### ISSUE TITLE
Title: Want to add a project under the section basic of artificial intelligent 

### ISSUE THREAD

**Issue by Riya922003** [Kushal997-das/Project-Guidance#1002]
### Is your proposal related to a problem? Please describe.

Project : OCR using YOLO v9 model with text and speech outputs .
Kindly assign this issue to me

**Comment by zeba62** [comment]
Can you please assign me with this issue?

**Comment by Kushal997-das** [comment]
@Riya922003 Not clear kindly give the relevant answer while creating the Issue.
