### ISSUE TITLE
GSSoC'24: Flappy Bird Game using Face Detection

### ISSUE THREAD

**Issue by SAM-DEV007** [Kushal997-das/Project-Guidance#1004]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like.

It is my implementation of flappy bird game which uses Python with packages OpenCV, and mediapipe. It belongs in `Artificial_Intelligence/Basic` section for using face detection.

I already made this repository that is public in my profile as a means to get hands-on practice on OpenCV and mediapipe.

### Describe alternatives you've considered.

The following website consists of the demo: https://ml-integrations.onrender.com/

Instagram Filters -> Flappy Bird

The website is hosted on a free hosting server, so it may take 5-10 min to load initially. Furthermore, the rendering of the frames will be slow due to limited processing power of the free server.

I only aim to add the Python functionality and not the web integration.

**Comment by vishuhere** [comment]
Steps I will be performing: 

1. I will set up a development environment and install the necessary libraries like MediaPipe and a game development framework like Pygame. 

2. I'll use MediaPipe to detect face movements or gestures to control the game, while also implementing the game mechanics such as the bird's movement and obstacles.

3. i’ll Implement the game logic, including collision detection between the bird and the pipes, scoring, and game over conditions.

4. I will be providing feedback to the player based on their face movements. For instance, you could display instructions or feedback on the screen based on how the player is moving their face.

It's a challenging project, but definitely doable with some coding skills and patience! 

Why me?

I am GSSOC'24 Contributor With deep expertise in CNNs and computer vision, I am well-suited for this project. My experience encompasses theoretical understanding and practical application, as demonstrated by presentations and project work. Recently I contributed to a startup where my role centered around the areas of computer vision (image recognition, object detection and pose estimation) and large language models (hallucination mitigation, access control, RAG, fine-tuning, knowledge graphs, dynamic policy enforcement) making me confident in contributing effectively to this endeavor.

**Comment by vishuhere** [comment]
There will be many more tasks i'll implement here including Refinement, Optimisation, Deployment etc. 

Please assign me this task and allow me to put a label of GSsoC24 in it.
