### ISSUE TITLE
GSSoC'24: WhisperCommand: A Whisper-to-Drone Interface Using Self-Made NLP"?

### ISSUE THREAD

**Issue by rohitagr0310** [Kushal997-das/Project-Guidance#1005]
### Is your proposal related to a problem? Please describe.

The problem it addresses is the challenge of enabling users to control drones using voice commands spoken in a whisper. Whispering can be challenging for traditional voice recognition systems to accurately interpret due to its lower volume and altered vocal characteristics. Additionally, understanding the intent behind the whispered commands and translating them into actionable instructions for the drone requires advanced natural language processing (NLP) capabilities. By combining whisper recognition technology with a self-made NLP system tailored for drone commands, the project aims to provide a solution to this problem, enabling users to control drones effectively even in quiet environments or situations where speaking loudly is not feasible.

**Comment by Kushal997-das** [comment]
@rohitagr0310 Try to add relevant screenshots.
