### ISSUE TITLE
GSSOC '24 : A Flask-Powered E-Commerce Website Built from Web-Scraped Data

### ISSUE THREAD

**Issue by rohitagr0310** [Kushal997-das/Project-Guidance#1008]
### Is your proposal related to a problem? Please describe.

ScrapToShop is an e-commerce website built using HTML, CSS, JavaScript, and Flask, designed to showcase products sourced from web-scraped data. Leveraging Flask's capabilities, the website offers a seamless browsing and shopping experience for users. The project addresses the challenge of aggregating product information from various websites and presenting it in a cohesive and user-friendly manner.

### Add any other context or screenshots about the proposal request here.

ScrapToShop provides a solution for businesses or individuals looking to set up an online store without maintaining an extensive inventory. By scraping product data from external websites, the website ensures a diverse range of offerings without the need for manual input. With its minimalist design and efficient functionality, ScrapToShop offers a hassle-free e-commerce solution for both sellers and buyers.

**Comment by shikham12** [comment]
please assign me this issue

**Comment by Kushal997-das** [comment]
@Kushal997-das You already created one issue work on that first .
