### ISSUE TITLE
Want to add hand gesture volume control under IOT 

### ISSUE THREAD

**Issue by Ayushi22-coder** [Kushal997-das/Project-Guidance#1013]
### Is your proposal related to a problem? Please describe.

Gesture-based system volume control is a way to control the volume of your computer using hand gestures. This can be done using a variety of different technologies, but one popular option is to use Python and OpenCV.

Tech Stack: Python and Open CV library.

### Add any other context or screenshots about the proposal request here.

https://i.imgur.com/XvkQGYy.png

**Comment by shikham12** [comment]
please assign me this issue
