### ISSUE TITLE
Title: AI Gym Tracker

### ISSUE THREAD

**Issue by Karansankhe** [Kushal997-das/Project-Guidance#1014]
### Is your feature request related to a problem? Please describe.

Counting reps accurately manually is challenging due to human error, distraction, or fatigue. An AI tracker solves this by providing precise, automated rep counting.

### Describe the solution you'd like.

An AI gym tracker automates rep counting accurately, eliminating human errors and ensuring precise workout data for optimal fitness tracking.

### Describe alternatives you've considered.

Tech stack: MediaPipe,OpenCV,Numpy

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by Kushal997-das** [comment]
@Karansankhe Already have.
