### ISSUE TITLE
A project on image processingTitle: 

### ISSUE THREAD

**Issue by 1arka02** [Kushal997-das/Project-Guidance#1023]
### Is your proposal related to a problem? Please describe.

i will like to add a short project which can detect clusters from image using KNN algorithm and calculate the distnace between the centers

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by Kushal997-das** [comment]
@1arka02 Already have!!
