### ISSUE TITLE
Would like to add a basic project to Web development- Rainforest Initiative Platform

### ISSUE THREAD

**Issue by shreyasadhasivam** [Kushal997-das/Project-Guidance#1024]
I'm a GsSOC '24 contributor. Please assign me this issue. I would like to add a basic project using HTML, CSS, JS and PHP

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by Kushal997-das** [comment]
@shreyasadhasivam Provide the details, without details, we can't proceed.

**Comment by shreyasadhasivam** [comment]
It's a basic web development project using html,css,php where the current projects can be seen and customers can contact through which we will receive mail.
