### ISSUE TITLE
Habit Tracker App in Flutter

### ISSUE THREAD

**Issue by vamzx** [Kushal997-das/Project-Guidance#1028]
### Is your feature request related to a problem? Please describe.

Beginners might be confused as to where to start with designing apps in Flutter

### Describe the solution you'd like.

This app tutorial will be easy to follow, and will also teach readers the importance and implementation of good UI, how to integrate other tools for backend such as Hive, and create a functioning app easily.

### Describe alternatives you've considered.

The best way to learn a tool is by practicing it. So beginners can use this project to learn how to use Flutter to build amazing apps and the third party tools that can be integrated to provide additional features that are used in most apps today.

### Add any other context or screenshots about the feature request here.

I am a GSSOC '24 contributor and I am working on many Flutter apps currently, so I can easily work on this. Please assign this to me

**Comment by vamzx** [comment]
@Kushal997-das Since this is a level 1 issue, is it okay if I make the app that depicts its UI without using firebase? I can parallelly raise another issue where I create an app with both frontend and backend. Please let me know if this works fine with you.

**Comment by vamzx** [comment]
@Kushal997-das could you please let me know? I am done with all the simple functionalities since this is a level 1 issue, I can add progress trackers and calendars as well if you ask me to. Thanks!

**Comment by Kushal997-das** [comment]
@vamzx Don't focus on level1 or level2 initially. Instead, concentrate on making high-quality contributions. If your PR is of good quality, we will assign an appropriate level. However, please note that only one PR is allowed per user in my repo for the first time. Avoid creating multiple PRs; just consolidate all your changes into a single PR.

Note: Ensure that the same project is not added to multiple repos, as it will be marked as spam.

**Comment by vamzx** [comment]
@Kushal997-das Sure, got it! So I have two issues assigned at the moment, one is for a game and one is for this tracker. Should I raise my PR with both the issues together?

**Comment by vamzx** [comment]
@Kushal997-das I have been trying to raise a PR but it says "Nothing to compared, both have different commit histories" 

Could you please help me out? I have finished worked on the project, I am just not able to raise a proper pull request for some reason

**Comment by Kushal997-das** [comment]
@vamzx Refer [this](https://opensource.com/article/19/7/create-pull-request-github)

**Comment by NamrataCSalvi** [comment]
I would like to work on this issue. Can you assign it to me

**Comment by vamzx** [comment]
@Kushal997-das Could you please check the PR for this issue?
