### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TawfikYasser** [Kushal997-das/Project-Guidance#104]
Hi @Kushal997-das 

I have a suggestion, It’s about creating a simple `GitHub Action` to show a **Greeting** message for a person who open a new issue or a pull request.

If you agree, I want to do it, And please assign it to me.

Thanks

**Comment by Kushal997-das** [comment]
@TawfikYasser You can do.

**Comment by SamarpanCoder2002** [comment]
> Hi @Kushal997-das
> 
> I have a suggestion, It’s about creating a simple `GitHub Action` to show a **Greeting** message for a person who open a new issue or a pull request.
> 
> If you agree, I want to do it, And please assign it to me.
> 
> Thanks

Yah sure, You can do it

**Comment by TawfikYasser** [comment]
Okay Thanks

**Comment by TawfikYasser** [comment]
Are you have specific template? Or I make one by myself? @Kushal997-das

**Comment by Kushal997-das** [comment]
> Are you have specific template? Or I make one by myself? @Kushal997-das

@TawfikYasser What do you think what is the need of template?

**Comment by TawfikYasser** [comment]
I think it should greeting the person, then give some guidelines about contributing to this repo ref. to CONTRIBUTING file, and give a brief example about how project should contains.

**Comment by Kushal997-das** [comment]
> I think it should greeting the person, then give some guidelines about contributing to this repo ref. to CONTRIBUTING file, and give a brief example about how project should contains.

@TawfikYasser Awesome you can do i already assign you for this :) 
After sending PR lemme know :)

**Comment by TawfikYasser** [comment]
Okay,  Thanks @Kushal997-das

**Comment by TawfikYasser** [comment]
Hi @Kushal997-das , I have created the file yml for the GitHub action. I hope you like it. Thanks :)

**Comment by TawfikYasser** [comment]
The PR created #110

**Comment by Kushal997-das** [comment]
@TawfikYasser Thanks
