### ISSUE TITLE
Add PR template 

### ISSUE THREAD

**Issue by suhanipaliwal** [Kushal997-das/Project-Guidance#1049]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by Kushal997-das** [comment]
@suhanipaliwal We have alredy PR template but yeah if your one looks better will add.
