### ISSUE TITLE
Title:  An AI Assistant using openai api and voice recognition system 

### ISSUE THREAD

**Issue by Avishek8136** [Kushal997-das/Project-Guidance#1050]
### Is your proposal related to a problem? Please describe.

Yes, For beginners who love the AI and want to make an assistant it can be a interesting project.
Please assign me this issue under GSSOC24.

**Comment by Avishek8136** [comment]
Also documenntation will be there

**Comment by Kushal997-das** [comment]
@Avishek8136 You already created one issue before please focus on that.

**Comment by Avishek8136** [comment]
Previous work is completed
