### ISSUE TITLE
Want to add a to-do list made using react js and contex api in web development part

### ISSUE THREAD

**Issue by AnitSarkar123** [Kushal997-das/Project-Guidance#1053]
You decide what will be the level for the project 

Please assign me under GSSOC'24

**Comment by Kushal997-das** [comment]
@AnitSarkar123 No proper way  of creating an issue.

**Comment by AnitSarkar123** [comment]
Then what is the proper way sir @Kushal997-das

**Comment by Kushal997-das** [comment]
@
