### ISSUE TITLE
Title: MACHINE LEARNING BASED SMS SPAM DETECTOR 

### ISSUE THREAD

**Issue by SuryanshuKushwaha** [Kushal997-das/Project-Guidance#1054]
### Is your proposal related to a problem? Please describe.

@Kushal997-das 
-> I want to add a project based on  Machine Learning enthusiastics , it is a SMS spam filter which verifies that a message is a spam or a ham (message which is not spam) with accuracy. 
-> Helps uneducated people by not caught in trap of spam message.

### Add any other context or screenshots about the proposal request here.

![Screenshot (39)](https://github.com/Kushal997-das/Project-Guidance/assets/114632428/25cb688f-73cf-4bfd-9ba7-ae6a221a35d3)

**Comment by saikrishna823** [comment]
Hey,I would like to work on this issue.I have strong knowledge Machine Learning and Deep learning.We can implement this project with the help of Naive Byes algorithm.I will also create a user interface with the help of streamlit.Pleae assign this issue to me

**Comment by Kushal997-das** [comment]
@saikrishna823 Already have.
