### ISSUE TITLE
Title: Creation of an editing software using Numpy

### ISSUE THREAD

**Issue by litesh1123** [Kushal997-das/Project-Guidance#1062]
### Is your proposal related to a problem? Please describe.

Yes with normal webcam or camera we can detect different kind of images  like Hsv , negative , gray scale ,detect face and rest all blurred, adding filters etc.
> Most of people dont know that we can take thermal images using webcam or camera of laptop with numpy which gives same level of input as a thermal image-capturing device
![hsv](https://github.com/Kushal997-das/Project-Guidance/assets/139573484/fe84b5ee-dd41-4164-81b5-e7a89e683fc3)
> We can capture live video in thermal, negative, grey etc

The highlight of this project is teaching usage of Python in image creation, manipulation etc
> This project will teach how Python can be used to manipulate images and take different forms of images which have quality equivalent to devices used for detecting specific types of images

**Comment by litesh1123** [comment]
Sir in this issue i will create algorithm and core functionalities can u please label3 or 2 sir as it will be helpful for me ,I will be making it from scratch

**Comment by litesh1123** [comment]
@Kushal997-das Sir because of some exam issues I was not active project is ready if you open it I will push the code sir

**Comment by Kushal997-das** [comment]
@litesh1123 Submit it ASAP

**Comment by litesh1123** [comment]
Ok sir Thank you sir

**Comment by litesh1123** [comment]
@Kushal997-das Sir projects is done shall I add this folder to desktop application ?
