### ISSUE TITLE
Feature for auto commenting on a new issue creation 

### ISSUE THREAD

**Issue by suhanipaliwal** [Kushal997-das/Project-Guidance#1075]
I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

**Comment by Kushal997-das** [comment]
@suhanipaliwal Add also for PR for the same.
