### ISSUE TITLE
Title: [Project Addition] Brain Tumor Detection 

### ISSUE THREAD

**Issue by Karthik110505** [Kushal997-das/Project-Guidance#1082]
🔴 Project Title : Brain Tumor Detection 

🔴 Aim : Detect and draw bounding boxes around a Brain Tumor

🔴 Dataset :https://www.kaggle.com/datasets/pkdarabi/medical-image-dataset-brain-tumor-detection

🔴 Approach : I build a model inorder to detect the brain tumor and draw bounding boxes around it using yolov8, and its similar models.

Please assign me this issue @Kushal997-das

**Comment by Kushal997-das** [comment]
@Karthik110505 The same issue you created [here](https://github.com/SrijanShovit/HealthLearning/issues/135) Don't spam please.

**Comment by Karthik110505** [comment]
@Kushal997-das  Sorry, I didn't mean to. And also both issues might be similar but one is a detection problem and other is a segmentation problem, so I added them.
