### ISSUE TITLE
Update WhatsApp Chat Analyser Project

### ISSUE THREAD

**Issue by YuktaG123** [Kushal997-das/Project-Guidance#1085]
### Is your feature request related to a problem? Please describe.

There are less features in the current WhatsApp Chat Analyser Project. I want to add more functionalities in the same .

### Describe the solution you'd like.

I will enhance the visualisations and the emoji analysis as well. 

### Describe alternatives you've considered.

It will enhance the user interface.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-04-03 202104](https://github.com/Kushal997-das/Project-Guidance/assets/112880670/913def09-a572-478a-a4c1-4d6dd68adc31)

**Comment by YuktaG123** [comment]
@Kushal997-das please assign the labels of gssoc and level 2 .

**Comment by YuktaG123** [comment]
@Kushal997-das please assign this project to me.

**Comment by swati-singh23** [comment]
@Kushal997-das request you to assign me this issue. Thank You.

**Comment by MADHAV0704** [comment]
please assign me this issue

**Comment by Kushal997-das** [comment]
@YuktaG123 Update on this else will close this issue.
