### ISSUE TITLE
Title: To add flower Classifier to AI-Intermediate

### ISSUE THREAD

**Issue by shrehs** [Kushal997-das/Project-Guidance#1088]
### Is your proposal related to a problem? Please describe.

I believe it would be great to add a flower classifier model to the project which could enhance the reach. The classifier uses compose transformer and pre-trained model VGG16. Please do assign this to me.
Thank you!

**Comment by Kushal997-das** [comment]
@shrehs Closing this for now if your first PR got merged then will assign you in this project.
