### ISSUE TITLE
Dataset for EDA on NETFLIX DATA

### ISSUE THREAD

**Issue by biswajeetyadavv** [Kushal997-das/Project-Guidance#1091]
### Explain what you want to add/change in documentation.

I was working in EDA on Netflix data from the domain - of machine learning and data science, basic. where I found out there is no dataset  Therefor, I have got the dataset which is fetched and matches with Python code in it. 

![Screenshot for no dataset available](https://github.com/Kushal997-das/Project-Guidance/assets/126945506/7838b665-f129-4b61-a3ad-8adc2c895481)

**Comment by Kushal997-das** [comment]
@biswajeetyadavv Good catch , make sure you work with latest data.
