### ISSUE TITLE
Title: Adding dark mode to Basic calculator app

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Kushal997-das/Project-Guidance#1094]
### Is your feature request related to a problem? Please describe.

Adding dark mode to Basic calculator app

### Describe the solution you'd like.

I would like to add dark mode to basic calculator app

### Describe alternatives you've considered.

I would like to add dark mode to basic calculator app

**Comment by SuhainaFathimaM** [comment]
@Kushal997-das Please assign me this under GSSoC 2024

**Comment by Kushal997-das** [comment]
@SuhainaFathimaM We have this project already if you want to improve the existing project you may create new issue for this .
