### ISSUE TITLE
Title: Improvised UI for BaseX calculator 

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Kushal997-das/Project-Guidance#1095]
### Is your feature request related to a problem? Please describe.

 Improvised UI for BaseX calculator 

### Describe the solution you'd like.

 Improvised UI for BaseX calculator 

### Describe alternatives you've considered.

 Improvised UI for BaseX calculator

**Comment by SuhainaFathimaM** [comment]
@Kushal997-das Please assign me this under GSSoC 2024

**Comment by Kushal997-das** [comment]
@SuhainaFathimaM Hi, kindly mentioned all your issues in my [Linkedin](https://www.linkedin.com/in/kushal-das-7337421a9/), with issue number

**Comment by Kushal997-das** [comment]
@SuhainaFathimaM Kindly give us SS , let me show the UI first , how is different from the existing one.
