### ISSUE TITLE
Title: Prediction on Cancer Data Analysis ( Advanced )

### ISSUE THREAD

**Issue by Royal-Emine** [Kushal997-das/Project-Guidance#1100]
### Is your proposal related to a problem? Please describe.

It's not particularly a problem but a suggestion(Request) to include this advanced project into the Machine learning and Data Science sector of the Advanced folder for an elevation of the repository.

### Add any other context or screenshots about the proposal request here.

I have the BERT embedded ONCORTT dataset which is not very easily accessible with proper source code that can get included in this repository.

**Comment by Kushal997-das** [comment]
@Royal-Emine As you already added one project , and this issue is not fit for this Repo, we are closing this
