### ISSUE TITLE
Title: Colorization of Pictures

### ISSUE THREAD

**Issue by Royal-Emine** [Kushal997-das/Project-Guidance#1108]
### Is your proposal related to a problem? Please describe.

Its basically a new project under the Advanced/Intermediate sector of Artificial Intelligence which will enhance the repository value because both the folders are empty.

### Add any other context or screenshots about the proposal request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/112507451/0fe4e107-3444-448a-9994-88183d488827)

It looks somewhat like this while the code (Python) is implemented.

**Comment by Kushal997-das** [comment]
@Royal-Emine Only one project allowed under Gssoc , kindly approach other repo.
