### ISSUE TITLE
Markdown Previewer

### ISSUE THREAD

**Issue by AmrutaJayanti** [Kushal997-das/Project-Guidance#1129]
I would like to add under Web Development, Markdown Previewer which takes the markdown code and renders HTML element. Please assign me this under GSSOC'2024

**Comment by Kushal997-das** [comment]
@AmrutaJayanti Explain in details

**Comment by AmrutaJayanti** [comment]
![Screenshot 2024-05-30 193250](https://github.com/Kushal997-das/Project-Guidance/assets/142327526/756df47e-19ef-4154-8c1d-a4e93a9db178)
As you enter the markdown code, it renders the HTML element. Its beginner friendly. It helps beginners to acustomate for writing markdown codes.
