### ISSUE TITLE
Updating readme.md

### ISSUE THREAD

**Issue by saikuladeepgithub** [Kushal997-das/Project-Guidance#1132]
### Explain what you want to add/change in documentation.

Hi,The readme file is absolutely good. But we have to place the emojis in a good way. They are attched to the contributing.md link in the readme file while redirecting whick looks not good. So if you assign this i will do it sir.

**Comment by Kushal997-das** [comment]
@saikuladeepgithub Which `readme.md` file are you talking about.

**Comment by saikuladeepgithub** [comment]
Hi sir, now it's absolutely good sir. I want to make some changes in emojis in readme file. That's why I have raised an issue.
Now it's absolutely good sir.
Thank you sir

**Comment by Kushal997-das** [comment]
@saikuladeepgithub In which `readme.md` are you talking about ?
