### ISSUE TITLE
Add flutter project

### ISSUE THREAD

**Issue by Nikitakandwal** [Kushal997-das/Project-Guidance#1134]

**Comment by SivaRamana-H-V** [comment]
Hay, kindly assign to me work on this part

**Comment by Shubham-Zone** [comment]
@Kushal997-das assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter
![Screenshot_2024-04-17-21-42-35-11](https://github.com/Kushal997-das/Project-Guidance/assets/154971588/76d93571-c10a-4110-bef3-ab328e4af6b5)
![Screenshot_2024-04-17-21-45-16-21](https://github.com/Kushal997-das/Project-Guidance/assets/154971588/c80df676-ef21-4970-97c4-54a38c5b1afa)
![Screenshot_2024-04-17-21-45-27-06](https://github.com/Kushal997-das/Project-Guidance/assets/154971588/62e66870-3bf1-4f4c-b097-7f235fcb7772)
![Screenshot_2024-04-17-21-45-48-95](https://github.com/Kushal997-das/Project-Guidance/assets/154971588/ab185a44-253d-4f6d-a678-8060d7f3131f)
![Screenshot_2024-04-17-21-48-16-40](https://github.com/Kushal997-das/Project-Guidance/assets/154971588/a34220fb-733b-46db-83d1-9767b25968e2)
