### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TawfikYasser** [Kushal997-das/Project-Guidance#114]
Hi @Kushal997-das , @SamarpanCoder2002 

I have a new suggestion

What is your opinion about creating a TEMPLATE for the PR

to make it easy for the contributor to explain PR and it’s importance to make it also more easier for reviewer to review it.

Thanks

**Comment by Kushal997-das** [comment]
@TawfikYasser I also thinks like that but for my busy schedule I can't do this now . 
You can do this @TawfikYasser 👍

**Comment by TawfikYasser** [comment]
Okay, I will do that :)
Thanks

**Comment by UG-SEP** [comment]
Hey,
@TawfikYasser  & @Kushal997-das  this issue no #114 has been resolve please close it
