### ISSUE TITLE
Title: QUIZ Desktop Application 

### ISSUE THREAD

**Issue by sahuf2003** [Kushal997-das/Project-Guidance#1159]
### Is your proposal related to a problem? Please describe.

A quiz app in Python uses Tkinter for Gui and for the quiz question it uses API. It also emails the user their score. It also saves the user information in the CSV file.

With the help of this learners will be able to learn how to use API in Python as well as a Tkinter in python.
It also uses smtplib.

### Add any other context or screenshots about the proposal request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/127684377/5920546a-e25b-4eb4-ba24-6c92cf7567f4)
![image](https://github.com/Kushal997-das/Project-Guidance/assets/127684377/f09d71a2-2da4-45c7-908d-6a6d1941c353)
![image](https://github.com/Kushal997-das/Project-Guidance/assets/127684377/669d3a2d-0ea9-4e7d-a251-295662d56e00)

**Comment by sahuf2003** [comment]
@Kushal997-das  assign me this issue

**Comment by khushi-igupta** [comment]
Hello @sahuf2003 , I am GSSOC'24 contributor and I want to work on this issue. Kindly assign me this issue.
