### ISSUE TITLE
Title: Amazon Landing Page  

### ISSUE THREAD

**Issue by saiumasankar** [Kushal997-das/Project-Guidance#1167]
### Is your proposal related to a problem? Please describe.

I would like to contribute by adding my project in Web Development folder. My project is landing page of Amazon. I built a clone of Amazon using HTML and CSS.

**Comment by saiumasankar** [comment]
Please assign this issue.

**Comment by Kushal997-das** [comment]
Will check and let you know.

**Comment by Kushal997-das** [comment]
@saiumasankar Provide more details.

**Comment by saiumasankar** [comment]
@Kushal997-das I cloned the amazon landing page along with login and sign up pages too. I have done it from scratch without using any tools. I wrote the HTML and CSS code which clones the landing page of Amazon e-commerce.

This is the photo of the amazon landing page designed by me.

![amazonclonepic](https://github.com/Kushal997-das/Project-Guidance/assets/119750857/e285eb37-a53d-4a12-b62a-9f2a7331aac7)

**Comment by Kushal997-das** [comment]
@saiumasankar Make sure the same project doesn't exits in the repo already.

**Comment by saiumasankar** [comment]
Hi @Kushal997-das I have checked all the projects in the web development. My project doesn't exists in any of the repos.

**Comment by saiumasankar** [comment]
I sent PR. Please review this PR and assign the PR to me.
