### ISSUE TITLE
Cartoonify-Images 

### ISSUE THREAD

**Issue by jeet-Abhi123** [Kushal997-das/Project-Guidance#1172]
One such project that serves as inspiration uses only core OpenCV filters and functions to cartoonize images and videos. The picture is also compressed using the K-means clustering algorithm. It has the necessary cartoonish undertone thanks to this clustering.

By using the K-means algorithm and opencv we will make an image look like cartoon.
Please assign me this project under GSSOC'24

**Comment by khushi-igupta** [comment]
Hello @jeet-Abhi123  , I am GSSOC'24 contributor and I want to work on this issue. Kindly assign me this issue.
