### ISSUE TITLE
Password Strength Checker ML 

### ISSUE THREAD

**Issue by AkhilYadavPadala** [Kushal997-das/Project-Guidance#1177]
### Is your feature request related to a problem? Please describe.

A password strength checker works by understanding the combination of digits, letters, and special symbols we use in our password. It is created by training a machine learning model on a labelled dataset of different combinations of letters and special symbols people use in passwords. The model learns from data about what combinations of letters and symbols can be classified as a solid or weak password.

### Describe the solution you'd like.

So, I would like to implement an ML algorithm(Random Forest Classifier) to check the strength of the password with a model score of 0.81 and deploy it as a web app.

### Describe alternatives you've considered.

I would like to deploy it as a web app so that users can easily get access to the model.

### Add any other context or screenshots about the feature request here.

![Screenshot (326)](https://github.com/Kushal997-das/Project-Guidance/assets/142014008/3c48ef24-ff5c-41e9-953d-71223968814b)

**Comment by Kushal997-das** [comment]
@AkhilYadavPadala Please complete with the first issue .

**Comment by AkhilYadavPadala** [comment]
Alright 👍
