### ISSUE TITLE
Edit Web Dev project ( Weather App)

### ISSUE THREAD

**Issue by sristy17** [Kushal997-das/Project-Guidance#1180]
Will add a web development project.(Weather App) using reactjs

**Comment by sristy17** [comment]
> @sristy17 Please check this project already there in my repo [this](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development/Basic/Weather%20App) What changes are you gonna make in your project kindly mention that with images.

As I can see, the weather project that is already added is a vanila js project whereas, I was planning to add a react js project, with more funtionalities. Or else I can modify the recent projects with more detials datas like max temp, min temp and more or mybe some more styling?

**Comment by Kushal997-das** [comment]
@sristy17 Modify the existing project with more details and new features. Make sure you deploy the link and paste into the `readme. md` file.

**Comment by sristy17** [comment]
> @sristy17 Modify the existing project with more details and new features. Make sure you deploy the link and paste into the `readme. md` file.

I have made changes also raised a pr please review and merge it. 
 
thank you!
