### ISSUE TITLE
Title: Covid-19 X-Ray Image Classification

### ISSUE THREAD

**Issue by aaradhyasinghgaur** [Kushal997-das/Project-Guidance#1183]
### Is your proposal related to a problem? Please describe.

**Description :-** The Coronavirus Disease 2019 (COVID-19) has brought a worldwide threat to the living society. The whole world was putting incredible efforts to fight against the spread of this deadly disease. Meanwhile, hundreds of machine-learning experts volunteer their time and expertise to help medical researchers in this fight.

**Aim :-** One of the areas where machine learning can help is detecting the COVID-19 cases from chest X-ray images. The task is a simple classification problem where given an input chest X-ray image, the machine learning-based model must detect whether the subject of study has been infected or not.

**Dataset I'll use :-** https://www.kaggle.com/datasets/pranavraikokte/covid19-image-dataset

**Solution I propose :-** 
1.) Using 5 different available network architectures such as Xception , DenseNet121 , VGG16 etc. to do catagorical classification for chest X-ray to detect COVID19 symptoms .
2.) use data augmentation techniques to improve the accuarcy of models.
3.) Comparing performance and accuracy of models using accuracy score ,loss and accuracy graph , confusion matrix for better understanding.
4.) Perfroming EDA (data analysis) for dataset to understand the structure of data.
5.) Using README file for describing the work I've performed.

**Kindly assign this issue to me @Kushal997-das  and lable it as level-3 if possible as I'm training and testing dataset for 5 different models which is resource and time consuming and also making doucumentation about which works better > I will also be doing EDA analysis for the dataset.**

I want to add this project in advance ml/data science repo

**Comment by aaradhyasinghgaur** [comment]
@Kushal997-das kindly assign this issue to me please.

**Comment by Kushal997-das** [comment]
@aaradhyasinghgaur, I'm assigning this to you, but please ensure that this project doesn't already exist in the repository.
