### ISSUE TITLE
I am a candidate of GSSOC'24 and I want to contribute a Web Development project

### ISSUE THREAD

**Issue by SriramChowdaryMogalapu** [Kushal997-das/Project-Guidance#1190]
I am a candidate of GSSOC'24 and I want to contribute a Web Development project which is an Image Carousel which allows user to add and remove images and shows the images. It also have a chat box API integration. Please assign me this

![image](https://github.com/Kushal997-das/Project-Guidance/assets/103817400/e6184d91-1ad2-496c-8a1e-b6e5b593c617)
![image](https://github.com/Kushal997-das/Project-Guidance/assets/103817400/b751f9d1-44c8-4345-8d76-dff9fee478ae)

**Comment by Babuprasanth27** [comment]
Hey, I am interested in fixing this issue. could you assign it to me?

**Comment by Kushal997-das** [comment]
> Hey, I am interested in fixing this issue. could you assign it to me?

Please create your own new issue with new project idea .
