### ISSUE TITLE
Title: Adding BMI calculator project 

### ISSUE THREAD

**Issue by Braj-01** [Kushal997-das/Project-Guidance#1198]
### Is your feature request related to a problem? Please describe.

BMI calculator is a basic project for understanding frontend technologies.

### Describe the solution you'd like.

Adding BMI calculator in basic project section of web development

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

N/A

**Comment by Babuprasanth27** [comment]
Hey, I am interested in fixing this issue. could you please assign it to me?
