### ISSUE TITLE
There are two work flows for greeting 

### ISSUE THREAD

**Issue by thevijayshankersharma** [Kushal997-das/Project-Guidance#1200]
### What happened?

There are two work flows for greeting means duplicates.

### How can we reproduce this bug?

Raise any issue or check the raised issue.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/109781385/70539630-3f63-421f-b250-abb0f2744547)

### Urgency (Optional)

Medium priority

**Comment by Kushal997-das** [comment]
@Adhetya Thanks for highlighting but this issue is already solved.
