### ISSUE TITLE
Title: Improve header and footer

### ISSUE THREAD

**Issue by AkhilaSunesh** [Kushal997-das/Project-Guidance#1202]
### Is your feature request related to a problem? Please describe.

Improve the UI of header and footer

### Describe the solution you'd like.

use logos and increase the text.

### Describe alternatives you've considered.

Making a better UI

**Comment by Babuprasanth27** [comment]
Hey, I am interested in fixing this issue. Please assign it to me.

**Comment by Kushal997-das** [comment]
@AkhilaSunesh What UI explain in details .
