### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by Tejashri-Taral** [Kushal997-das/Project-Guidance#1205]
### Is your feature request related to a problem? Please describe.

I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Describe the solution you'd like.

I would like to add a "scroll top" button to a web page. This button should appear when the user scrolls down the page, and when clicked, it should smoothly scroll the page back to the top.

### Describe alternatives you've considered.

One alternative solution could be to implement a fixed-positioned button that always stays visible on the screen, regardless of scrolling. This approach ensures that users can easily access the "scroll top" functionality without needing to scroll back up the page to find the button

### Add any other context or screenshots about the feature request here.

Screenshot:

![image](https://github.com/Kushal997-das/Project-Guidance/assets/160386036/f049e934-74d2-468a-86a0-697ad30b65d3)

**Comment by aikansh008** [comment]
please assign this issue to me
