### ISSUE TITLE
Title: Text Translator 

### ISSUE THREAD

**Issue by AmrutaJayanti** [Kushal997-das/Project-Guidance#1209]
### Is your proposal related to a problem? Please describe.

Text translation is made easier using `Text Translator`

### Add any other context or screenshots about the proposal request here.

![Screenshot 2024-06-17 110448](https://github.com/Kushal997-das/Project-Guidance/assets/142327526/0ea88a18-dc73-4229-9c1f-2d5651e56d1c)
![Screenshot 2024-06-17 110455](https://github.com/Kushal997-das/Project-Guidance/assets/142327526/f1b9caf7-bac1-4c3b-b894-2920345c617a)

**Comment by Kushal997-das** [comment]
@AmrutaJayanti Is this only translate to Telugu?

**Comment by AmrutaJayanti** [comment]
Actually I provided options for Hindi , Malayalam ,Telugu ,Bengali ,French ,Spanish .

**Comment by AmrutaJayanti** [comment]
![Screenshot 2024-06-19 155937](https://github.com/Kushal997-das/Project-Guidance/assets/142327526/04a826d7-e0ed-4fae-8a77-f66be8e9708e)
![Screenshot 2024-06-19 155948](https://github.com/Kushal997-das/Project-Guidance/assets/142327526/8a5fe103-415b-46cb-9553-56ac04d6986f)
![Screenshot 2024-06-19 160004](https://github.com/Kushal997-das/Project-Guidance/assets/142327526/ae119e9e-c717-4619-8809-45f2a644020f)
![Screenshot 2024-06-19 155919](https://github.com/Kushal997-das/Project-Guidance/assets/142327526/71331945-d2b7-493b-9b8a-d90bba2c6df7)
