### ISSUE TITLE
want to add image to browser tab

### ISSUE THREAD

**Issue by Shreyaa173** [Kushal997-das/Project-Guidance#1210]
### What happened?

there is no image at browser tab
![image](https://github.com/Kushal997-das/Project-Guidance/assets/144673309/f4244247-5032-4540-8b66-52692630ca2c)

### How can we reproduce this bug?

no

### Urgency (Optional)

High priority

**Comment by Shreyaa173** [comment]
![image](https://github.com/Kushal997-das/Project-Guidance/assets/144673309/7ca8d39d-8bbf-41b1-bd1c-338b138c3265)
How to proceed?

**Comment by aikansh008** [comment]
please assign this issue to me '
