### ISSUE TITLE
want to provide a logo

### ISSUE THREAD

**Issue by Shreyaa173** [Kushal997-das/Project-Guidance#1211]
### What happened?

there is no logo
![image](https://github.com/Kushal997-das/Project-Guidance/assets/144673309/e97c2ce7-51f9-4708-9437-5485a676a2e3)

### How can we reproduce this bug?

no

### Urgency (Optional)

High priority

**Comment by Kushal997-das** [comment]
@Shreyaa173 Please use this fix in issue #1210. There is no need to create a new issue for this.
