### ISSUE TITLE
Some project redirect links are either not redirecting to the correct folder or are returning a 404 Error.

### ISSUE THREAD

**Issue by Kushal997-das** [Kushal997-das/Project-Guidance#1213]
### What happened?

There are a few projects in [this README.md file](https://github.com/Kushal997-das/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md). However, when we click on them, instead of redirecting to the respective folder under Project-Guidance, they are directed to a different folder.

### How can we reproduce this bug?

"Please check this project. When you click on the following link, you will be redirected to the appropriate folder: [Online Gaming Portal Template](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development/Intermediate/Online%20Gaming%20Portal%20Template), located under Kushal997-das/Project-Guidance/Intermediate.

### Urgency (Optional)

Medium priority

**Comment by n-keerthi-gayathri** [comment]
@Kushal997-das please assign me this issue, I am GSSoC'24 Contributor

**Comment by Kushal997-das** [comment]
@n-keerthi-gayathri Go ahead!

**Comment by NamrataCSalvi** [comment]
I would like to work on this issue. Can you assign it to me

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24. @Kushal997-das

**Comment by DHARMESH-RAJ-1** [comment]
I would like to work on this issue , i am confident that i can fix the issue . please assign this issue to me.
