### ISSUE TITLE
Title: Navbar Background Change

### ISSUE THREAD

**Issue by driyash9881** [Kushal997-das/Project-Guidance#1215]
## Problem Description

Navbar have a plain background that needs to be made more interactive and visually appealing. To achieve this, the  plan is to implement **Glassmorphism** — a design trend characterized by frosted-glass effects, soft shadows, and vibrant colors, which together create a sophisticated and modern look.
The navbar

### Describe the solution you'd like.

To transform the plain background into a more engaging design using Glassmorphism,

1. **Will Create a Frosted Glass Effect**:
   - Use CSS properties such as `backdrop-filter`, `border-radius`, and `box-shadow` to create the appearance of frosted glass.
   - Will Apply transparency using `rgba` values in `background-color` to allow the underlying elements to show through.

2. **Enhance the Background**:
   -  background image or gradient behind the glass effect to provide depth and contrast.
   - Incorporate vibrant colors or subtle patterns to complement the glass effect.

3. **Implement Interactive Elements**:
   - Integrate hover effects, transitions, and animations to enhance user interaction.

### Describe alternatives you've considered.

A plain background can often appear dull and uninspiring. To create a more engaging and polished user experience, we propose adding a clean background with a border. This approach aims to blend simplicity with elegance, providing a structured and modern look that can be enhanced further with design techniques like Glassmorphism.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/118407844/d2ad3438-f092-4697-97fa-362f820bf8ed)

**Comment by Babuprasanth27** [comment]
Hey, Shall I fix this issue?

**Comment by aikansh008** [comment]
please assign this issue to me
