### ISSUE TITLE
Title: Add 'Back-To-Top' Button on All Pages

### ISSUE THREAD

**Issue by AsmitaMishra24** [Kushal997-das/Project-Guidance#1217]
### Is your feature request related to a problem? Please describe.

The addition of a "Back to Top" button on the homepage of our website would enhance user experience by providing a convenient way for users to quickly return to the top of the page after scrolling down. This feature is commonly seen on many websites and has become an expected element for smooth navigation.

### Describe the solution you'd like.

1. Explore alternative placement options for the "Back to Top" button, such as a floating button that dynamically appears as users scroll down.
2. Implement the relocation of the "Back to Top" button in a manner that enhances both its visibility and usability without compromising the overall design aesthetics of the website.

### Describe alternatives you've considered.

Button Up: Button Up is another alternative that serves the same purpose. It’s designed to be unobtrusive and provides a simple way for users to return to the top of a long page.

### Add any other context or screenshots about the feature request here.

My Previous Work:-
https://github.com/Kushal997-das/Project-Guidance/assets/146121869/c57ac768-189d-4803-8a02-a392db7baa12

**Comment by ShagunSharma17** [comment]
Hi @AsmitaMishra24 please assign this task under GSSOC'24
