### ISSUE TITLE
Title: Image Processing Advanced C++ application 

### ISSUE THREAD

**Issue by somaiaahmed** [Kushal997-das/Project-Guidance#1230]
### Is your feature request related to a problem? Please describe.

This is a simple image processing application created using Qt and OpenCV. It allows users to load images, apply basic image processing operations (such as grayscale and blur), and save the processed images.

### Describe the solution you'd like.

Features
The application provides the following features:

Load Image: Users can load an image of various formats (e.g., PNG, JPEG, BMP) using the "Load Image" button.
Blur Image: Apply Gaussian blur to the loaded image using the "Blur" button. The blur intensity can be adjusted using the slider.
Rotate Image: Rotate the image by 90 degrees clockwise or counterclockwise using the "Rotate" and "Right Rotate" buttons.
Grayscale: Convert the image to grayscale using the "Gray" button.
Resize Image: Resize the image to 75% of its original size using the "Resize" button. This can be repeated multiple times.
Clear Image: Restore the original image by clearing any applied filters or transformations.
Sharpness: Apply a sharpening filter to enhance image details using the "Sharp" button.
Flip Image: Flip the image horizontally using the "Flip" button.
Enlarge Image: Increase the image size by 25% using the "Enlarge" button.
Brightness and Contrast: Adjust image brightness and contrast using sliders provided under the "Brightness" and "Contrast" buttons.
White Balance: Automatically balance white levels in the image using the "Color" button.
Crop Image: Select a region in the image to crop using the "Crop" button. Click and drag to select the cropping area.
Save Image: Save the processed image to your desired location and format (e.g., PNG, JPEG, BMP) using the "Save" button.

### Describe alternatives you've considered.

alternatives to implement undo/redo functionality

**Comment by somaiaahmed** [comment]
@Kushal997-das plzz assign me to this issue and put appropriate labels

**Comment by Kushal997-das** [comment]
@somaiaahmed Hi, at a time one issue only.
