### ISSUE TITLE
Add Investigating Netflix Movies Analysis Project To Basic Machine learning and Data Science 

### ISSUE THREAD

**Issue by Salma-Mamdoh** [Kushal997-das/Project-Guidance#1231]
### Is your feature request related to a problem? Please describe.

The project aims to investigate whether the duration of Netflix movies has been decreasing over time. This involves analyzing a dataset of Netflix movies to identify trends in movie durations and examining how these trends vary across different genres.

### Describe the solution you'd like.

This project investigates trends in Netflix movie durations using pandas, seaborn, and matplotlib. The dataset, sourced from netflix_data.csv, undergoes cleaning to remove missing values and filter movies. Exploratory data analysis includes basic statistics and visualizations like histograms and scatter plots to identify trends over time. Genre-specific analysis enhances insights by color-coding movie durations across different genres. Regression analysis further validates trends, showing a potential decline in average movie durations over recent years. Overall, this structured approach provides actionable insights into Netflix content trends, aiding in strategic decision-making for future content production.
![Screenshot 2024-06-22 044100](https://github.com/Kushal997-das/Project-Guidance/assets/52897508/df9e9c66-82b0-47ed-a2f7-12de3ea85fe6)

### Describe alternatives you've considered.

the project focuses on analyzing Netflix movie data to investigate trends in movie durations over time. It employs Python's pandas for data manipulation and seaborn/matplotlib for visualization. The dataset is cleaned to remove missing values and filter movies specifically. Exploratory data analysis includes basic statistics and scatter plots to visualize trends in movie durations across different genres. Regression analysis further validates these trends, indicating a potential decline in average movie durations. The findings aim to provide actionable insights for content strategy at Netflix based on viewer preferences and industry trends.

**Comment by Salma-Mamdoh** [comment]
@Kushal997-das  plz assign me to this issue and give appropriate labels

**Comment by Vedant988** [comment]
@Kushal997-das  plz assign me to this issue. I will try my best

**Comment by Kushal997-das** [comment]
@Salma-Mamdoh Please focus on one issue at a time. Connect with me on LinkedIn once your first PR is merged, and I'll reopen the issue then.

**Comment by Vedant988** [comment]
I didn't found the dataset of Netflix Basic ML And DS folder,  Can you help
me with that?
