### ISSUE TITLE
Title: Restaurant Recommender 

### ISSUE THREAD

**Issue by pavitraag** [Kushal997-das/Project-Guidance#1234]
### Is your feature request related to a problem? Please describe.

I'm always frustated when I have to search good restaurants nearby.

### Describe the solution you'd like.

This recommender is used for recommending the nearest restaurants given the location of user.

### Describe alternatives you've considered.

N/A

**Comment by pavitraag** [comment]
@Kushal997-das Please this to me under gssoc24

**Comment by ghsharma** [comment]
the project works well , but just do these small changes in your readme file :
1. include pictures of your project .
2. and summaries the points shortly giving crisp information.

everything else is perfect and shall be merged.
