### ISSUE TITLE
Title: Stock Market Prediction (Deep Learning Algorithms-neural networks with fine tuning and advanced optimization methods)

### ISSUE THREAD

**Issue by ranamanish674zu** [Kushal997-das/Project-Guidance#1238]
### Is your feature request related to a problem? Please describe.

basically if some business man work with their work they feeling confused to select the stock market and how to deal with to market?

### Describe the solution you'd like.

to solve the issue to would like to provide the stock data analysis using Deep Learning Algorithms-neural networks with fine tuning and advanced optimization methods which will help people's or business man to run thier businees smoothly .

### Describe alternatives you've considered.

No thanks

### Add any other context or screenshots about the feature request here.

Thank you

**Comment by ranamanish674zu** [comment]
Can you assign it to me? @Kushal997-das 

Full name: Manish Rana
GitHub profile link: https://github.com/ranamanish674zu
Email ID: [manish.rana2021@vitbhopal.ac.in](mailto:manish.rana2021@vitbhopal.ac.in)
Approach for this project: Will use Deep Learning algorithm and python
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it
Thanks.

**Comment by Kushal997-das** [comment]
Hi @ranamanish674zu,

It appears that you have created multiple issues simultaneously, which suggests you may not have read the contribution.md file thoroughly. The guidelines clearly state that only one issue should be created at a time. Additionally, submitting the same pull request to multiple repositories is considered spam. As a result, I am closing all your issues immediately.

You can refer to the following for more details:

[Proof1](https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/pull/377)
[Proof2](https://github.com/Recode-Hive/machine-learning-repos/pull/379)

**Comment by ranamanish674zu** [comment]
> Hi @ranamanish674zu,
> 
> It appears that you have created multiple issues simultaneously, which suggests you may not have read the contribution.md file thoroughly. The guidelines clearly state that only one issue should be created at a time. Additionally, submitting the same pull request to multiple repositories is considered spam. As a result, I am closing all your issues immediately.
> 
> You can refer to the following for more details:
> 
> [Proof1](https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/pull/377) [Proof2](https://github.com/Recode-Hive/machine-learning-repos/pull/379)

@Kushal997-das  Ohky Thanks you so much , i will take care of it next time
