### ISSUE TITLE
Title:  ROC Curve

### ISSUE THREAD

**Issue by ranamanish674zu** [Kushal997-das/Project-Guidance#1250]
### Is your feature request related to a problem? Please describe.

Used to visualize the performance of a binary classifier.

### Describe the solution you'd like.

i would like to provide the some mathematical concept of ROC curve (Used to visualize the performance of a binary classifier.) and some coding how to make it 

### Describe alternatives you've considered.

No thanks 

### Add any other context or screenshots about the feature request here.

thanks

**Comment by ranamanish674zu** [comment]
i want to work on this issue

**Comment by aikansh008** [comment]
please assign this issue to me
