### ISSUE TITLE
Title:  flight fare 

### ISSUE THREAD

**Issue by Pranshu-jais** [Kushal997-das/Project-Guidance#1261]
### Is your feature request related to a problem? Please describe.

 It involves understanding the factors that influence ticket prices and creating a model to estimate them accurately.

### Describe the solution you'd like.

Approach : preprocessing dataset ,performing EDA and building model using using ml algorithm like RandomForestRegressor,XG boost etc trained on relevant features and deploying the model using flask web app.

### Describe alternatives you've considered.

Please assign this project to me as part of GSSoC'24 with the gssoc label and the appropriate level (1/2/3)
Expectation level : 3

**Comment by aikansh008** [comment]
please assign this issue to me
