### ISSUE TITLE
Title:  Adding hovering effect to Domain name cards

### ISSUE THREAD

**Issue by GAVINESHWAR** [Kushal997-das/Project-Guidance#1274]
### Is your feature request related to a problem? Please describe.

In the website There is no hovering effect to the domain name cards

### Describe the solution you'd like.

In the website adding the hovering makes better user interface to the cards.

### Describe alternatives you've considered.

Adding hovering effects , bores and border shadow make the cards colorful and better interface.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/124431955/20bb7155-9995-4bd8-ad3b-1b134eec372d)
 
No hovering effects 
![image](https://github.com/Kushal997-das/Project-Guidance/assets/124431955/980f3f92-9c96-4383-8e3e-3f11860e8a4b)

Adding these kind of effects.

@Kushal997-das assign me this issue to make contribution to the project.

Thank you

**Comment by Kushal997-das** [comment]
@GAVINESHWAR 

Please consider addressing one issue at a time. Try to add this feature to the last issue instead of opening multiple issues. This will help keep everything consolidated. Thank you!

**Comment by GAVINESHWAR** [comment]
> @GAVINESHWAR
> 
> Please consider addressing one issue at a time. Try to add this feature to the last issue instead of opening multiple issues. This will help keep everything consolidated. Thank you!
> 
> #1273

@Kushal997-das , Ok can I add this issue once again for assigning me after completing previous issue .
