### ISSUE TITLE
Title: Build and deploy a Machine Learning model to predict the cancer.

### ISSUE THREAD

**Issue by sarayusreeyadavpadala** [Kushal997-das/Project-Guidance#1280]
@Kushal997-das I would like to contribute to this repository by adding a machine learning model that can predict cancer. I can build a model by 
-> loading and preprocessing the cancer dataset using pandas.
-> normalize the data and splitting the data into train and test.
-> build a regularized logistic regression model using scikit learn.
-> train and test the model. Finding accuracy.
-> deploy it in a web app using streamlit or gradio.

Please assign me this issue and label it with gssoc and level (1/2/3).

**Comment by Kushal997-das** [comment]
@sarayusreeyadavpadala 

Go ahead, but please ensure that the same project does not already exist in this PR. Otherwise, we will not add it again.

**Comment by sarayusreeyadavpadala** [comment]
@Kushal997-das could you please add the level 2 label to this issue?
