### ISSUE TITLE
Title: Adding a Login/Signup Page

### ISSUE THREAD

**Issue by Ojas-Arora** [Kushal997-das/Project-Guidance#1282]
### Is your feature request related to a problem? Please describe.

@Kushal997-das I want to add a login/signup page to website. kindly assign this issue to me.

### Describe the solution you'd like.

I will add a button for the same in navbar.

### Describe alternatives you've considered.

NA

**Comment by Kushal997-das** [comment]
@Ojas-Arora I don't think there's a need for login, sign-in, and sign-up functionality since maintaining a local database would be required. If you have a better plan, please feel free to suggest it.

**Comment by Ojas-Arora** [comment]
@Kushal997-das Can I add a chatbot to website?

**Comment by Kushal997-das** [comment]
Can

**Comment by aikansh008** [comment]
please assign this task to me
