### ISSUE TITLE
Title: domain name page 

### ISSUE THREAD

**Issue by siddhant-2002** [Kushal997-das/Project-Guidance#1287]
### Is your feature request related to a problem? Please describe.

whenever we click on domain names basic intermediate advanced we will direct go to the git repository I think we should create there new page for that 

### Describe the solution you'd like.

that new page includes cards containing single folder / project and some insight 

### Describe alternatives you've considered.

and after that when we go on that card we should able to see description of the project and then link to repository 

### Add any other context or screenshots about the feature request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/112260375/42ddf0ee-a6a3-4939-b15e-ec6b1d49b175)

**Comment by siddhant-2002** [comment]
hey i have created differrent pages for different level and added it

**Comment by aikansh008** [comment]
please assign this issue to me
