### ISSUE TITLE
Title: enhance footer design

### ISSUE THREAD

**Issue by siddhant-2002** [Kushal997-das/Project-Guidance#1288]
### Is your feature request related to a problem? Please describe.

footer is very simple

### Describe the solution you'd like.

i want to make it look good and stylish

### Describe alternatives you've considered.

add links of social media and company name copyright etc.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/112260375/2353e393-c268-47d0-8627-cf643d362be6)

**Comment by Phoenix-Illusion** [comment]
Is your feature request related to a problem? Please describe:

The current footer design of the website is very simple and lacks visual appeal.

Describe the solution you'd like:

I would like to enhance the footer to make it more visually appealing and stylish. This includes:

Adding links to social media profiles.
Incorporating the company name and copyright information.
Using improved styling and design elements to give the footer a modern look.
A link to the sitemap for easy navigation of the website's structure.

Describe alternatives you've considered:

Adding only the social media links.
Keeping the current design but adding a few more links.

@Kushal997-das plz assign this to me under GSSOC'24.

**Comment by Kushal997-das** [comment]
@siddhant-2002, please add this to issue #1287. There's no need to open a separate issue; just merge it there.
