### ISSUE TITLE
Title: Adding mail contact option in footer

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [Kushal997-das/Project-Guidance#1289]
### Is your feature request related to a problem? Please describe.

When people need contact support but can't find the email address easily on the website, it will be frustrating. This makes it difficult to get timely assistance and affects user experience.

### Describe the solution you'd like.

I would like a mail contact option to be added to the website footer. This should include a visible email address or a "Contact Us" link that opens the user's default email client with a pre-filled support email address. This makes it easy for users to reach out for help anytime.

### Describe alternatives you've considered.

An alternative solution is to have a contact form on the website. However, a single click to send an email directly is more convenient than filling out a form, providing a quicker and more user-friendly way to get support.

**Comment by Ayesha-Siddiqua88** [comment]
@Kushal997-das , please assign this to me under GSSoC'24

**Comment by Kushal997-das** [comment]
Hello, @Ayesha-Siddiqua88. While adding an email can help users reach out to us, I believe integrating a dynamic and flexible contact form would be more effective. It should also be visually appealing. If you agree with this approach, feel free to contact me on LinkedIn for a quicker response.
