### ISSUE TITLE
Title: National Poll on Healthy Aging (NPHA)

### ISSUE THREAD

**Issue by AmrutaJayanti** [Kushal997-das/Project-Guidance#1309]
### Is your feature request related to a problem? Please describe.

Predicting the number of doctors a survey respondent sees in a year.

### Describe the solution you'd like.

Predicting the number of doctors a survey respondent sees in a year using the subset of NPHA dataset

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

N/A

**Comment by AmrutaJayanti** [comment]
@Kushal997-das Please assign me this task . I would like to add this in `Machine Learning and Data Science` directory

**Comment by Kushal997-das** [comment]
@AmrutaJayanti Check the PIN issue .

**Comment by AmrutaJayanti** [comment]
@Kushal997-das Sorry for the inconvenience.
