### ISSUE TITLE
DropDown should close automatically on choosing any option on it

### ISSUE THREAD

**Issue by Utsavladia** [Kushal997-das/Project-Guidance#1318]
### Is your feature request related to a problem? Please describe.

It should close itself

### Describe the solution you'd like.

![image](https://github.com/user-attachments/assets/93ef80ba-2b32-428a-99cb-2243585f8aa7)

I will fix it

### Describe alternatives you've considered.

Make the dropdown close on choosing any option

**Comment by Kushal997-das** [comment]
@Utsavladia Please add all of this to the same issue; there's no need to create a new one. Refer to issue #1317 and address everything together.
