### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by anusha7530** [Kushal997-das/Project-Guidance#1337]
### Explain what you want to add/change in documentation.

Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference - 
- Contributing: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Contributing.md
- Learn: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Learn.md
- PROPOSAL: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/PROPOSAL.md

**Comment by yashksaini-coder** [comment]
can this issue be assigned to me as part of Wob'24 @anusha7530 @Kushal997-das
