### ISSUE TITLE
Add Topics 

### ISSUE THREAD

**Issue by anusha7530** [Kushal997-das/Project-Guidance#1338]
### Explain what you want to add/change in documentation.

In WoB, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository!
I would recommend adding the name of the company like the software you use to build like "vs-code, ghdesktop" to improve your discoverability.

If you are happy with the topics you have, feel free to close this issue.

**Comment by Kushal997-das** [comment]
Hi @anusha7530,

I noticed that several issues you submitted are not relevant to this repository and some are already covered. To keep things organized, I’ll be closing those issues. If you have any other questions or topics to discuss, feel free to reach out!

Thanks for your understanding!
