### ISSUE TITLE
Font Size in "More options (three lines) menu" is Too Small

### ISSUE THREAD

**Issue by Vishwajeet594** [Kushal997-das/Project-Guidance#1339]
### What happened?
The font size in the **"More Options" (three dots) menu is too small**, making it difficult for users to read the text.

### What did you expect to happen?
I expected the font size in the "More Options" menu to be larger and consistent with other sections of the website, ensuring better readability.

### Tell us what you see!
When navigating to the "More Options" menu, the text appears significantly smaller than in other parts of the site. This makes it hard to read, particularly for users with visual impairments or on smaller screens.

### Screenshot:
![Screenshot 2024-09-28 092705](https://github.com/user-attachments/assets/960df41f-c2f4-4962-aaf9-df567032fe7f)

### How can we reproduce this bug?

1. Open the website in a browser.
2. Locate and click on the "More Options" (three dots) menu.
3. Observe the font size of the text within this menu.

### Urgency (Optional)

Medium priority

**Comment by Vishwajeet594** [comment]
Please assign it to me

**Comment by Raj-Varu-Open-Source** [comment]
I cannot do pull request, Please add me. Thanks

**Comment by Raj-varu** [comment]
I cannot send pull request, Please add me. Thanks

**Comment by SakiraAli1115** [comment]
Hey I am the mentor of this project
@Vishwajeet594 Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue.
