### ISSUE TITLE
Title: Having some cheatsheet to learn commads

### ISSUE THREAD

**Issue by VivekShahare04** [Kushal997-das/Project-Guidance#1344]
### Explain what you want to add/change in documentation.

I have some sheets for command which will help to learner to learn new commands...let me know as it will help a learner ro learn new commands and if you want i will directly attach it into readme file....let me know.. @kus

**Comment by alo7lika** [comment]
Assign me this work,  I would love to contribute and add labels gssoc and hacktoberfest.

**Comment by Kushal997-das** [comment]
> Assign me this work, I would love to contribute and add labels gssoc and hacktoberfest
