### ISSUE TITLE
Title: Adding a email spam detection project under machine learning (basic) projects

### ISSUE THREAD

**Issue by ShrishtiSingh26** [Kushal997-das/Project-Guidance#1345]
### Is your feature request related to a problem? Please describe.

it would be really helpful to add this project as well. It is a beginner friendly project which helps in understanding logistic regression better.

### Describe the solution you'd like.

I would like to add email spam detection model using logistic regression, under the machine learning basic projects

### Describe alternatives you've considered.

We can add spam email or sms detection and use other models as well to train it like svm or navies bayes

**Comment by ShrishtiSingh26** [comment]
i would like to work on this issue so please assign it to me

**Comment by Rashmi885** [comment]
I would like to contribute to this project.
