### ISSUE TITLE
Title: Enhancement to a subsection inorder to improve visibility.

### ISSUE THREAD

**Issue by Jay-1409** [Kushal997-das/Project-Guidance#1346]
### Is your proposal related to a problem? Please describe.

Looking forward to contribute towards this amazing repo, here is what I would like to change:
**Before**
<img width="956" alt="image" src="https://github.com/user-attachments/assets/2c089904-b728-4203-9c15-9d4009aabcab">
 **After** 
<img width="957" alt="image" src="https://github.com/user-attachments/assets/7f4b7af0-2cad-4d18-aa9d-3a68dad6f5d4">

Please Assign this to me under Gssoc 2024 extd or hacktoberfest 2024

**Comment by Kushal997-das** [comment]
@Jay-1409 I don’t think this is a priority at the moment, but thank you for bringing it to my attention. Please feel free to open new issues in the future!
