### ISSUE TITLE
Add 'Deep Learning' Folder with a project on 'Neural Network from Scratch for Regression and Classification Tasks'

### ISSUE THREAD

**Issue by rishikaa1** [Kushal997-das/Project-Guidance#1347]
I would like to propose the addition of a new folder called "Deep Learning" in the repository. This folder will focus on projects related to deep learning, and I would like to contribute a project where we build a neural network from scratch for both regression and classification tasks using only NumPy.

This project will:

- Build a neural network from scratch without using any deep learning frameworks.
- Demonstrate how the neural network can be used for regression and classification tasks.
- Include detailed documentation and comments for easier understanding, especially for beginners.

Reason for Proposal:

This project will enhance the repository by providing an advanced-level deep learning project suitable for learners who want to dive deep into the mechanics of neural networks. It would align well with the repository's goal of offering beginner to advanced projects in various programming languages.

Please consider my proposal and assign me this task.

**Comment by Kushal997-das** [comment]
@rishikaa1 I don't think it's really important now thank you so much for open issue feel free to  open new issue again.
