### ISSUE TITLE
Adding Object detection using YOLO in Intermediate ML

### ISSUE THREAD

**Issue by ramana2074** [Kushal997-das/Project-Guidance#1349]
The Object detection using YOLO uses an Pretrained model which can be used to detect and classify the objects in an image.
I can work on this, please assign me to this ?

**Comment by Kushal997-das** [comment]
@ramana2074 Could you please give a detailed explanation of what you want to add? It would also help to include images of the expected output. Please be specific about everything you want to include.

**Comment by ramana2074** [comment]
could please add the labels gssoc ext , hacktober and level
