### ISSUE TITLE
Enhance the data analytics of -> Machine Learning and Data Science/Basic/Diabetes Prediction/Diabetes.ipynb

### ISSUE THREAD

**Issue by kottarivaibhav** [Kushal997-das/Project-Guidance#1351]
Hello @Kushal997-das 
### Is your feature request related to a problem? Please describe.

I would Like to add various methods like comparison with various ML models 

### Describe the solution you'd like.

I would like to test and train and come up with better solution . I would also like to use lot of plots for better data visualization.

### Describe alternatives you've considered.

This will be useful as it will give better understanding of the data.

**Comment by Kushal997-das** [comment]
@kottarivaibhav At a time one issue .
