### ISSUE TITLE
Title: The Footer in Very Normal 

### ISSUE THREAD

**Issue by mr-kunal-07** [Kushal997-das/Project-Guidance#1353]
### Is your proposal related to a problem? Please describe.
Hello @Adhetya 
make angeging footer for more better ui

please assign me to improve this

**Comment by aimanrazia** [comment]
add in footer more dynamic features like animation ,hover to it

**Comment by mr-kunal-07** [comment]
Ok thank you 😊

**Comment by Kushal997-das** [comment]
@mr-kunal-07, things aren't clear, and tagging someone else seems inappropriate.
