### ISSUE TITLE
The months and days may occur negative.

### ISSUE THREAD

**Issue by KashishJuneja101003** [Kushal997-das/Project-Guidance#1358]
### What happened?

While calculating the age, the months and days may be negative.
For example: DOB is 10/10/2003 and today's date is 03/10/2003, the days are negative.
![image](https://github.com/user-attachments/assets/f8caf471-1909-478d-bb0a-bac1a69af7d8)

### How can we reproduce this bug?

The age must be positive. Saying 21 years, 1 month, -7 days is not right. If the result is negative, it should not be printed.
Like the result should be, "21 years and 1 month" only.

### Urgency (Optional)

None

**Comment by KashishJuneja101003** [comment]
Please assign this issue to me.

**Comment by KashishJuneja101003** [comment]
Hi, thanks for the response! My contributions were not part of any specific event; I raised this issue while working independently on the project.

Could you please assign this issue to me and add the labels: "gssoc-extd "and "hacktoberfest"? Also, could you specify the level of this issue?

If you need any further information, please let me know.

Thanks!

**Comment by KashishJuneja101003** [comment]
I apologise for the oversight. Actually, the issue with the code was if DoB is 10/10/2003 and today's date is "03/10/2024", then the number of days in the age were "-7".
I mistakenly wrote the 2003 as current date in the issue section.
You may check the screen shot posted in the issue for a better understanding of my issue.

Thank You for being patient with me throughout the process.

I'll make sure not to repeat these mistakes.

Thank you!

**Comment by Kushal997-das** [comment]
@KashishJuneja101003 Ok, will check

**Comment by KashishJuneja101003** [comment]
@Kushal997-das Do I need to raise the pull request once more?
Since in my dashboard, it is still invalid.

**Comment by Kushal997-das** [comment]
> 03/10/2024


Could you check if you are receiving any instances where the number of days is negative? It seems to be working perfectly fine for me. 
![check na](https://github.com/user-attachments/assets/7b87ebe1-6ed3-40c0-8bb5-b501e274b040)

**Comment by KashishJuneja101003** [comment]
10/10/2003 is valid now because 10/10/2024 has already passed.

It will show negative months and years if you try with any future date with year < 2024.

For example, 

![image](https://github.com/user-attachments/assets/11cf43b0-ac82-4ccb-8345-a07b1fb6e8e2)
![image](https://github.com/user-attachments/assets/3a9329aa-fa46-4c04-8d54-bd5c503c82f3)


I posted the issue on 03/10/2024. Thus the output was negative that day. After 10/10/2024 arrived, it became valid.

I hope this comment clears up any misunderstanding.

Thank You!

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue!!
