### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by UG-SEP** [Kushal997-das/Project-Guidance#136]
Hey Guys Please update the readme of desktop application folder

**Comment by TawfikYasser** [comment]
Hi @UG-SEP , I suggest for you to update it :)

**Comment by Kushal997-das** [comment]
> Hey Guys Please update the readme of desktop application folder

You can do this @UG-SEP

**Comment by UG-SEP** [comment]
@Kushal997-das  I can do it but not know because my exams are started so i need to focus on that

**Comment by UG-SEP** [comment]
closing issue because it have been solved
