### ISSUE TITLE
Title: Replace Checkboxes with Animated 3D vector tickmark image in "Steps to Contribute" Section

### ISSUE THREAD

**Issue by Rashipotey** [Kushal997-das/Project-Guidance#1360]
### Is your proposal related to a problem? Please describe.

I hope this message finds you well! I wanted to suggest an enhancement for the "Steps to Contribute" section of the project. Currently, the first checkbox remains unchecked when the site is first loaded. This might confuse users about whether they need to interact with it or not, potentially impacting their experience. To enhance user engagement and clarify the contribution process, I propose replacing the checkboxes with powerful animated 3D images.  
Kindly assign me this issue.

### Add any other context or screenshots about the proposal request here.

![Screenshot 2024-10-03 213447](https://github.com/user-attachments/assets/916cef72-8f92-41d0-8a56-2cbffbb0d676)

**Comment by Kushal997-das** [comment]
@Rashipotey Things aren't clear, and tagging someone else seems inappropriate. Please remove the tagged person and include some screenshots of what your output will look like. Also, please mention your contributions under this.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Rashipotey 
Please update me because it's two week ,otherwise I will close this issue!!!
