### ISSUE TITLE
currency converter,rock paper scissor and algorithm visualizer

### ISSUE THREAD

**Issue by bhavanamn** [Kushal997-das/Project-Guidance#1362]
I would like to add some basic javascript projects (like currency converter ,rock paper scissors) and also algorithm visualizer which was build using React js to web development folder.Please assign this issue to me.
Please assign this issue to me

**Comment by SakiraAli1115** [comment]
Hey I am the mentor of this project 
@bhavanamn  Hello Thank you for opening the pull issue and you can opening new issue by creating  the new concept those are not  exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
