### ISSUE TITLE
Title: Add hackathon tracker

### ISSUE THREAD

**Issue by ananyag309** [Kushal997-das/Project-Guidance#1364]
### Is your feature request related to a problem? Please describe.

willing to add hackathon tracker under web dev projects

### Describe the solution you'd like.

working video
https://github.com/user-attachments/assets/d53dc8f9-2b76-4b4a-95df-06604411c1a4

### Describe alternatives you've considered.

n/a

**Comment by ananyag309** [comment]
gssoc extd

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue to @ananyag309
