### ISSUE TITLE
Title: Improving UI of the cards

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Kushal997-das/Project-Guidance#1365]
### Is your feature request related to a problem? Please describe.

it doesnt match the level of landing page.So i would love to try and make it better

### Describe the solution you'd like.

<img width="1300" alt="Screenshot 2024-10-04 at 7 30 48 PM" src="https://github.com/user-attachments/assets/8463c5b1-a407-4d18-a8b8-0362f2ca82d2">
the project is really good , i feel this section needs a little more improvement.

### Describe alternatives you've considered.

Make the UI better

**Comment by SakiraAli1115** [comment]
Hello @T-Rahul-prabhu-38  
Please update me because it's one week ,otherwise I will close this issue!!!

**Comment by T-Rahul-prabhu-38** [comment]
@SakiraAli1115 im so sorry i lost this issue i raised. can i still work on it please.ill create a PR by tonight.

**Comment by T-Rahul-prabhu-38** [comment]
oh i actually didnt start working on this because i wasnt assigned it . please assign me and ill quickly work on it.

**Comment by Kushal997-das** [comment]
> I am the mentor of this project Hello @T-Rahul-prabhu-38 Can you please describe little bit how the output will look like after update and give screenshots.!!

Hello @T-Rahul-prabhu-38,

Mentor @SakiraAli1115 is inquiring about something. If you’re not serious about addressing it, this issue will be closed by the end of the day today. @SakiraAli1115, please go ahead and close it if he does not respond by then.

**Comment by T-Rahul-prabhu-38** [comment]
I did clearly mention since I'm not assigned this task yet I have not started working on it.
Please assign me this issue so I can work on it.

**Comment by T-Rahul-prabhu-38** [comment]
We are only allowed to work untill the issue is assigned right , I'm just following the rules

**Comment by Kushal997-das** [comment]
> I am the mentor of this project Hello @T-Rahul-prabhu-38 Can you please describe little bit how the output will look like after update and give screenshots.!!

@T-Rahul-prabhu-38, please refrain from spamming. She asked you a question, so focus on providing the information requested without making unnecessary comments.

**Comment by T-Rahul-prabhu-38** [comment]
It was a pleasure working on truism repo
