### ISSUE TITLE
Title: Addition of a few basic codes like: contact book, note making app, to-do list

### ISSUE THREAD

**Issue by Chin-may02** [Kushal997-das/Project-Guidance#1366]
### Is your proposal related to a problem? Please describe.

Although the repository is very vast it can be updated with a few basic programs in python. I would like to contribute to this issue.
Would you please add the gssoc-ext and hacktoberfest-accepted tags so that I can immediately work on it. 

### Add any other context or screenshots about the proposal request here.

N/A

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Chin-may02 
Can you please describe little bit how the output will look like after update and give screenshots.!!

**Comment by Chin-may02** [comment]
Hello, Here you go 
1. Contact Book
![image](https://github.com/user-attachments/assets/8b86893c-edb4-4465-9b96-ac4e1bef08af)
2. Note making- yet to code 
3. To do list
![image](https://github.com/user-attachments/assets/ca7990b1-3e1c-46c5-84d8-8902e2f0cf0e)

**Comment by Chin-may02** [comment]
@SakiraAli1115 There are more projects that I will be adding along with the ones I have mentioned above with a readme for the beginners to better understand python. 
Do assign me this task along with the tags gssoc-ext, hacktoberfest and hacktoberfest-accepted along with the level that seems fit.

**Comment by SakiraAli1115** [comment]
Hello @Chin-may02
It is a Program not any application. Please read our project and understand, and thank you for your contribution ,make another pull issue by creating new concepts those are not exist in the project!!!
@Kushal997-das Kindly close this issue since it already exist in our project.
