### ISSUE TITLE
Title: Addition of a few simple python codes

### ISSUE THREAD

**Issue by djv554** [Kushal997-das/Project-Guidance#1367]
### Is your proposal related to a problem? Please describe.

Addition of few simple basic level python codes like
1) rock-paper-scissors game 
2) password generator 
3) number guessing game
I'd love to work on this.
Please assign this task to me with the labels of gssoc-ext and hacktoberfest-accepted.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @djv554 
Can you please describe little bit how the output will look like after update and give screenshots.!!

**Comment by SakiraAli1115** [comment]
Hello @djv554 
It is a Program not any application. Please read our project and understand, and thank you for your contribution ,make another pull issue by creating new concepts those are not exist in the project!!!
@Kushal997-das Kindly close this issue !!
