### ISSUE TITLE
Blinkit Clone | Web Development Project

### ISSUE THREAD

**Issue by neyhere07** [Kushal997-das/Project-Guidance#1368]
### Add any other context or screenshots about the proposal request here.

https://github.com/user-attachments/assets/6bd88749-7c97-4cf4-bed8-84cdb52c691c

<hr><br>I have made this simple Blinkit Login page. Tech Stack used here are: <strong>HTML</strong> and <strong>CSS</strong>.<br><br>  @Kushal997-das I would like to contribute to this repository in <strong>Web Development</strong> Folder under <strong>GSSOC-2024-extd</strong> and <strong>Hacktoberfest-2024</strong>. Kindly assign me this issue. Thank you!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @neyhere07 
I appreciate your idea and thank you for contribute to this project !!!
@Kushal997-das kindly assign this issue!!!
