### ISSUE TITLE
[Project]: Add Virtual-Whiteboard to basic web development domain

### ISSUE THREAD

**Issue by tobySolutions** [Kushal997-das/Project-Guidance#1376]
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

This issue was created to add the virtual whiteboard project to the basic track of the web development projects. Below is a screenshot of what the Virtual Whiteboard looks like:

<img width="1512" alt="Screenshot 2024-10-05 at 08 27 08" src="https://github.com/user-attachments/assets/003358fe-ab41-4693-84ed-089d0127b5d2">

### 🔍 Priority Level
- [ ] High
- [x] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [ ] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### 💬 Next Steps:

You can expect a response within [3 days].

Feel free to check back or provide more details if needed!

**Comment by tobySolutions** [comment]
Can this issue be assigned to me, please?

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @tobySolutions 
Can you please describe little bit more !!!!
