### ISSUE TITLE
Project: Drawing Tool made with HTML canva

### ISSUE THREAD

**Issue by chibuike-19** [Kushal997-das/Project-Guidance#1377]
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

A simple drawing tool that also has shapes and color range picker. Work on the tool can be downloaded as an image whenever needed. A screenshot of the website preview is shared below:
![Screenshot 2024-10-05 083927](https://github.com/user-attachments/assets/11d48aa0-8159-4e35-83d2-83c7a2f0b968)

### 🔍 Priority Level
- [ ] High
- [x] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [ ] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### 💬 Next Steps:

You can expect a response within [2 days].

Feel free to check back or provide more details if needed!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @chibuike-19 
Can you please add some more features!!!!

**Comment by Kushal997-das** [comment]
@SakiraAli1115 Assigning him as he already mentioned.

**Comment by SakiraAli1115** [comment]
@Kushal997-das  Kindly assign this issue!!!!

**Comment by chibuike-19** [comment]
Okay, should I still go ahead to add my project?
