### ISSUE TITLE
Title: Projects featuring page

### ISSUE THREAD

**Issue by Bhum-ika** [Kushal997-das/Project-Guidance#1378]
### Is your feature request related to a problem? Please describe.

When a user clicks on Basic, Intermediate or Advanced , it opens up to a github repo listing all those projects.

### Describe the solution you'd like.

I would like to add a page where those products will be listed along with their images and short description and when clicked , will take them to that specific code repo.

### Describe alternatives you've considered.

Nothing

### Add any other context or screenshots about the feature request here.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by Bhum-ika** [comment]
Okay, I will make a demo page for you to show and send by tonighr

**Comment by Bhum-ika** [comment]
@SakiraAli1115 
![image](https://github.com/user-attachments/assets/4f9d60c4-1325-4b18-8d13-6bdad8b9a487)

This is a demo output to show you, there will be an eye iconf or users to go on code and image of every project along with little description and this page will be for every category

**Comment by raj-adi00** [comment]
Is this issue open. I can work on it

**Comment by Bhum-ika** [comment]
@raj-adi00 yes, you can

**Comment by raj-adi00** [comment]
@Kushal997-das Please assign it to me.
