### ISSUE TITLE
Title: Adding a game using html, css, js - Smash Monty Mole

### ISSUE THREAD

**Issue by rugved0102** [Kushal997-das/Project-Guidance#1379]
### Is your feature request related to a problem? Please describe.

This game is for entertainment.

### Describe the solution you'd like.

The game involves clicking on randomly appearing moles to score points while avoiding randomly appearing piranha plants, as clicking on a plant ends the game. Moles and plants appear at random intervals on a 3x3 grid, and the score updates dynamically based on player actions.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/855386c3-9c24-4069-866f-638ba7741779)

**Comment by rugved0102** [comment]
@Kushal997-das can you please assign me the issue ?

**Comment by SakiraAli1115** [comment]
@rugved0102  Tell me where you can contribute?

**Comment by rugved0102** [comment]
@SakiraAli1115 I can add this project in the basic folder of your Web dev project. It is a simple game using html, css and javascript.

**Comment by SakiraAli1115** [comment]
Like under GSSoC'24 Extended Edition and Hacktoberfest?

**Comment by rugved0102** [comment]
@SakiraAli1115  in both GSSoC'24 ext and hacktoberfest.
