### ISSUE TITLE
Improve Design of '404: Page Not Found' Error Page"

### ISSUE THREAD

**Issue by venurockss** [Kushal997-das/Project-Guidance#1380]
I noticed that when a user navigates to a random or non-existent URL, the "404: Page Not Found" page is not properly designed or visually appealing. The current layout could be enhanced to provide a better user experience. I've attached a screenshot for reference. I would be happy to work on redesigning this page if you could assign this issue to me.
![Screenshot 2024-10-06 172923](https://github.com/user-attachments/assets/0df962a4-8b16-4103-ad7b-ca4bbd3a2914)

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @venurockss 
Can you please describe little bit how the output will look like after update and give screenshots.!!

**Comment by G-Rajashekar** [comment]
@SakiraAli1115 Hello PA, Can you assign this issue to me .
The sample output is:
![Uploading Screenshot (444).png…]()

**Comment by SakiraAli1115** [comment]
@G-Rajashekar Tell me where you can contribute ?

**Comment by SakiraAli1115** [comment]
@G-Rajashekar Hello 
Can you please update me within 24 hours , otherwise will close this issue!!!

**Comment by IshaniSaikia** [comment]
@SakiraAli1115  Ma'am, if no one has solved this issue yet, can I work on it

**Comment by Kushal997-das** [comment]
@IshaniSaikia Go ahead.

**Comment by sushil-sagar05** [comment]
hey @Kushal997-das @SakiraAli1115  can you assign me on this issue i will design the custom error page for this website
eg: 
![gssoc3](https://github.com/user-attachments/assets/45a6146b-4614-4844-9f86-d5535caef6d6)

**Comment by Kushal997-das** [comment]
@sushil-sagar05 Okay, please proceed. Make sure everything looks good. We'll review the PR carefully, and if it meets our standards, we'll move forward; if not, we'll address any issues.
