### ISSUE TITLE
Title: Add GroqDev LLM application

### ISSUE THREAD

**Issue by yashksaini-coder** [Kushal997-das/Project-Guidance#1381]
### Is your feature request related to a problem? Please describe.

Add a LLM bot project in the Artificial Intelligence category, which is a chatbot for coding purposes.

### Describe the solution you'd like.

Develop a new LLM bot that uses API key to chat & invoke LLM call functions to create & generate reponses tailored to user's prompt

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

**Comment by yashksaini-coder** [comment]
@Kushal997-das can you assign this issue to me & add labels to it

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @yashksaini-coder 
Can you please describe little bit how the output will look like after update and give screenshots.!!

**Comment by yashksaini-coder** [comment]
It is a web application built using flask. That uses API keys and different models to choose from. Can be counted in data science or Gen AI category @Kushal997-das @SakiraAli1115

**Comment by Kushal997-das** [comment]
@yashksaini-coder, could you please attach some screenshots as @SakiraAli1115 mentioned? Also, be sure to specify which event you’d like to contribute to.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder, could you please attach some screenshots as @SakiraAli1115 mentioned? Also, be sure to specify which event you’d like to contribute to.

sure here's a demo of my web application I created,

[GroqDev implementation.webm](https://github.com/user-attachments/assets/bfcb1e8a-5494-45be-bc9a-cf944f556deb)

It is based on Flask and using Groq API keys or Gemini keys we can use different models. It was originally developed as a chat-bot component for my flask based Chat application. The UI i am planning to change by using a little ReactJS

**Comment by SakiraAli1115** [comment]
@yashksaini-coder Tell me where you can contribute ?
@Kushal997-das kindly assign this issue!!!!

**Comment by yashksaini-coder** [comment]
@SakiraAli1115 I have few other ideas with documentation on using ai resources to build static or dynamic web apps using flask or streamlit.

I want to add them to so can I contribute to this repo.

Starting with this simple GroqDev AI coding bot. So assign me this issue

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder Tell me where you can contribute ? @Kushal997-das kindly assign this issue!!!!

This type of project can be categorized in Artificial Intelligence

**Comment by yashksaini-coder** [comment]
@SakiraAli1115 @Kushal997-das can this issue assign to me with proper labels

**Comment by SakiraAli1115** [comment]
> @SakiraAli1115 I have few other ideas with documentation on using ai resources to build static or dynamic web apps using flask or streamlit.
> 
> I want to add them to so can I contribute to this repo.
> 
> Starting with this simple GroqDev AI coding bot. So assign me this issue

Can you give working video, screenshot !!
Then we will decide!!

**Comment by yashksaini-coder** [comment]
> > @SakiraAli1115 I have few other ideas with documentation on using ai resources to build static or dynamic web apps using flask or streamlit.
> > I want to add them to so can I contribute to this repo.
> > Starting with this simple GroqDev AI coding bot. So assign me this issue
> 
> Can you give working video, screenshot !! Then we will decide!!

[GroqDev implementation.webm](https://github.com/user-attachments/assets/d131b66a-8bbb-45d3-b452-fe32bac80bcc)

@SakiraAli1115

**Comment by yashksaini-coder** [comment]
So @SakiraAli1115 can you assign me this issue

**Comment by SakiraAli1115** [comment]
@Kushal997-das  kindly assign this issue!!!

**Comment by Kushal997-das** [comment]
@yashksaini-coder Please allow us some time to respond; there’s no need to rush. Let’s tackle one issue at a time, as I will be assigning them to you.

**Comment by yashksaini-coder** [comment]
okh @Kushal997-das

**Comment by SakiraAli1115** [comment]
@yashksaini-coder Tell me where you can contribute ?
like under GSSoC'24 Extended Edition and Hacktoberfest?

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder Tell me where you can contribute ? like under GSSoC'24 Extended Edition and Hacktoberfest2024?

GSSOC & hacktoberfest both if possible
