### ISSUE TITLE
Title: Add Real-Time Translation Model to the Machine Learning & Data Science Advanced Section

### ISSUE THREAD

**Issue by 770navyasharma** [Kushal997-das/Project-Guidance#1382]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Hi, I would like to contribute a Real-Time Translation Model to the Advanced section under the Machine Learning and Data Science folder. This model will be a real-time translation app built using Streamlit and will demonstrate advanced techniques for text translation.

### Describe the solution you'd like.

The app will support real-time translation between multiple languages.
It will be built using Streamlit for the front-end and pre-trained translation models from libraries of Google Translate, gtts for the backend.
This will provide users with an interactive web-based interface to input text and see live translations in the chosen target language.

### Add any other context or screenshots about the feature request here.

Labels Requested:
GSSoC (GirlScript Summer of Code)
Hacktoberfest
Enhancement
Machine Learning
Advanced
Level 2 or 3
This app will be an exciting addition to the advanced projects in the repository, showcasing how to build a practical machine learning solution using real-time translation capabilities. I am looking forward to contributing!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @770navyasharma 
It is already present ,how different is your pull issue ,Can you please describe me how the output will look like after update and give screenshots!!!

**Comment by Kushal997-das** [comment]
@770navyasharma Kindly reply.
