### ISSUE TITLE
Title: a frontend project of GitHub profile search engine 

### ISSUE THREAD

**Issue by adityalaxkar123** [Kushal997-das/Project-Guidance#1387]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

People can search the GitHub profile, see their following, followers and repos.

### Describe the solution you'd like.

Tech stack: frontend technology and GitHub api

**Comment by adityalaxkar123** [comment]
Me a GSSOC'24 extended member can you assign it to me

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @adityalaxkar123 
Can you please describe me little bit more and give screenshots!!!!!

**Comment by adityalaxkar123** [comment]
it is simply a frontend web development project in which people can search the github profiles, see their following,follower and repository.
![Screenshot (970)](https://github.com/user-attachments/assets/5230eaae-dd27-4301-bf33-aa18faaff21e)
@SakiraAli1115

**Comment by SakiraAli1115** [comment]
Ok 
@Kushal997-das kindly assign this issue!!!

**Comment by adityalaxkar123** [comment]
Can you give level to this issue @Kushal997-das
