### ISSUE TITLE
Title: Add Customer Churn Prediction Project in Machine learning 

### ISSUE THREAD

**Issue by SimranShaikh20** [Kushal997-das/Project-Guidance#1389]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your proposal related to a problem? Please describe.

@Kushal997-das 
Hi, I am Simran Shaikh. I’ve been reviewing the project as part of my contribution to GSSoC Extended 24 and noticed that Customer Churn Prediction one of the most important topic that show as why employee left there job . This project must be added in Machine Learning & Data Science Section in Intermediate level. 
I would like to work on this.
If you like my proposal , please assign the task to me and add the corresponding charts to it.By assign  Level 3 Label.
Thank you for your time and consideration!

### Add any other context or screenshots about the proposal request here.

I had saw so many times that most of people left there subscription  because of some reason they even we don't know why . 
But by using this prediction KNN model we are able to know and in a better way we can understand why they are living there jobs.I hope that you liked my idea !

**Comment by SimranShaikh20** [comment]
@Kushal997-das  do you liked my proposal ?

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @SimranShaikh20 
I appreciate your pull issue, Can you provide me screenshots!!!!

**Comment by SimranShaikh20** [comment]
@SakiraAli1115 
I had not create this project if you assign me work i will create it.

**Comment by Kushal997-das** [comment]
@SimranShaikh20 Hi , Kushal this side I’m assigning this issue to you kindly make sure while opening the PR add the relevant output screenshots. And yes level should be decided by us , let create the PR then we will add level . Thank you .

**Comment by SimranShaikh20** [comment]
@Kushal997-das 
okay i will make sure to upload all relevant content.

**Comment by SimranShaikh20** [comment]
@Kushal997-das 
![image](https://github.com/user-attachments/assets/5eb1a55b-0b5d-46a6-a0f3-ce0ff2458aaa)
there is issue while making PR request.

**Comment by SimranShaikh20** [comment]
hello @Kushal997-das  can you  pleased resolved the PR Error

**Comment by SakiraAli1115** [comment]
@SimranShaikh20  
Do sync with the origin project.

**Comment by SimranShaikh20** [comment]
@SakiraAli1115 
I had created PR check it and let me know is there any changes

**Comment by SimranShaikh20** [comment]
@SakiraAli1115 
I had make PR check it !

**Comment by SimranShaikh20** [comment]
> @SakiraAli1115 I had make PR check it !

and @Kushal997-das have checked ? 
let me

**Comment by SakiraAli1115** [comment]
> @SakiraAli1115 I had make PR check it !

@SimranShaikh20 yes

**Comment by SakiraAli1115** [comment]
@SimranShaikh20  Wait we will check anything  is needed or not in this PR

**Comment by SimranShaikh20** [comment]
> @SimranShaikh20 Wait we will check anything is needed or not in this PR !! Kindly open new issue which is not exist in this project.

??
