### ISSUE TITLE
Title: Enhancing Footer and Icons

### ISSUE THREAD

**Issue by devxMani** [Kushal997-das/Project-Guidance#1390]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Feature

### Describe the solution you'd like.

Updating footer and add designs and important links

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @devxMani 
I appreciate your pull issue , can you please describe little bit more and give screenshots!!!

**Comment by Kushal997-das** [comment]
Hello @devxMani ,

Mentor @SakiraAli1115 is inquiring about something. If you’re not serious about addressing it, this issue will be closed by the end of the day today. @SakiraAli1115, please go ahead and close it if he does not respond by then.

**Comment by SakiraAli1115** [comment]
> Hello @devxMani ,
> 
> Mentor @SakiraAli1115 is inquiring about something. If you’re not serious about addressing it, this issue will be closed by the end of the day today. @SakiraAli1115, please go ahead and close it if he does not respond by then.

okay!

**Comment by devxMani** [comment]
@SakiraAli1115 Yes firstly I'll enhance the footer by adding navigation links and icons of different navigations to create a separation between them 
![image](https://github.com/user-attachments/assets/55e2581c-e7c3-46a8-a84b-2a19f5ab1907)

**Comment by devxMani** [comment]
@SakiraAli1115 
![image](https://github.com/user-attachments/assets/ac54d58f-3feb-4bc2-af5b-82eed04571b3)
like this

**Comment by Kushal997-das** [comment]
@devxMani The Footer we have it's perfectly fine. Thank YOU
