### ISSUE TITLE
I wanna add tic tac toe game using html css and javascript for webdevelopment beginner projects 

### ISSUE THREAD

**Issue by rahul-chakradhari** [Kushal997-das/Project-Guidance#1392]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Additional Info

This is a simple Tic Tac Toe game built using HTML, CSS, and JavaScript. The game allows two players (O and X) to play against each other on a 3x3 grid. The game detects the winner or a draw, and provides a reset option to play again.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@rahul-chakradhari Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
