### ISSUE TITLE
[ML Project] Adding a Disease prediction based ML project in Intermediated level 

### ISSUE THREAD

**Issue by sanikaNB** [Kushal997-das/Project-Guidance#1393]
i would like to add the ML project in intermediate level of Diseases prediction where a user gives an inputs as symptoms and based on the symptoms its predicts the Diseases and gives its description , medications, diet and workout needed to be followed for the cure of the diseases.

@Kushal997-das please assign this to me to add the project.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@sanikaNB  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
