### ISSUE TITLE
Title: Add Netflix clone project in web development-intermediate 

### ISSUE THREAD

**Issue by hamzathul** [Kushal997-das/Project-Guidance#1394]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

improving web development skills at the intermediate level

### Describe the solution you'd like.

Adding The project to web development-intermediate

**Comment by hamzathul** [comment]
Can i add this?

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@hamzathul  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
