### ISSUE TITLE
Title: Refactoring code for better readability (constants, extracting methods) for tic-tac-toe app made using kotlin.

### ISSUE THREAD

**Issue by Gopal0Gupta** [Kushal997-das/Project-Guidance#1395]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your proposal related to a problem? Please describe.

just refactoring code for better readability'

**Comment by Gopal0Gupta** [comment]
@Kushal997-das please assign me this issue under hacktoberfest & gssoc-ext.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@Gopal0Gupta  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.

**Comment by Gopal0Gupta** [comment]
> I am the mentor of this project. Hello @Gopal0Gupta I appreciate your pull issue, can you provide screenshots?

Hello @SakiraAli1115 sorry for replying late 
here are few screenshots but ui is similar, i changed mainactivity code for better readability and easy to understand for beginers
hope you find my contribution good and @Kushal997-das will assign me this issue so that i can send pull request

![WhatsApp Image 2024-10-11 at 11 44 10_f67c84ca](https://github.com/user-attachments/assets/5ecf8955-ab51-4f7f-b761-75947079d7b5)
![WhatsApp Image 2024-10-11 at 11 44 10_12941ac1](https://github.com/user-attachments/assets/5773384c-d598-4d89-af1d-7c6caac8a2fc)
![WhatsApp Image 2024-10-11 at 11 44 11_a11b0cf4](https://github.com/user-attachments/assets/7e41fc8c-6433-4ae3-bf26-f391c79ccda1)

**Comment by Gopal0Gupta** [comment]
@Kushal997-das assign me this issue under gssoc-extd and hacktober fest
