### ISSUE TITLE
Title: Can we add C codes with DSA 

### ISSUE THREAD

**Issue by Mansi07sharma** [Kushal997-das/Project-Guidance#1397]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your proposal related to a problem? Please describe.

I want to add DSA with it. It also help users to learn DSA with other courses because it is also very important for future.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Mansi07sharma 
I appreciate you pull issue can you describe little bit more and give screenshots!!!!

**Comment by SakiraAli1115** [comment]
@Mansi07sharma Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
