### ISSUE TITLE
Title: adding full screen navbar

### ISSUE THREAD

**Issue by itznayan** [Kushal997-das/Project-Guidance#1398]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

adding full screen navbar

### Describe the solution you'd like.

adding full screen navbar

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @itznayan 
I appreciate your pull issue can you give screenshots!!!

**Comment by itznayan** [comment]
@SakiraAli1115
 https://github.com/user-attachments/assets/49fc4ee0-8c22-44cd-b689-7245fc8ec7ac

**Comment by SakiraAli1115** [comment]
@itznayan Tell me where you can contribute?
@Kushal997-das  Kindly assign this issue !!

**Comment by itznayan** [comment]
@Kushal997-das please provide appropriate level

**Comment by itznayan** [comment]
@SakiraAli1115 @Kushal997-das please provide appropriate level so that i can start working

**Comment by SakiraAli1115** [comment]
Don't you worry start working now we will assign that level which is perfect in your issue !!
@itznayan
