### ISSUE TITLE
Title: add buttons instead of hyperlinks

### ISSUE THREAD

**Issue by snehaapratap** [Kushal997-das/Project-Guidance#1399]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your proposal related to a problem? Please describe.

buttons can be added in those cards instead of hyperlinks.
buttons will enhance the ui.
please assign me this task.

### Add any other context or screenshots about the proposal request here.

![image](https://github.com/user-attachments/assets/ff7f2e5b-37f7-41ce-889e-b6e204d54b49)

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @snehaapratap 
I appreciate your pull issue can you give screenshots !!!

**Comment by snehaapratap** [comment]
i have added screenshots above .
as each card has basic , intermediate and advanced , i want to make the buttons to enhance the UI.
kindly assign me this task.

**Comment by SakiraAli1115** [comment]
Tell me where you can contribute?
@Kushal997-das  Kindly assign this issue!!
