### ISSUE TITLE
Title: adding a chatbot 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Kushal997-das/Project-Guidance#1401]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

i want to add a chatbot which wil be tuned specifically to this website , @Kushal997-das can you please assign me this task , ill add it asap,

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @T-Rahul-prabhu-38 
I appreciate your pull issue can you please describe which type of chatbot you make and give screenshots!!!!

**Comment by T-Rahul-prabhu-38** [comment]
it will be a regular chatbot which will asnwer quesitons related to the website specifically.

**Comment by T-Rahul-prabhu-38** [comment]
it will be a chatbot built using gpt4o and this will be specific to the website so i can answer any questions related to the website too as well as general questions. It will work like a regular chatbot , the ones present on bottom right ususally.

so shall i work on this.

**Comment by SakiraAli1115** [comment]
Okay 
Tell me where you can contribute?
@Kushal997-das kindly assign this issue!!

**Comment by Vyakhya-Namdev** [comment]
Hi! I want to contribute in this issue with chatbot.... Can you please assign me this issue. I assure you i'll perform it very well

**Comment by T-Rahul-prabhu-38** [comment]
@Kushal997-das @SakiraAli1115 can you assign me this task please.
thank you.

**Comment by Vyakhya-Namdev** [comment]
@SakiraAli1115 can you please assign me this task I am good at making chatbots
