### ISSUE TITLE
Title: adding a dark mode

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Kushal997-das/Project-Guidance#1402]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

adding dark mode feature , ive worked on it before so i can fix it @Kushal997-das can you please assign me this.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@T-Rahul-prabhu-38  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
