### ISSUE TITLE
Add follow us section at bottom of website with large size

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Kushal997-das/Project-Guidance#1403]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### What happened?

Add follow us section at bottom of website
<img width="958" alt="image" src="https://github.com/user-attachments/assets/4882eac5-e090-488e-9f7c-b61c5e5df007">

### Urgency (Optional)

High priority 🔴

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @KapuluruBhuvaneswariVspdbct 
I appreciate your pull issue !!!
@Kushal997-das kindly assign this issue!!!
