### ISSUE TITLE
Title: Age Detection Using OpenCV

### ISSUE THREAD

**Issue by ramana2074** [Kushal997-das/Project-Guidance#1405]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

I would like to add a file about Age detection in machine learning folder. 

### Describe the solution you'd like.

This project implements an age detection system using OpenCV's DNN module and a pre-trained Caffe model. The system detects faces in an image and predicts the age group of each detected face.

### Add any other context or screenshots about the feature request here.

![Figure_1](https://github.com/user-attachments/assets/3b9aadd5-ca99-4e88-915f-70f6be1ded3e)
The output would be this.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @ramana2074 
Can you please provide working video!!

**Comment by ramana2074** [comment]
https://github.com/user-attachments/assets/df5beac5-635c-4393-b6a7-97e70650f1e7

Here you go

**Comment by SakiraAli1115** [comment]
@ramana2074 Tell me where you can contribute ?
@Kushal997-das Kindly assign this issue!!!!!

**Comment by ramana2074** [comment]
In the Machine Learning Folder Advanced

**Comment by Kushal997-das** [comment]
> In the Machine Learning Folder Advanced

Try to add in intermediate

**Comment by ramana2074** [comment]
Okay i will add it in Intermediate 
please add level and hactober fest labels
