### ISSUE TITLE
Title: Add Random Avatar Generator project in web development

### ISSUE THREAD

**Issue by hamzathul** [Kushal997-das/Project-Guidance#1406]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Improve web development skills

### Describe the solution you'd like.

Add the project to the web development

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @hamzathul 
I appreciate your pull issue can you give screenshots!!!

**Comment by hamzathul** [comment]
![random-avatar](https://github.com/user-attachments/assets/bf22bd6f-d816-419f-9b3f-fd0fc3fd59b5)

web development -> basic

**Comment by SakiraAli1115** [comment]
@hamzathul Tell me where you can contribute?
like under GSSoC'24 Extended Edition and Hacktoberfest2024?
@Kushal997-das kindly assign this issue!!!

**Comment by hamzathul** [comment]
gssoc-ext
