### ISSUE TITLE
Title: Automated Email Sending Bot

### ISSUE THREAD

**Issue by decodingafterlife** [Kushal997-das/Project-Guidance#1407]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your proposal related to a problem? Please describe.

People send numerous emails every day. This can become repetitive and tedious. I propose to create a bot that'll automate this process. Users should just maintain a csv file with name email and other important details along with the set mail template. The bot will automatically send the required emails.

Possible use cases:
1. Job application emails
2. Customer review emails
3. Community based emails
4. newsletters

Future scope (will work on this after initial PR is approved and accepted):
Using LLM and LangChain to automate email creation and integrating it with the earlier bot making the whole process totally automated.

I will like to work on this project under GSSoCextd and Hactoberfest.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @decodingafterlife 
I appreciate your pull issue !
@Kushal997-das  kindly assign this issue !!!

**Comment by decodingafterlife** [comment]
@SakiraAli1115 thank you! I'll start working. This project will be under Artificial intelligence right?

**Comment by decodingafterlife** [comment]
I am almost done with the code, will work on the readme file and pull a request. Can the hacktoberfest label be also added @Kushal997-das ?
