### ISSUE TITLE
Title: Designing the Logo

### ISSUE THREAD

**Issue by hritika2409** [Kushal997-das/Project-Guidance#1408]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Its not a problem but it will ultimately enhance the website look and features

### Describe the solution you'd like.

I would like to design a better logo for a great look and a presentable look of the webstie

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @hritika2409 
I appreciate your pull issue , can you please describe me little bit and give screenshots!!!

**Comment by hritika2409** [comment]
<img width="179" alt="image" src="https://github.com/user-attachments/assets/5a0a5eb9-1207-4398-8f19-f7348ff69932">
This is just the sample not the actual of how it can look, it will totally depend upon you and your imagination and choices and the way you want

**Comment by Kushal997-das** [comment]
@hritika2409, thank you for opening this! I really appreciate it, but the current version looks good.

**Comment by SakiraAli1115** [comment]
@Kushal997-das  kindly close this issue!!!
