### ISSUE TITLE
Title: Improving the card feature when hovered over

### ISSUE THREAD

**Issue by hritika2409** [Kushal997-das/Project-Guidance#1409]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

<img width="956" alt="image" src="https://github.com/user-attachments/assets/9dca32db-4a20-429f-9af0-b1c42fb2849f">

### Describe the solution you'd like.

Changing it in 3d form so that it should be highlighted when hovered over

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @hritika2409 
I appreciate your pull issue can you give working video!!!

**Comment by hritika2409** [comment]
https://github.com/user-attachments/assets/2c484a04-1eff-4943-91dd-be8049e30f46

kind of this not exactly this but more responsive and interactive

**Comment by Kushal997-das** [comment]
@hritika2409, please merge both of your issues together instead of opening a new one. #1410

**Comment by hritika2409** [comment]
But both the issues are different why to merge them?

**Comment by Kushal997-das** [comment]
> But both the issues are different why to merge them?

Let's focus on one issue at a time and successfully complete one PR first. Both issues can be merged together, so I'm closing this one since you've already opened the other issue.

**Comment by hritika2409** [comment]
so on which issue i have to work on? @Kushal997-das

**Comment by Kushal997-das** [comment]
I've already mentioned to @hritika2409 which issue you need to work on first. Since issue #1410 has already been taken by someone else, it would be better for you to focus on #1409 instead. I'm reopneing this again.

**Comment by hritika2409** [comment]
Ok i will get back to you with the work soon @Kushal997-das
