### ISSUE TITLE
Title: Changing the footer 

### ISSUE THREAD

**Issue by hritika2409** [Kushal997-das/Project-Guidance#1410]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

<img width="959" alt="image" src="https://github.com/user-attachments/assets/2d240339-a900-4584-9026-c16addb17fe0">

### Describe the solution you'd like.

Changing the footer into better looking and responsive features

**Comment by Kushal997-das** [comment]
@hritika2409, please merge both of your issues together instead of opening a new one. #1409

**Comment by GyanaPrakashSahoo7853** [comment]
Description 
The current footer design lacks animation effect and size issue of social media icons . An improved footer design can enhance usability and the overall look of the website. 

Screenshot
![image](https://github.com/user-attachments/assets/ce9f4606-bce9-4771-9418-563f40db6400)
 
I would like to work on it.
@Kushal997-das Please assign me this issue with label hacktoberfest.

**Comment by hritika2409** [comment]
Am i still assigned to do this task?Can i update or i can say upgrade it from my end too?

**Comment by Kushal997-das** [comment]
I've already mentioned to @hritika2409 which issue you need to work on first. Since issue #1409 has already been taken by someone else, it would be better for you to focus on #1410 instead.
