### ISSUE TITLE
Add Twitter Sentiment Analysis Project

### ISSUE THREAD

**Issue by rishikaa1** [Kushal997-das/Project-Guidance#1411]
I would like to propose adding a new project focused on sentiment analysis of Twitter data under advanced level in machine learning. It will demonstrate how to analyze public sentiment on various topics by processing live tweets.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @rishikaa1 
I appreciate your pull issue Can you describe little bit and give screenshots!!

**Comment by rishikaa1** [comment]
@SakiraAli1115 hello. this project will implement a sentiment analysis model for classifying tweets into three categories: positive, negative, and neutral. it will utilize the Sentiment140 dataset from Kaggle to analyze public sentiment through tweets, instead of relying on the Twitter API for live data, which has become more restrictive these days. 

I will build and train a logistic regression classifier to predict tweet sentiments, along with providing performance metrics and visualizations for added details and interpretation.

Sample screenshot: 
![Snap](https://github.com/user-attachments/assets/2643613e-5462-4416-8eea-794a4a6e44b7)

**Comment by SakiraAli1115** [comment]
@rishikaa1 Tell me where you can contribute?
@Kushal997-das kindly assign this issue!!!!

**Comment by rishikaa1** [comment]
@SakiraAli1115 i want to contribute this project to the advanced level under machine learning.

**Comment by SakiraAli1115** [comment]
@rishikaa1 like under GSSoC'24 extended edition and hacktoberfest?

**Comment by rishikaa1** [comment]
@SakiraAli1115 yes

**Comment by rishikaa1** [comment]
@SakiraAli1115 hey, i was thinking if i could implement this same project using deep learning to achieve better accuracy and add both models to the repo if assigned?

**Comment by Kushal997-das** [comment]
@rishikaa1 We will determine whether it falls under advanced or intermediate. For now, please mention which program it is under, as requested by Mentor @SakiraAli1115 . Kindly reply there first.

**Comment by rishikaa1** [comment]
@Kushal997-das i have replied that i want to contribute under GSSoC'24 extended and hacktoberfest.

**Comment by rishikaa1** [comment]
@Kushal997-das @SakiraAli1115 could you tell me under which section in machine learning should i add this project?
