### ISSUE TITLE
Title: Movie recommendation System on the basis of emotion

### ISSUE THREAD

**Issue by Amanjayswal500** [Kushal997-das/Project-Guidance#1412]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

Many people struggle to find movies that support their mental health, often leading to unsuitable or triggering content.

### Describe the solution you'd like.

A movie recommendation system that suggests films based on users’ emotional states and preferences to promote mental well-being.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-10-10 111234](https://github.com/user-attachments/assets/3640b605-abc2-4c49-8da9-6c24fd2e732e)
After clicking link 
![Screenshot 2024-10-10 111310](https://github.com/user-attachments/assets/27134bd9-9493-4a6d-9408-1af6a50b0eb8)

**Comment by Amanjayswal500** [comment]
@Kushal997-das  please assign this issue to me

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Amanjayswal500 
I appreciate your pull issue!!!
@Kushal997-das Kindly assign this issue!!!

**Comment by Amanjayswal500** [comment]
I want to add this feature to your project
@SakiraAli1115

**Comment by SakiraAli1115** [comment]
@Amanjayswal500 
I mean to say that under GSSoC'24 Extended Edition and hacktoberfest2024 ?
