### ISSUE TITLE
Title: want to add a login/registration page using CPP

### ISSUE THREAD

**Issue by shivigoyal4321** [Kushal997-das/Project-Guidance#1415]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

YES THIS FEATURE/CODE is related to the problem. It reinforces core programming concepts such as data structures, file handling, and object-oriented programming.

### Describe the solution you'd like.

Through c++, the system allows new users to register by providing their personal information such as first name, last name, email address, and password. The system validates the input data to ensure its correctness. Existing users can log in using their username and password. 

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-10-10 185752](https://github.com/user-attachments/assets/9e239a64-9aae-4465-99d0-6febfff34f18)
the output will look like this.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @shivigoyal4321 
I appreciate your pull issue , can you describe me and give screenshots!!!

**Comment by Kushal997-das** [comment]
@shivigoyal4321 Is this is desktop application ?

**Comment by shivigoyal4321** [comment]
@Kushal997-das no it is not, although it runs very well in the terminal of (like VS Code) itself.

**Comment by shivigoyal4321** [comment]
@SakiraAli1115 hello, i have included the screen-shot, kindly check

**Comment by SakiraAli1115** [comment]
@shivigoyal4321 This is not clear screenshot, its terminal kindly provide a proper screenshot then will decide

**Comment by Kushal997-das** [comment]
Hello @SakiraAli1115,

The person hasn't sent any screenshots yet, so why did you mention that the screenshot is not clear?
