### ISSUE TITLE
Enhance the items under table of content with Dynamic Hover Effect

### ISSUE THREAD

**Issue by sanchitc05** [Kushal997-das/Project-Guidance#1418]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your proposal related to a problem? Please describe.

What's the style idea?
The items under the table of contents are static and look boring. I believe a dynamic design could attract a lot of users and keep them engaged on the website. The goal is to implement a hover effect that captures users' attention and encourages interaction.

**Proposed Changes:**

> Background Transition:

Add a background color or gradient transition that changes on hover.
Consider a shadow effect to create depth.

Kindly assign me this issue.

![Screenshot (224)](https://github.com/user-attachments/assets/3ce5c7df-a774-4bcd-8f17-18407227a47a)

**Comment by sanchitc05** [comment]
Please add the hacktoberfest label as well

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@Kushal997-das kindly add the hacktoberfest label

**Comment by sanchitc05** [comment]
Should I start the work? Will you add the label later?

**Comment by SakiraAli1115** [comment]
@sanchitc05 Yes

**Comment by sanchitc05** [comment]
@Kushal997-das @SakiraAli1115 please check my PR it's been quite a long time. Do check it and let me know if you need any improvements or modifications.

**Comment by sanchitc05** [comment]
@Kushal997-das @SakiraAli1115 I would really appreciate it if you could spare some time from your busy schedule and review my PR as soon as possible.
