### ISSUE TITLE
I want to add "Handwritten-Digit-Recognition-using-SVM-classifier" notebook 

### ISSUE THREAD

**Issue by madhavi-peddireddy** [Kushal997-das/Project-Guidance#1420]
Hello,

I would like to contribute to your repository by adding a new file for handwritten digit recognition using an SVM classifier. 
Handwritten digit recognition is indeed a fundamental project for beginners in machine learning. It introduces key concepts like data preprocessing, feature extraction, and model building. By using models such as Support Vector Machines (SVMs), beginners can understand the basics of classification, image processing, and model evaluation. It's a great starting point to gain hands-on experience and build a solid foundation in machine learning techniques.
@Kushal997-das

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @madhavi-peddireddy 
I appreciate your pull issue , Can you give screenshots!!!

**Comment by madhavi-peddireddy** [comment]
![Screenshot (113)](https://github.com/user-attachments/assets/4dba2b61-6a63-437f-b538-ff5b85b5dfd8)
![Screenshot (114)](https://github.com/user-attachments/assets/e210ca2b-3349-4273-b820-7dd67e919cf6)

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly close this issue!!!
