### ISSUE TITLE
ADDING A FAQ SECTION WITH PROPER UI

### ISSUE THREAD

**Issue by eshitatalukdar08** [Kushal997-das/Project-Guidance#1422]
Hello @Kushal997-das, the website is missing a FAQ section. I can create one and ensure it has a professional appearance. Please assign this task to me. Thank you and have a great day!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @eshitatalukdar08 
I appreciate your pull issue , Can you provide screenshots!!!

**Comment by eshitatalukdar08** [comment]
Sure!
![dropdown](https://github.com/user-attachments/assets/ba61ff5e-0207-4f2d-b290-b9a7b8386c6e)
The idea will remain the same however I will use a different design according to your website. I will include the questions related to your Project Guidance website and will try to answer them for you. Can you please assign me to this task? I will also apply subtle transitions to the dropdown icon.

**Comment by SakiraAli1115** [comment]
@eshitatalukdar08 Tell me where you can contribute?
like under GSSoC'24 Extended Edition and hacktoberfest2024
@Kushal997-das kindly assign this issue!!!

**Comment by eshitatalukdar08** [comment]
Thank you so much, can you please assign the level label?

**Comment by Sourabh782** [comment]
hii @Kushal997-das is this issue open? if yes, can i contribute to it? :)
