### ISSUE TITLE
Icons are missing

### ISSUE THREAD

**Issue by Asmi-Shetty** [Kushal997-das/Project-Guidance#1423]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### What happened?

as soon as we open the website we see that the icons are missing in front of all the sections which doesn't give a good impression to the users.
![Screenshot 2024-10-11 122118](https://github.com/user-attachments/assets/b17cbc13-00ef-4163-a8df-f7b80e9cbc05)

### Urgency (Optional)

High priority 🔴

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Asmi-Shetty 
I appreciate your pull issue!!
@Kushal997-das Kindly assign this issue!!!!

**Comment by Kushal997-das** [comment]
Hello @Asmi-Shetty It's already working fine; please check on your end. 
![check9](https://github.com/user-attachments/assets/3f24e1dc-13ce-4def-a280-18490e0b8f96)
