### ISSUE TITLE
Checklist for steps to contribute

### ISSUE THREAD

**Issue by c4dr-me** [Kushal997-das/Project-Guidance#1424]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### What happened?

the checklist should either be unselected for all or selected for all the steps 
![image](https://github.com/user-attachments/assets/3bd80980-2855-460a-b29f-5e8a286237e7)

### Urgency (Optional)

Low priority 🚦

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @c4dr-me 
I appreciate your pull issue, can you describe  and give screenshot after update the output!!!
