### ISSUE TITLE
Garden Planning Website

### ISSUE THREAD

**Issue by ananyag309** [Kushal997-das/Project-Guidance#1428]
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

The Garden Planner website is an interactive tool designed for users to create and visualize their ideal garden layout. Users can drag and drop various plants into a grid to plan their garden space while tracking the total cost based on the selected plants. The site allows for saving and loading garden layouts, making it easy to manage and modify designs over time. With a user-friendly interface and responsive design, it aims to enhance the gardening experience for both beginners and enthusiasts.

### 🔍 Priority Level
- [x] High
- [x] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @ananyag309 
I appreciate your pull issue, Can you give screenshots!!!!

**Comment by ananyag309** [comment]
@SakiraAli1115 sure

- here you can set your plot 
![image](https://github.com/user-attachments/assets/f60ecefd-6f9e-4b56-a80a-3b3366065700)
- add plant and soil based planning
![image](https://github.com/user-attachments/assets/8d4437be-c4b6-4828-8995-9254b4265257)


I am still trying to add more featurs and will improve the css as well

**Comment by SakiraAli1115** [comment]
@Kushal997-das  kindly assign this issue!!!
