### ISSUE TITLE
Title: Add brain tumor detection 

### ISSUE THREAD

**Issue by Aditijainnn** [Kushal997-das/Project-Guidance#1432]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

I want to add ml model of brain tumor detection

### Describe the solution you'd like.

assign this to me under gssoc ext

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Aditijainnn 
I appreciate your pull issue , can you describe little bit more and give screenshots!!!!!

**Comment by Aditijainnn** [comment]
> I am the mentor of this project. Hello @Aditijainnn I appreciate your pull issue , can you describe little bit more and give screenshots!!!!!

<img width="790" alt="SFWEF" src="https://github.com/user-attachments/assets/5ab101b0-5f8b-4d4b-8db3-35141227b271">
<img width="418" alt="ZxZAX" src="https://github.com/user-attachments/assets/be989f3c-044d-4451-9ae7-9ffbc8c6aacc">
