### ISSUE TITLE
Title: Add background remover app

### ISSUE THREAD

**Issue by Aditijainnn** [Kushal997-das/Project-Guidance#1433]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

I want to add abckground remover app

### Describe the solution you'd like.

this will remove background from pictures

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Aditijainnn 
I appreciate your pull issue , can you describe little bit more and give screenshots!!!

**Comment by Aditijainnn** [comment]
> I am the mentor of this project. Hello @Aditijainnn I appreciate your pull issue , can you describe little bit more and give screenshots!!!

YES its a frontend project basically it removes background of images
![image](https://github.com/user-attachments/assets/c3e1a9b5-ac3b-44da-ada8-45425c1cc4de)

**Comment by Kushal997-das** [comment]
@Aditijainnn Let's complete your first issue before moving on to the second. I'm closing this for now.
