### ISSUE TITLE
I want contribute AI Image Generator Project

### ISSUE THREAD

**Issue by damarudhvarma** [Kushal997-das/Project-Guidance#1435]
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

The AI Image Generator solves key issues by automating the creation of custom images from text prompts, saving users time and effort. It eliminates the need for manual design skills, reliance on stock images, and the high cost of hiring designers, making it easy for anyone to generate unique visuals quickly and affordably.

You Can Watch the demo video [here](https://drive.google.com/file/d/15PmkjI34Wo2k6_bGK53dmWar4GSQ99WU/view?usp=sharing).

### 🔍 Priority Level
- [ ] High
- [x] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [ ] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### 💬 Next Steps:

You can expect a response within [2 days].

**Comment by damarudhvarma** [comment]
@Kushal997-das  can you please assign this to me

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @damarudhvarma 
I appreciate your pull issue , can you give screenshots!!!

**Comment by damarudhvarma** [comment]
## In this project  i have used <b>Hugging Face API<b> to generate Images using Prompt

<p>At the backend the API uses the <b> Stable  Diffusion Model <b> to create images from the prompt<p>

![Screenshot 2024-10-12 075703](https://github.com/user-attachments/assets/033d5dba-4d7b-4d3d-bfc3-64b8afe43b0d)
![Screenshot 2024-10-12 075734](https://github.com/user-attachments/assets/6dfb0ad5-f3b6-4384-b407-e88122e4217c)

https://github.com/user-attachments/assets/883033c1-e773-4aac-80a5-7cc15c6f3760

**Comment by SakiraAli1115** [comment]
@Kushal997-das  kindly assign this issue!!!
