### ISSUE TITLE
Title: Medical Diagnoser

### ISSUE THREAD

**Issue by ramana2074** [Kushal997-das/Project-Guidance#1436]
### Initiative (Required)

GSSoC  extended(Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

To add a project that implements Medical diagnosis which provides an appropriate solution to the patient input or problem.

### Describe the solution you'd like.

This project implements a Medical Diagnosis and Prescription System using Deep Learning techniques. By utilizing the power of Long Short-Term Memory (LSTM) networks, this system is capable of analyzing a patient's symptoms and providing an accurate diagnosis along with the recommended medication. The LSTM model, a variant of Recurrent Neural Networks (RNN), is particularly suited for processing sequential data like patient symptoms and offers significant advantages when dealing with textual data.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @ramana2074 
I appreciate your pull issue, Can you give screenshots!!
