### ISSUE TITLE
Title: Google clone 

### ISSUE THREAD

**Issue by OKpoorav** [Kushal997-das/Project-Guidance#1438]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

The current google clone under the web development easy action is quite out dated along side that the current hover animations are not the same as original one , It lacks icons for search by image etc.

### Describe the solution you'd like.

I would like to update the logo, make the hover animation closer to the original one and add make it closer to the original version

**Comment by SakiraAli1115** [comment]
Hey I am the mentor of this project
@OKpoorav Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
