### ISSUE TITLE
Title: RFID Door Lock  [IIOT]

### ISSUE THREAD

**Issue by IkkiOcean** [Kushal997-das/Project-Guidance#1440]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Yes, the feature request addresses the need for a secure and convenient way to manage access control in various environments, such as homes, offices, or restricted areas. Traditional key-based locks are prone to issues like key loss, duplication, and unauthorized access. Managing multiple keys can be cumbersome and presents a security risk if keys fall into the wrong hands.

### Describe the solution you'd like.

I will design and develop an RFID (Radio Frequency Identification) door lock system that provides secure and contactless access control. The system will use RFID cards or tags to authenticate users and unlock doors.

The RFID door lock system offers a modern, contactless solution that enhances security, simplifies access management, and provides a more convenient alternative to physical keys. It solves the problem of unauthorized access by ensuring that only registered RFID tags or cards can unlock the door, reducing the risk associated with lost or stolen keys.

**Comment by SakiraAli1115** [comment]
Hey I am the mentor of this project
@IkkiOcean  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.

**Comment by IkkiOcean** [comment]
> Hey I am the mentor of this project
> @IkkiOcean  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
> @Kushal997-das kindly close the issue since it already exist in our project.
> 
> 

I assure you this concept is new to the project. There is a home automation project but it doesn't include RFID system. I have searched the project again and There is no implementation of RFID in it. Please reconsider

**Comment by SakiraAli1115** [comment]
@IkkiOcean  
Ok share working video, then I'm decide is it different or not?

**Comment by IkkiOcean** [comment]
> @IkkiOcean Ok share working video, then I'm decide is it different or not?


https://github.com/user-attachments/assets/522896c6-f085-4bdb-b31c-df5eec2c8f8c

There you go. I connected all of this again for the video... so please assign this to me

**Comment by IkkiOcean** [comment]
@SakiraAli1115 so what do you say? This is different from other projects so please assign it to me

**Comment by Kushal997-das** [comment]
@IkkiOcean, I’m assigning this to you. Please ensure that it is different.

**Comment by IkkiOcean** [comment]
> @IkkiOcean, I’m assigning this to you. Please ensure that it is different.
> 
> 

Yeah sure! Please assign level 3 as I will going through making circuit diagram, embedded c code and a demo video.
