### ISSUE TITLE
Title: Emotion Based Music Player

### ISSUE THREAD

**Issue by shanmukhi-developer** [Kushal997-das/Project-Guidance#1444]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Users often struggle to select music that fits their mood, especially when emotions change throughout the day. Traditional music players rely on user preferences, which may not capture the user's current emotional state. Additionally, the overwhelming number of song choices on streaming platforms can make it difficult for users to find the right music. There is also a lack of real-time adaptability and deeper emotional personalization in existing systems.

### Describe the solution you'd like.

An emotion-based music player project addresses several challenges by leveraging emotional detection and machine learning techniques to create a more personalized and adaptive music experience. This project solves key challenges by using emotion detection techniques, such as facial recognition or voice analysis, to curate playlists that match the user’s mood automatically. It adapts to real-time emotional changes, providing a dynamic music experience tailored to the user's feelings. This reduces the overwhelming task of manually selecting songs from large libraries while offering deeper personalization compared to traditional music systems. With privacy protections and options for manual control, the player balances automation with user choice. It also addresses cultural nuances, ensuring music suggestions are emotionally and contextually relevant to each user.ant to each user.

### Add any other context or screenshots about the feature request here.

Please add labels (gssoc-ext)
Some screenshots are:
![Screenshot 2024-10-12 173747](https://github.com/user-attachments/assets/e8130422-48c7-4100-8b3a-7036c360d4

![Screenshot 2024-10-12 183922](https://github.com/user-attachments/assets/c253f15e-8ac5-47a1-95de-b8fde97998bc)
f4)

![Screenshot 2024-10-12 175323](https://github.com/user-attachments/assets/f423a015-460b-43b7-9ede-d34b557f7978)

![Screenshot 2024-10-12 175557](https://github.com/user-attachments/assets/a31ea4cb-66c4-4601-b01b-ad7b457c2948)

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @shanmukhi-developer 
I appreciate your pull issue and thank you for your contribute!!!
@Kushal997-das kindly assign this issue!!!!

**Comment by shanmukhi-developer** [comment]
Can I start pushing the issue?

**Comment by Kushal997-das** [comment]
@shanmukhi-developer,

Hello, I noticed that a similar issue was created, and an open PR for the same problem exists in another repository, which violates our rules. As a result, I have marked this one as spam. You are no longer permitted to submit any PRs or issues in this repository.

If you'd like, I can provide you with the link for your reference, but please note that the project admins are also likely to close this PR, which I want to avoid.
