### ISSUE TITLE
Title: Google Advanced Search clone

### ISSUE THREAD

**Issue by nksmanya** [Kushal997-das/Project-Guidance#1445]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

I would like to add the google advanced search clone, which has 
Find pages with… “all these words:”
Find pages with… “this exact word or phrase:”
Find pages with… “any of these words:”
Find pages with… “none of these words:”
Like Google’s own Advanced Search page, the four options should be stacked vertically.

### Describe the solution you'd like.

I would like to work on this project. Please assign this issue to me.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @nksmanya 
I appreciate your idea , can you give working video !!!

**Comment by nksmanya** [comment]
https://github.com/user-attachments/assets/5e0d51fb-e7de-4c2b-b11b-527be745f07b

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue!!!
