### ISSUE TITLE
Title: Responsive Neumorphic Calculator

### ISSUE THREAD

**Issue by nksmanya** [Kushal997-das/Project-Guidance#1446]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

To create a responsive neumorphic-themed calculator using HTML, CSS and JavaScript

### Describe the solution you'd like.

I would like to create a responsive neumorphic-themed calculator using HTML, CSS and JavaScript. 
Please assign this issue to me.

**Comment by SakiraAli1115** [comment]
Hey I am the mentor of this project
@nksmanya  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
