### ISSUE TITLE
Title: Object Detection Andrioid app

### ISSUE THREAD

**Issue by spandana2004** [Kushal997-das/Project-Guidance#1447]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Creating an object detection app that uses the Ml algorithms to do the same.

### Describe the solution you'd like.

To build an object detection app using Android's ML Kit, start by setting up Android Studio and adding ML Kit dependencies in your `build.gradle`. Use CameraX for capturing the camera feed and displaying it in a `PreviewView`. Configure the object detection by initializing `ObjectDetectorOptions` with desired settings (e.g., single/multiple object detection, classification). Capture frames using `InputImage`, and process them with ML Kit’s `ObjectDetector` to identify objects and their bounding boxes. Finally, overlay detection results on the camera feed using a custom `Canvas` view for visual feedback.

### Add any other context or screenshots about the feature request here.

..

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @spandana2004 
I appreciate your pull issue, Can you give screenshots and thank you for your contribute!!!

**Comment by spandana2004** [comment]
![image](https://github.com/user-attachments/assets/e12b7e86-7223-444c-9789-7e5dea371c59)

**Comment by SakiraAli1115** [comment]
Tell me where you can contribute?
@Kushal997-das  kindly assign this issue!!!

**Comment by spandana2004** [comment]
How to add ML Kit Object Detection and Tracking to Android app. How to use on-device object detection and tracking in ML Kit to detect objects in images. complete source code will be provided.
