### ISSUE TITLE
Title: login signup page with Google 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Kushal997-das/Project-Guidance#1448]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

We can implement a sign in page with Google 

### Describe the solution you'd like.

I am willing to work on this please assign me

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Sawan-Kushwah 
I appreciate your pull issue, can you give screenshots!!!!

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/c5df3d6f-4a4e-46f7-8596-47c81c156554

@SakiraAli1115 
it will work something like this i have implemented this 
you can sign in with google or custom mail feature !

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue!!
@Sawan-Kushwah tell me where you can contribute?

**Comment by Sawan-Kushwah** [comment]
Firebase or oauth 2.0 I can do both ?

**Comment by Sawan-Kushwah** [comment]
@SakiraAli1115 Please assign me this so that i can start working on this , if its suits you !?

**Comment by Meetpidev** [comment]
@Kushal997-das Can i wok on it ? requested to assign me this issue..

**Comment by Sawan-Kushwah** [comment]
@Kushal997-das  i will make pr today
