### ISSUE TITLE
Title: Navbar enhancement

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [Kushal997-das/Project-Guidance#1449]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

The navbar looks too big and much designs are also not present. I want to design the navbar a bit and add effects for precision.
Please assign the issue to me and also add labels of hacktoberfest-accepted, gssoc-extd,and levels.

### Describe the solution you'd like.

HOVER EFFECT TO BE ADDED TO NAVBAR.
BREADTH OF NAVBAR NEEDS TO BE DECREASED.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@ABHISIKTAcommits Hello
I appreciate your pull issue , can you give screenshot after update the output.
