### ISSUE TITLE
Title: COPYRIGHTS SECTION AT THE BOTTOM OF THE PAGE IS MISSING.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [Kushal997-das/Project-Guidance#1450]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

A COPYRIGHT SECTION IS NEEDED TO BE ADDED AT THE BOTTOM OF THE SCREEN FOR SECURITY REASONS.
PLEASE ASSIGN THIS ISSUE TO ME AND ALSO ADD THE LABELS OF hacktoberfest-accepted and gssoc-extd.

### Describe the solution you'd like.

Adding the section would make the page more professional.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @ABHISIKTAcommits 
I appreciate your pull issue, can you give screenshots!!!

**Comment by ABHISIKTAcommits** [comment]
@SakiraAli1115 yes i'm sending the screenshot....

AFTER INSERTING THE COPYRIGHT SECTION THE WEBPAGE WOULD LOOK LIKE :

![Screenshot 2024-10-13 114423](https://github.com/user-attachments/assets/dd5a8fd6-fcb5-4b6a-a463-516c0652ff9f)

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue!!!!

**Comment by ABHISIKTAcommits** [comment]
@Kushal997-das please assign the issue to me so that I can start working on the project asap...!!!

**Comment by Kushal997-das** [comment]
Hello @ABHISIKTAcommits ,

Since you’ve already opened issue #1449, please allow that to be completed and merged before opening any new issues. We will be closing this current issue for now.

Thank you for your understanding!
