### ISSUE TITLE
Title: THE WEBPAGE HAS TOO MANY SPACES.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [Kushal997-das/Project-Guidance#1451]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Explain what you want to add/change in the documentation.

THE SPACES LOOKS MORE THAN EXPECTED AFTER EACH HEADING. I WANT TO DECREASE THE SPACES AND MAKE IT LOOK GOOD.
PLEASE ASSIGN THIS ISSUE TO ME AND ALSO ADD THE LABELS OF hacktoberfest-accepted and gssoc-extd.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @ABHISIKTAcommits 
I appreciate your pull issue and thank you for your contribute...
@Kushal997-das  kindly assign this issue!!!!!

**Comment by Kushal997-das** [comment]
Hello @ABHISIKTAcommits ,

Since you’ve already opened issue https://github.com/Kushal997-das/Project-Guidance/issues/1449, please allow that to be completed and merged before opening any new issues. We will be closing this current issue for now.

Thank you for your understanding!
