### ISSUE TITLE
Code Review: Calendar Generation Logic Improvements

### ISSUE THREAD

**Issue by KashishJuneja101003** [Kushal997-das/Project-Guidance#1452]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### What happened?

The calendar generation code has several critical issues:

    1. Uninitialized Variables: Key variables like c, s, and p are not initialized, leading to potential undefined behavior.
    2. Leap Year Logic: The leap year calculation lacks clarity and could be optimized.
    3. Edge Case Handling: Invalid month inputs are not properly managed.
    4. Variable Naming: Variable names should be more descriptive to reflect the data they hold, enhancing readability 
         and maintainability.

These issues can negatively affect the code's functionality and clarity.

### Urgency (Optional)

None

**Comment by KashishJuneja101003** [comment]
Please do assign this issue to me.
Also, add gssoc-extd, hactoberfest and level labels while assigning.
Thank You!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @KashishJuneja101003 
I appreciate your pull issue, can you give screenshots!!!!

**Comment by KashishJuneja101003** [comment]
![image](https://github.com/user-attachments/assets/b5f18263-bddd-4b72-9713-1b0e9f3c7178)
![image](https://github.com/user-attachments/assets/e3c5f941-aa7e-4a13-9b7e-683ba86c532e)
Here month validation is handled in a separate if-block which hinders the code redability. Thus, it must be mentioned in the default block of switch-case.

![image](https://github.com/user-attachments/assets/8e412025-0605-4054-b523-2526f60f00ee)
The variables used may be named as per the data they hold. For example, 'month_name' is more descriptive variable than 'b'.

![image](https://github.com/user-attachments/assets/303f09ff-74b9-4b22-a725-b7785d6ea7d2)
The leap year calculation in the code is not optimized because it uses multiple conditional statements that are evaluated separately.
This results in more lines of code and more individual checks, which can be streamlined. Combining these conditions into a single logical expression makes the code more concise, clearer, and potentially faster, as it reduces the number of evaluations performed.

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue!!
