### ISSUE TITLE
Upgrading UI of footer 

### ISSUE THREAD

**Issue by AsifQamar** [Kushal997-das/Project-Guidance#1453]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Upgrading UI for better user experince

### Describe the solution you'd like.

i'll make it amazing

### Add any other context or screenshots about the feature request here.

<img width="960" alt="Screenshot_183" src="https://github.com/user-attachments/assets/6a1367f6-575e-48e0-98bc-e7340a2baad2">

**Comment by AsifQamar** [comment]
@Kushal997-das please assign me this issue

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @AsifQamar 
I appreciate your pull issue, can you  give screenshot after update!!!

**Comment by AsifQamar** [comment]
> I am the mentor of this project. Hello @AsifQamar I appreciate your pull issue, can you give screenshot after update!!!

Sure i'll send the updated footer Screenshot soon

**Comment by AsifQamar** [comment]
@SakiraAli1115  check it
<img width="960" alt="Screenshot_185" src="https://github.com/user-attachments/assets/6a94cc8d-735c-4108-8f9a-9fc745edf538">
