### ISSUE TITLE
Title: Jobify Job Seeker Webapp

### ISSUE THREAD

**Issue by itznayan** [Kushal997-das/Project-Guidance#1455]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Yes, the feature request is related to the user experience for job seekers using the Jobify web app. Currently, job seekers may struggle with tracking their applications, managing job alerts, and networking with potential employers. This can lead to frustration and a lack of organization, making the job search process more challenging.

### Describe the solution you'd like.

I would like to implement a feature that provides a comprehensive job application dashboard for users. This dashboard would include the following functionalities:

Application Tracker: Allow users to easily track the status of their job applications (e.g., applied, interview scheduled, offer received, etc.) with a visual timeline.

Resume and Cover Letter Management: Provide users with the ability to upload and manage multiple resumes and cover letters tailored to different job applications.

User-Friendly UI: Ensure the dashboard is intuitive and easy to navigate, with clear sections for each feature.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @itznayan 
I appreciate your pull issue, can you give working video and thank you for your contribute!!!

**Comment by itznayan** [comment]
@SakiraAli1115 It's MERN Stack project where user can login, post job and apply for job. Video is too long so i am not able to provide.

**Comment by itznayan** [comment]
@Kushal997-das @SakiraAli1115 


https://github.com/user-attachments/assets/75cbd08b-cc0a-44f1-b253-c4d737c5eb0d

**Comment by SakiraAli1115** [comment]
@itznayan Tell me where you can contribute?
@Kushal997-das Kindly assign this issue!!

**Comment by Kushal997-das** [comment]
@itznayan Hello, please follow the rules of this event and avoid spamming by submitting one project across multiple repositories to gain points. I can point out the duplicate issue here , and I don't want to negatively impact your score. I'm closing this one.
