### ISSUE TITLE
Title: Add profile card project in Basic web development project

### ISSUE THREAD

**Issue by Arveti-likhitha** [Kushal997-das/Project-Guidance#1456]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

A profile card adds overall usability as personal data is now more viewable and presentable. It essentially allows for an interface tailored to individualization-that is, maximum involvement with consistency in the user profile layout and a professional look. More importantly, this feature can be reused in the rest of the project, so it really makes the code scalable and maintainable.

### Describe the solution you'd like.

1. Create a profile card application that provides quick access to important user information in a single view.  
2. It increases engagement and encourages users to interact more with their profiles or those of other users. 
3. The profile card includes social media links or contact information, it promotes networking within the user base, making it easy to connect with others directly from the app.

### Add any other context or screenshots about the feature request here.

Please assign these labels to me: hacktoberfest-accepted, gssoc-ext

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @Arveti-likhitha 
I appreciate your pull issue , can you give screenshots!!!!

**Comment by Arveti-likhitha** [comment]
Please take a look at the screenshot below and let me know if this looks good. Please suggest if any changes are to made so that I can learn and improve.

![image](https://github.com/user-attachments/assets/3ce8095d-8593-449e-aef5-b7ce315869cb)
