### ISSUE TITLE
Bug: Empty Space Inputs Accepted as Valid Tasks

### ISSUE THREAD

**Issue by KashishJuneja101003** [Kushal997-das/Project-Guidance#1459]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### What happened?

![image](https://github.com/user-attachments/assets/b464cf7b-7279-42b2-9a76-8f4c09904fbb)

The application currently allows users to add tasks that consist only of whitespace (spaces, tabs, etc.) to the task list. This behavior is unintended, as it does not fulfill the purpose of the task manager, which should only allow valid, meaningful tasks to be added.

**Expected Behavior:**
The application should validate the input to ensure that it is not empty or composed solely of whitespace. If the user attempts to add such an entry, a warning message should be displayed indicating that the input is invalid, and the task should not be added to the list.

**Suggested Fix:**
Implement input validation using the strip() method on the task input to remove leading and trailing whitespace. Before adding the task to the list, check if the trimmed input is an empty string. If it is, display a warning message to the user.

### Urgency (Optional)

None

**Comment by KashishJuneja101003** [comment]
Kindly assign this issue to me.
Also, add labels gssoc-extd, hactoberfest and level.
Thank You!

**Comment by SakiraAli1115** [comment]
Hello @KashishJuneja101003 
Issue number #1452 kindly complete this one then open new issue , otherwise I'll close the issue.

**Comment by KashishJuneja101003** [comment]
Hello @SakiraAli1115 
Issue #1452 is not assigned to me yet.

**Comment by Kushal997-das** [comment]
@KashishJuneja101003 

Since you’ve already opened issue, please allow that to be completed and merged before opening any new issues. We will be closing this current issue for now.

Thank you for your understanding!

**Comment by KashishJuneja101003** [comment]
Hello, my previous issues have been successfully merged. Could you please open this issue?

**Comment by KashishJuneja101003** [comment]
May I start working on this issue?
