### ISSUE TITLE
[Bug Title here] Readme file Contribution is repeated twice

### ISSUE THREAD

**Issue by AnanteshG** [Kushal997-das/Project-Guidance#1460]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### What happened?

The 'Project Admin' and 'Contribution' part in the readme file is repeated. 

https://github.com/user-attachments/assets/7787bc71-abb3-4305-b179-2fe2f496c02d

### Urgency (Optional)

Medium priority ⚠️

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @AnanteshG 
I appreciate your pull issue and thank you for your contribute!!
Tell me where you can contribute? 
@Kushal997-das kindly assign this issue!!

**Comment by AnanteshG** [comment]
I'll contribute in the readme.md file of the repository.

**Comment by AnanteshG** [comment]
Yeah GSSoC and Hacktoberfest both.

**Comment by AnanteshG** [comment]
@SakiraAli1115 @Kushal997-das assign the issue to me so that I can make a PR.
