### ISSUE TITLE
Title: The basic calulators css could be better

### ISSUE THREAD

**Issue by Arushi2S** [Kushal997-das/Project-Guidance#1462]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

As ui is the game changer in a project. I feel better use of css coloring scheme would enhance learning experience (in respect of basic calculator). 

### Describe the solution you'd like.

The interesting colour world be classic black orange as available on our phones

**Comment by Arushi2S** [comment]
Plz assign me this issue

**Comment by Arushi2S** [comment]
Sure 
![Screenshot (119)](https://github.com/user-attachments/assets/f49dbede-0f23-496d-a7c7-062ce5ec944b)

**Comment by SakiraAli1115** [comment]
@Arushi2S Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.

**Comment by Arushi2S** [comment]
okay sir
