### ISSUE TITLE
Title: Lane Line Detection for Autonomous Vehicles using OpenCV and Machine Learning

### ISSUE THREAD

**Issue by aviralgarg05** [Kushal997-das/Project-Guidance#1463]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

Improve the ADAS and auto lane alignment system in present vehicles as well as future autonomous vehicles

### Describe the solution you'd like.

Use Advanced Machine Learning Algos and OpenCV to detect lane line

### Add any other context or screenshots about the feature request here.

I am also GSSOC'24 Extended contributor

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue!!!!

**Comment by aviralgarg05** [comment]
Pls assign so that i can start working

**Comment by SakiraAli1115** [comment]
@aviralgarg05 Hello, please follow the rules of this event and avoid spamming by submitting one project across multiple repositories to gain points. I can point out the duplicate issue here , and I don't want to negatively impact your score.
@Kushal997-das kindly close this issue!
