### ISSUE TITLE
Arrange Project Names in Lexicographical Order in the README file of Machine Learning and Data Science folder

### ISSUE THREAD

**Issue by neyhere07** [Kushal997-das/Project-Guidance#1465]
# OVERVIEW :

The current list of projects in the <strong>"Machine Learning and Data Science"</strong> folder of this repository is not organized in lexicographical (alphabetical) order. Having the project names listed in lexicographical order would help learners find and navigate through the projects more easily and efficiently. 

I would like to request sorting the project names from <strong>Basics</strong> to <strong>Advanced</strong> in lexicographical order in the README file. This will improve the readability and accessibility of the content for users.

# SCREENSHOT :
## Before :

![mldsprojects](https://github.com/user-attachments/assets/14845be4-7f53-401e-b073-46eee98a8e49)

## After :
![dsmlproafter](https://github.com/user-attachments/assets/ba2a0c64-ccac-4b2c-a268-6c4e07c9ad59)

<hr>

<em>I would like to work on this issue. Kindly assign me under GSSOC-Extd'24 and Hacktoberfest-2024. Thank you!</em>

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @neyhere07 
I appreciate your pull issue and thank you for your contribute!!
Tell me where you can contribute?
@Kushal997-das kindly assign this issue!!!
