### ISSUE TITLE
Title: Adding cards of projects

### ISSUE THREAD

**Issue by MaahiVaghela** [Kushal997-das/Project-Guidance#1466]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

After choosing Domain, list of projects is provided which makes it bit confusing
![Screenshot 2024-10-14 121823](https://github.com/user-attachments/assets/244daee5-9b0f-47b2-afb1-d29bb59cdf03)

### Describe the solution you'd like.

It's better if we provide list of projects in form of cards which provides title and description of particular project. If user find it interesting, then they click on card which redirect it to particular project's GitHub. In additionally we can add which language or technology is used in the project on cards. Which makes user select project according to their skills. Please assign this issue to me.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @MaahiVaghela 
I appreciate your pull issue, can you give screenshots after update output!!

**Comment by MaahiVaghela** [comment]
sure

**Comment by charmi2109** [comment]
I'm keen to work on this, making the website more appealing .Please Assign me this issue @Kushal997-das

**Comment by Kushal997-das** [comment]
@charmi2109 KIndly open new issue for that.
