### ISSUE TITLE
Title: Add Netflix home page clone in basic web development project

### ISSUE THREAD

**Issue by MaahiVaghela** [Kushal997-das/Project-Guidance#1467]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

It's beginners friendly and a good project to practice webdev

### Describe the solution you'd like.

I would like to work on this project. Please assign this issue to me.

**Comment by SakiraAli1115** [comment]
Hey I am the mentor of this project
@MaahiVaghela  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
