### ISSUE TITLE
The contributing, Project Admin, Engaging and Collaborating with, Stargazers over time 🤗🚀, Awesome contributors 🤩, These all are repeated two times in the documentation which creates confusion

### ISSUE THREAD

**Issue by Aayush2308** [Kushal997-das/Project-Guidance#1471]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Explain what you want to add/change in the documentation.

I read the whole README.md file of the repository. These parts of the document [The contributing, Project Admin, Engaging and Collaborating with, Stargazers over time 🤗🚀, Awesome contributors 🤩] are repeated two times in the README.md file which creates confusion for the new user to understand. So I will choose the best which fits and modify it for the user to simply understand about the repo and project. 
Please add the #hacktoberfest-accepted label 

Screenshots: 

![image](https://github.com/user-attachments/assets/a7d37321-f556-4031-8b20-bb1ad7cee95b)
As you can see after the "Awesome contributors 🤩" section, the contributing segment appears again and eventually all the segments repeats.

**Comment by Kushal997-das** [comment]
@Aayush2308 , thank you for your note. However, we have already fixed this issue. Please check our project, and feel free to create a new issue if needed.
