### ISSUE TITLE
Title: Add Wishlist App to web development section 

### ISSUE THREAD

**Issue by Arushi2S** [Kushal997-das/Project-Guidance#1472]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Its just an add on feature to widen your project spectrum. It will use css, html and javascript

### Describe the solution you'd like.

Addition of a wishlist app to basic of web development where a person could add or delete his/her wishes and mark done when achieved
![Screenshot (122)](https://github.com/user-attachments/assets/603a58f3-f2fa-481c-ad9d-d49ee0edb4e7)

**Comment by Arushi2S** [comment]
please assign me this issue

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@Arushi2S  Hello 
I appreciate your pull issue and thank you for your contribute!!!
@Kushal997-das kindly assign this issue!!

**Comment by Kushal997-das** [comment]
@Arushi2S, hello! I noticed that you opened the same issue in a different repository to gain points, which goes against the rules. If you would like to contribute to my project, please close your issue in that repository. Otherwise, I will have to mark it as spam.

**Comment by Arushi2S** [comment]
@Kushal997-das 
that repository was not participating
sir, actually this is my 1st time in open source 
I was not aware how to search for a participating repo
issue closed on that repository is closed please check and assign me

**Comment by Kushal997-das** [comment]
@Arushi2S Okey , make sure not to repeat this.

**Comment by Arushi2S** [comment]
noted

**Comment by Arushi2S** [comment]
sir I have submitted pr 
please check if its fine
also if you find it fair, please also add hactoberfest label to it
