### ISSUE TITLE
Title: Add Huffman Coding Project to Desktop Application/Intermediate/C++ for Learning Data Compression

### ISSUE THREAD

**Issue by PrasanBora** [Kushal997-das/Project-Guidance#1475]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

The current Desktop Application/Intermediate directory lacks projects that focus on efficient data compression algorithms
Huffman Coding is a widely used compression technique that is fundamental in data encoding
Adding this project would give users a chance to implement a real-world algorithm and strengthen their understanding of both C++ and data structures

### Describe the solution you'd like.

I would like to add a Huffman Coding project under the Desktop Application/Intermediate/C++ directory
This project will involve implementing the Huffman compression algorithm to encode and decode text files Through this, users will learn essential concepts like binary trees, priority queues and file I/O operations

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@PrasanBora Hello 
I appreciate your pull issue, can you give screenshots after update the output!!!

**Comment by PrasanBora** [comment]
![image](https://github.com/user-attachments/assets/e2f4a637-f953-4e56-9fdc-40e77ec8a126)
![image](https://github.com/user-attachments/assets/43624d8b-74e1-434d-8b19-55c2b374e185)

**Comment by Kushal997-das** [comment]
Hello @PrasanBora ,

Since you’ve already opened issue #1472  please allow that to be completed and merged before opening any new issues. We will be closing this current issue for now.

Thank you for your understanding!
