### ISSUE TITLE
Title: Memory block game

### ISSUE THREAD

**Issue by RahulScripted** [Kushal997-das/Project-Guidance#1483]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

I want to add a memory block game in web development basic section. here is a preview of game -
![Screenshot 2024-10-15 230300](https://github.com/user-attachments/assets/8159daf4-b9da-44a1-8d1c-3a44c911f089)

### Describe the solution you'd like.

My proposed solution is -

![Screenshot 2024-10-15 230300](https://github.com/user-attachments/assets/9c87a2d8-1202-419f-80ea-4223b42d5887)

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@RahulScripted Hello
I appreciate your pull issue !!!
@Kushal997-das kindly assign this issue!!!

**Comment by RahulScripted** [comment]
@SakiraAli1115 thank you 😊

**Comment by SakiraAli1115** [comment]
@RahulScripted Tell me where you can contribute?

**Comment by RahulScripted** [comment]
> @RahulScripted Tell me where you can contribute?

@SakiraAli1115 I want to contribute in web development section's basic part

**Comment by SakiraAli1115** [comment]
@RahulScripted Okay

**Comment by RahulScripted** [comment]
> @RahulScripted Okay

Please assign me under gsoc-extd lebel
