### ISSUE TITLE
Title: Add Spam detector under Machine learning projects

### ISSUE THREAD

**Issue by khushidadwal** [Kushal997-das/Project-Guidance#1484]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

I would like to add a project related to Spam text classifier under machine learning and data science.

### Describe the solution you'd like.

This project will predict the text data from different languages (English, German, French) as Spam or ham using a logistic regression model.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @khushidadwal 
I appreciate your pull issue, can you give screenshots after update the output!!!

**Comment by khushidadwal** [comment]
The following are the screenshots of the basic features and the final output of the model trained.
Please review and assign this issue to me.
Thanks :-)
![image](https://github.com/user-attachments/assets/c7dc1f6e-2d34-426f-8b29-5d70ed118859)
![image](https://github.com/user-attachments/assets/10aa880b-9aac-4e79-b0a8-64d07f4b4bd0)
