### ISSUE TITLE
Title: adding about section in quick link

### ISSUE THREAD

**Issue by harshpardeshi09** [Kushal997-das/Project-Guidance#1485]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

There is no any info related to project or about section added,  I will add about section in 'Project Guidance' project which will be visible in Quick link section.

### Describe the solution you'd like.

I will add about section in quick link menu which will give some info (about) of project.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-10-15 233618](https://github.com/user-attachments/assets/3019b43e-e86b-4a64-988c-84edf152414d)

**Comment by harshpardeshi09** [comment]
@Kushal997-das pls assign me this issue and label it

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@harshpardeshi09 Hello 
I appreciate your pull issue, can give screenshot after update the output.

**Comment by harshpardeshi09** [comment]
> I am the mentor of this project. @harshpardeshi09 Hello I appreciate your pull issue, can give screenshot after update the output.

@SakiraAli1115 Yes i will, immediately after completing the work

**Comment by harshpardeshi09** [comment]
Mentor @SakiraAli1115 can you pls help me with my issue, I'm unable to clone this project. Cloning just stops at 15%.
i tried many times recloning the repo but nothing changed

**Comment by SakiraAli1115** [comment]
@harshpardeshi09  Hello 
Do try again, because repo size too large!!

**Comment by harshpardeshi09** [comment]
> I am the mentor of this project. @harshpardeshi09 Hello I appreciate your pull issue, can give screenshot after update the output.

![Screenshot 2024-10-18 013832](https://github.com/user-attachments/assets/6915f0f5-29f2-4b1a-9fcd-c83c26001439)

@SakiraAli1115 i have added the about section, check the changes, review it  and assign issue to me with labels as i can PR it.

**Comment by SakiraAli1115** [comment]
Hello @harshpardeshi09 
It's not required.
@Kushal997-das kindly close this issue!
