### ISSUE TITLE
Title: Movie Recommendation system on the basis of emotion

### ISSUE THREAD

**Issue by Amanjayswal500** [Kushal997-das/Project-Guidance#1488]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Develop a movie recommendation system that suggests films based on users' emotions, detected via text

### Describe the solution you'd like.

Use NLP to analyze emotional cues and recommend relevant genres or films accordingly. And using web-scrapping suggest movie and also provide link of the movies.

### Add any other context or screenshots about the feature request here.

output screen
![Screenshot 2024-10-10 111234](https://github.com/user-attachments/assets/6401bc41-835b-4004-8ff9-c485bdd772ec)
 after clicking link

![Screenshot 2024-10-10 111310](https://github.com/user-attachments/assets/cb776a08-ae6c-4248-a67f-e6b2fa9a5c89)

**Comment by SakiraAli1115** [comment]
@Amanjayswal500 Hello  
Issue number #1412 already assign this issue ,then why are you open same issue again?
