### ISSUE TITLE
Title: add a tic-tac-toe game built using java with GUI too

### ISSUE THREAD

**Issue by amrutha-m206** [Kushal997-das/Project-Guidance#1491]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

It is not a  problem but just an addition , this game helps beginners in java to undertsand OOPs concepts and collections while building the project.

### Describe the solution you'd like.

The game helps beginners to get started with building basic simple projects with GUI interface . The whole project is completely done in java so that developers can get an understanding of how Java's utilization can be done.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project
@amrutha-m206  Hello Thank you for opening the pull issue and you can opening new issue by creating the new concept those are not exist in the project !!
@Kushal997-das kindly close the issue since it already exist in our project.
