### ISSUE TITLE
Title: Car Rental Website

### ISSUE THREAD

**Issue by RahulScripted** [Kushal997-das/Project-Guidance#1492]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

I want to add a project to the basic web development section. The Tech Stack used here is - HTML, CSS & JavaScript

### Describe the solution you'd like.

Here is the live view link of my website -

https://gilded-kelpie-4a2814.netlify.app/

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-10-16 204222](https://github.com/user-attachments/assets/d3e5d4cc-00f0-4526-b138-620d9d74eee2)

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@RahulScripted Hello
I appreciate your pull issue  and thank you for your contribute!!
Tell me where are you contribute?

**Comment by RahulScripted** [comment]
> I am the mentor of this project. @RahulScripted Hello I appreciate your pull issue and thank you for your contribute!! Tell me where are you contribute?

@SakiraAli1115 I want to contribute it in web development's basic section with gsoc-extd, hacktoberfest lebels

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue!!

**Comment by Kushal997-das** [comment]
@RahulScripted 

Hello, I noticed that a similar issue was created and merged in another repository, which goes against our guidelines. As a result, I have marked this issue as spam.

I can reference the specific PR for your awareness, but I prefer not to negatively impact your score.

Thank you for your understanding.

**Comment by Kushal997-das** [comment]
@RahulScripted FYR - https://github.com/iamrahulmahato/master-web-development/pull/1350

**Comment by RahulScripted** [comment]
> @RahulScripted FYR - [iamrahulmahato/master-web-development#1350](https://github.com/iamrahulmahato/master-web-development/pull/1350)

So it means I can't added same project into different respiratory it against guidelines?

**Comment by Kushal997-das** [comment]
Okey , no issue I’ll remove the spam tag since you new in this. But can’t proceed with the same project.

**Comment by RahulScripted** [comment]
> Okey , no issue I’ll remove the spam tag since you new in this. But can’t proceed with the same project.

Okay 👌 can I add different landing page I already made 4-5 other than these
