### ISSUE TITLE
Title: Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Kushal997-das/Project-Guidance#1496]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Explain what you want to add/change in the documentation.

The contributing.md looks is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @milansamuel609 
I appreciate your pull issue, can you give screenshots after update the output!!

**Comment by milansamuel609** [comment]
> I am the mentor of this project. Hello @milansamuel609 I appreciate your pull issue, can you give screenshots after update the output!!

Yes I will give screenshots also

**Comment by milansamuel609** [comment]
![image](https://github.com/user-attachments/assets/4bd78eec-4516-4401-9918-6300e2716dfc)

![image](https://github.com/user-attachments/assets/096d3fc6-7835-43e9-bf2c-8d595c4a7df4)

![image](https://github.com/user-attachments/assets/bc938b20-0531-4177-ac88-eb17c42000e6)

![image](https://github.com/user-attachments/assets/9be3561c-5e32-4614-b6a5-f40657061690)

These are the screenshot of the changes. If you like the changes please kindly assign me this issue and I will raise the PR.

**Comment by milansamuel609** [comment]
@Kushal997-das Please check the screenshots once if possible. If they are ok then please assign me this issue.

**Comment by SakiraAli1115** [comment]
@Kushal997-das kindly assign this issue!!

**Comment by milansamuel609** [comment]
> @Kushal997-das kindly assign this issue!!

🫠🫠🫠
