### ISSUE TITLE
Title: A gym website login page

### ISSUE THREAD

**Issue by amrutha-m206** [Kushal997-das/Project-Guidance#1497]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

A front-end only login page for a gym webiste which users can use to integrate with their backend
(for gssoc-ext and hacktoberfest)

### Describe the solution you'd like.

Front-end login page for a Gym admission website

**Comment by Kushal997-das** [comment]
@amrutha-m206 
Hello, I noticed that a similar issue was created in another repository, which goes against our guidelines. As a result, I have close this issue.

I can reference the specific issue for your awareness, but I prefer not to negatively impact your score.

Thank you for your understanding.
