### ISSUE TITLE
Broken Links in README Files

### ISSUE THREAD

**Issue by NimraAslamkhan** [Kushal997-das/Project-Guidance#1501]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### What happened?

I reviewed all the README files across the project and noticed that some of the links are not working correctly. 

### Urgency (Optional)

None

**Comment by NimraAslamkhan** [comment]
I'd like to contribute on this issue as I have thoroughly reviewed the README files and am familiar with their structure. I am confident I can efficiently identify and correct the broken links to improve the user experience

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
Hello @NimraAslamkhan 
I appreciate your pull issue, can you give screenshots after update the output!

**Comment by NimraAslamkhan** [comment]
![Screenshot_20241018-203209](https://github.com/user-attachments/assets/fa6e13b2-e506-491b-a104-3d5512c1c251)
![Screenshot_20241018-203215](https://github.com/user-attachments/assets/85fb95c2-821c-476d-a765-d574607ee472)
![Screenshot_20241018-203202](https://github.com/user-attachments/assets/b1b6b074-fcaf-423e-887f-5bbc8b12b9a9)
![Screenshot_20241018-203157](https://github.com/user-attachments/assets/1afd784c-1c1b-4658-a0e2-96a1c52079e0)
![Screenshot_20241018-203151](https://github.com/user-attachments/assets/6812fe3f-2fe6-4f1a-8870-5c5fb9a8f38d)
