### ISSUE TITLE
The contributing section in README.md file needs to be more precise and requires Guidelines

### ISSUE THREAD

**Issue by Aayush2308** [Kushal997-das/Project-Guidance#1502]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Explain what you want to add/change in the documentation.

The contributing segment needs more explanation and simpler instructions so that new users (beginners) don't face any difficulties. 
More screenshots and precise explanation is required to explain the steps. 
Also I would like to add guildelines of raising issues and creating pull requests that will have a maximum chance to get merged with the main branch for the new users who visits this repo so that maximum people can contribute to this project. 

Please add #hacktoberfest-accepted and #hacktoberfest   #level2 labels

**Comment by Aayush2308** [comment]
Please add labels #hacktoberfest-accepted #level2 #hacktoberfest labels

**Comment by Kushal997-das** [comment]
@Aayush2308 ,

Could you please provide a more detailed description of this issue? Additionally, it would be helpful if you could include some screenshots to help us better understand the situation.

Thank you!
