### ISSUE TITLE
Custom Issue Report Add ATS-SCORE-RECOGNIZER Project to Web Development Section

### ISSUE THREAD

**Issue by Baig-fatema** [Kushal997-das/Project-Guidance#1514]
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

Copy code
### Issue Title
Add ATS-SCORE-RECOGNIZER Project to Web Development Section

### Description
I would like to propose adding the **ATS-SCORE-RECOGNIZER** project to the web development section as an intermediate-level project.

### Project Overview
The ATS Score Recognizer is a tool designed to automatically extract and recognize scores from various documents, such as resumes and job applications. It leverages advanced optical character recognition (OCR) and machine learning techniques to streamline the recruitment process by providing accurate score extraction.

### Technologies Used
- **Python**: The core language used for development.
- **Flask/Django** (if applicable): For web framework.
- **OpenCV/Pytesseract** (if applicable): For OCR capabilities.
- **HTML/CSS/JavaScript**: For the frontend interface.

### Features
- **OCR Capabilities**: Utilizes state-of-the-art OCR to read text from images and PDFs.
- **Score Extraction**: Efficiently identifies and extracts relevant scores from documents.
- **User-Friendly Interface**: Easy-to-use interface for uploading documents and viewing results.
- **Multi-Format Support**: Works with multiple document formats including PDF, JPEG, and PNG.

### 🔍 Priority Level
- [ ] High
- [x] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [x] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [] ❄️ Script Winter of Code (SWoC)
- [] ⛄ Winter of Blockchain (WoB)
- [x] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### 💬 Next Steps:

You can expect a response within [4 days].

**Comment by Kushal997-das** [comment]
@Baig-fatema ,


Could you please provide a more detailed description of this issue? Additionally, it would be helpful if you could include some screenshots to help us better understand the situation.

Thank you!

**Comment by Baig-fatema** [comment]
@Kushal997-das  sure, below is the link of the Video of working features i request you to please review it.

**video Link :** [https://drive.google.com/file/d/1pDoSE2hDuK6KJKIuYFwsnTaH-RVQBA3i/view?usp=sharing](https://drive.google.com/file/d/1pDoSE2hDuK6KJKIuYFwsnTaH-RVQBA3i/view?usp=sharing)


  The use of this web page is you can upload your resume, your job description, and your CGPA/Percentage on the basis of that using various python Libraries like OCR and the more it convert the document into text and fetch your data, like projects, work experience , your contact details and many more and they are properly described in it or not.
than it will show you what is the score of you resume  between 0-100%.
It works as Professional ATS score recognizer which is the Current need of Market.

- I request you to please review it.
- Add GSSoC extd Label, Hacker to be fest Label.
- Add it to my Score board.

Thank you.

**Comment by Baig-fatema** [comment]
@Kushal997-das  please review this the above video link

**Comment by Baig-fatema** [comment]
@Kushal997-das  Please Review the above PR  i have also share the video link.

- Add gssos-extd label.
- Add level2 label.
- Add hacker to be fest label.

**Comment by Baig-fatema** [comment]
video Link : [https://drive.google.com/file/d/1pDoSE2hDuK6KJKIuYFwsnTaH-RVQBA3i/view?usp=sharing](https://drive.google.com/file/d/1pDoSE2hDuK6KJKIuYFwsnTaH-RVQBA3i/view?usp=sharing)
