### ISSUE TITLE
 Optimize particlesJS config and improve Back-To-Top button efficiency

### ISSUE THREAD

**Issue by Aayush2308** [Kushal997-das/Project-Guidance#1521]
### Initiative (Required)

Hacktoberfest 2024 🎃

### What happened?

This issue addresses several efficiency improvements in our particlesJS configuration and Back-To-Top button implementation. The current code includes unused configurations in the particlesJS setup, such as polygon and image properties in the shape object, and unused interaction modes (grab, bubble, remove). These can be safely removed without affecting functionality. The config_demo object also appears to be unused and can be eliminated. For the Back-To-Top button, the code can be optimized by moving the button variable declaration outside the scroll event listener, creating a separate handleScroll function, and using a ternary operator for concise display toggling. Adding the passive: true option to the scroll event listener will improve scroll performance. Additionally, using const for variables that aren't reassigned and removing unnecessary else clauses will enhance code clarity and efficiency. These changes will streamline our codebase, potentially improve performance, and maintain all existing functionality.

Please add labels #hacktoberfest-accepted, #hacktoberfest, #level3
Thank you !!

### Urgency (Optional)

None

**Comment by Aayush2308** [comment]
Please add labels #hacktoberfest-accepted, #hacktoberfest, #level3
Thank you !!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@Aayush2308  Hello 
I appreciate your pull  issue, can you give screenshot after update the output!
