### ISSUE TITLE
any issue you would recommend to clear for level 1

### ISSUE THREAD

**Issue by Dhruvi-tech** [Kushal997-das/Project-Guidance#1524]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@Dhruvi-tech Hello
I appreciate your pull issue, can you describe me and give screenshot after update the output!!

**Comment by Dhruvi-tech** [comment]
sure
