### ISSUE TITLE
Add contents to Intermediary folder of Blockchain Development

### ISSUE THREAD

**Issue by pradyumna14** [Kushal997-das/Project-Guidance#1525]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Explain what you want to add/change in the documentation.

I want to add well written contents on Blockchain on intermediary level like writing about: Events, Mapping, Structure and Array, etc.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@pradyumna14 Hello
I appreciate your pull issue, can you give screenshot after update the project!!
Thank you!

**Comment by pradyumna14** [comment]
@Kushal997-das 
@SakiraAli1115 
Please assign me this one

**Comment by pradyumna14** [comment]
@SakiraAli1115 
I have created a PR, please give me the appropriate level tag and a hacktober-fest accepted tag as well,
hoping for it to be merged,

Also please assign me the other issue, since i completed this one: https://github.com/Kushal997-das/Project-Guidance/issues/1526
Thank you
