### ISSUE TITLE
Title: Improving Footer UI Alignment and spacing

### ISSUE THREAD

**Issue by Raj-banerjee25** [Kushal997-das/Project-Guidance#1529]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

I have noticed a design inconsistency or opportunity for improvement in the footer section, as shown in the attached screenshot.
![iss1](https://github.com/user-attachments/assets/9fc9dc54-199e-4b62-9d93-bcc2ff6894ed)

### Describe the solution you'd like.

Improve spacing and alignment of the "Quick Links" section. Increase the visibility of social media icons, making them more balanced with the rest of the content.
I am willing to work on this please assign me

**Comment by PriyanshuValiya** [comment]
@Raj-banerjee25 Assign me this issue..

**Comment by charmi2109** [comment]
Can you please assign me this issue @Raj-banerjee25

**Comment by SakiraAli1115** [comment]
I am the  mentor of this project.
@Raj-banerjee25 Hello
 I appreciate your pull issue, but it is not required!
Kindly open new concept of pull issue..
Thank you!!
@Kushal997-das kindly close this issue!!!

**Comment by SakiraAli1115** [comment]
> Can you please assign me this issue @Raj-banerjee25

@charmi2109 Hello
Kindly create your own pull issue, if any problem then tell me!!
Thank you!

**Comment by SakiraAli1115** [comment]
> @Raj-banerjee25 Assign me this issue..

@PriyanshuValiya Hello
Kindly create your own pull issue, if any problem then tell me!!
Thank you!
