### ISSUE TITLE
Add GitHub Repository Stats to README.md

### ISSUE THREAD

**Issue by Ganeshmoorthii** [Kushal997-das/Project-Guidance#1530]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Description:
The issue involves adding a table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the `README.md` file. This will help contributors and users track the activity and contributions in the repository at a glance.

### Steps to Implement:
1. Create a table in the `README.md` file displaying the following repository statistics:
   - Stars
   - Forks
   - Open Issues
   - Open Pull Requests
   - Closed Pull Requests
2. Use markdown syntax to include badges or icons for each statistic, along with dynamic links to the corresponding sections of the repository.

### Expected Behavior:
The `README.md` file will contain a neatly formatted table that displays real-time repository statistics, making the repository's activity more visible and engaging for contributors and users.

### Additional Information:
- This enhancement will make the repository more user-friendly by providing visibility into its overall activity.
- The table can be dynamically updated by using GitHub shields or other badge services to fetch real-time stats.

### Screenshot (for reference):
![Screenshot 2024-10-20 145520](https://github.com/user-attachments/assets/9f6842ba-94f6-4654-a913-027b96488f27)

---

### Checklist:
- [x] I have checked the existing issues.
- [x] I have read the Contributing Guidelines.
- [x] I want to work on this issue.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@Ganeshmoorthii Hello
I appreciate your pull issue, can you give screenshot after update the output!!
Thank you!!

**Comment by Kushal997-das** [comment]
@Ganeshmoorthii It's already there .
