### ISSUE TITLE
Randomize Letter Points and Optimize Scoring Function

### ISSUE THREAD

**Issue by KashishJuneja101003** [Kushal997-das/Project-Guidance#1532]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

Current Code Issue:
The compute_score() function contains an unnecessary nested loop, which makes it less efficient.
The point system remains static, reducing the game's variability and excitement.

### Describe the solution you'd like.

To improve the game's functionality, I propose the following changes:

**Tasks:**
1. **Randomize Points for Each Letter:**
    - Replace the fixed point values for letters with a random point system where each letter has a different value on every game run.
    - Points should be randomized between 1 and 10 for every new game.
    - Use rand() to generate random values and srand(time(0)); to seed the random number generator.

2. **Optimize compute_score() Function:**
    - Eliminate the nested loop that checks each letter of the alphabet for every character in the word.
    - Use direct indexing to access the points for each character based on its ASCII value (c - 'a').

3. **Remove Unused Variables:**
    - Clean up any unused variables (such as t in the original code).

4. **Separate Score Calculation and Output:**
    - The compute_score() function should return the score, while the main program should handle printing the score for better separation of concerns.

5. **Additional Features:**
    - Optional: Add an option to display the randomized point values for testing purposes.

**Expected Outcome:**
- A more dynamic game where letter values are randomized every time it runs.
- More efficient scoring using direct access to letter points.
- Clean and maintainable code with unnecessary parts removed.

**Comment by KashishJuneja101003** [comment]
Kindly assign this issue to me under gssoc-ext and hactoberfest-accepted.
Thank You!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@KashishJuneja101003  Hello
I appreciate your pull issue, can you give working video, screenshot after update the output!!
Thank you!!

**Comment by Kushal997-das** [comment]
Hi @KashishJuneja101003, You've already created 2-3 issues and merged PRs under the hacktoberfest2024 and gssoc-ext events. We can only allow one issue or PR per participant, but in your case, we've already made an exception. Unfortunately, we cannot accommodate any further submissions. Thank you for your understanding!
