### ISSUE TITLE
Title: Adding new domain

### ISSUE THREAD

**Issue by NANDAGOPALNG** [Kushal997-das/Project-Guidance#1533]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

The project guidance is only limited to 6 domains where students who are searching for projects in different domains will face problem

### Describe the solution you'd like.

So lets create projects in new domains such as Blockchain, Generative AI, Cloud computing These branches are now being popularized among tech enthusiast and current market, so that your website can help more students

**Comment by Varshatm218** [comment]
Assign this to me under GSSoC-extd

**Comment by SakiraAli1115** [comment]
> Assign this to me under GSSoC-extd

I am the mentor of this project.
@Varshatm218 Hello kindly create your own issue, if any problem then tell me!!
Thank you

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@NANDAGOPALNG Hello 
I appreciate your pull issue, can you give screenshot after update the output and thank you for your contribute!!!

**Comment by Kushal997-das** [comment]
Thank you, @NANDAGOPALNG, for your input. We currently don't have a separate folder for blockchain, generative AI, and cloud computing, as they are already integrated. However, feel free to work on this issue.
