### ISSUE TITLE
Custom Issue Report : Add a more relatable background photos in domain names

### ISSUE THREAD

**Issue by PriyanshuValiya** [Kushal997-das/Project-Guidance#1534]
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 🔍 Priority Level
- [ ] High
- [x] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [ ] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### 💬 Next Steps:

You can expect a response within [X days].

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@PriyanshuValiya Hello
I appreciate your pull issue, can you give screenshot after update the output!!
Thank you for your contribute!

**Comment by PriyanshuValiya** [comment]
@SakiraAli1115 I will start work on it after assigning me this task, for example for web project there is a bitcoin background image, which is not relatable i will fix all background images in website.

**Comment by PriyanshuValiya** [comment]
@Kushal997-das  Please add gssoc-extd and level labels in that..

**Comment by Kushal997-das** [comment]
@PriyanshuValiya focus on issue when you open pr that time levels matter

**Comment by Meetpidev** [comment]
@Kushal997-das Requested to assign me this issue... i want to work on it...
