### ISSUE TITLE
Title: R program projects

### ISSUE THREAD

**Issue by SKG24** [Kushal997-das/Project-Guidance#1536]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

While Python is a versatile, general-purpose language with a broad application in data science, R’s strength lies in its specialized capabilities for statistical analysis and data visualization. I believe acquiring proficiency in R not only complements their Python skills but also equips them with powerful tools for in-depth statistical analysis and data interpretation, which are crucial in making data-driven decisions.

I think this repository should include multiple R program - data science related projects. This will help coding community.

### Describe the solution you'd like.

I have worked on few R projects, like insurance cost predictor, fraud detection and customer segmentation.

### Add any other context or screenshots about the feature request here.

I would like to contribute on this issue for Gssoc extended 24

Sanat Kumar Gupta
@SKG24

**Comment by SKG24** [comment]
Please respond
Thank you!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@SKG24 Hello
I appreciate your pull issue, can you give working video, screenshot after update the output!!
Thank you for your contribute!!

**Comment by SKG24** [comment]
https://github.com/user-attachments/assets/e80861b7-4ad5-4e27-9b18-bc9867c0088d


This is the project I worked to predict the cost of medical insurance. Main idea is to use R language and leverage its statistical tools to visualize and interpret the data and model predictions.

https://github.com/SKG24/Data_Science_mini_projects/tree/main/regressin_health_insurance

This is my personal repository to the project.

**Comment by SKG24** [comment]
![Uploading Screenshot 2024-10-23 at 10.22.08 PM.png…]()
![Screenshot 2024-10-23 at 10 22 16 PM](https://github.com/user-attachments/assets/3c497bb4-0e97-4d29-8d4a-f2ea09f13be4)
![Screenshot 2024-10-23 at 10 22 23 PM](https://github.com/user-attachments/assets/d8790f8d-d295-456b-b14a-dd636b690715)
![Screenshot 2024-10-23 at 10 22 30 PM](https://github.com/user-attachments/assets/017f4ddb-f082-439a-b701-80cb56d57999)

**Comment by SKG24** [comment]
I have one doubt. Should I push my work under machine learning and data science and create new folder in it specifically for R program or create new folder on main page named R program projects. I think since it is data science, I should work under ml and ds and create a folder specifically for it.

**Comment by SKG24** [comment]
Please update me in which folder I have to add. I am done with three projects on local device. I just need to pull request. And one more thing for each project do I have to create new PR?

**Comment by Kushal997-das** [comment]
Hi @SKG24,

Please note that only one project is allowed, and you've opened an issue for one project. To avoid confusion, let’s focus on submitting one project under the basic folder.

Thank you!

**Comment by SKG24** [comment]
Thank you so much for being cooperative with my work. If you feel I have a few more R projects to work on.
