### ISSUE TITLE
ENHANCEMENT| Redesign the landing page cards

### ISSUE THREAD

**Issue by shubhagarwal1** [Kushal997-das/Project-Guidance#1537]
<img width="1433" alt="Screenshot 2024-10-21 at 5 52 29 AM" src="https://github.com/user-attachments/assets/3f0e0c0d-9f7e-4c4f-8909-39f1446e684b">

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@shubhagarwal1 Hello
I appreciate your pull issue, can you give screenshot after update the output!!!
Thank you!!

**Comment by shubhagarwal1** [comment]
Hey, @SakiraAli1115, Sure i would love to work on te project, please assign me this task, i will start working on the porject then.

**Comment by shubhagarwal1** [comment]
> Hey, @SakiraAli1115, Sure i would love to work on te project, please assign me this task, i will start working on the porject then, as per gssoc guidlines i can work on issue only when it is assigned to me
