### ISSUE TITLE
Title: Addition of a maze solver 

### ISSUE THREAD

**Issue by Mahak-Agrawal-304** [Kushal997-das/Project-Guidance#1539]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your proposal related to a problem? Please describe.

I propose adding a basic AI project, i.e. a maze solver.

It will take input in .txt file and produce the output in .png file. It uses both bfs as well as dfs algorithms for an optimized solution. It will be a great project for a beginner level developer.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@Mahak-Agrawal-304 Hello 
I appreciate your pull issue , can you describe little bit and give working video, screenshots after update the output!!

**Comment by Mahak-Agrawal-304** [comment]
Hello @SakiraAli1115 , sure I'll share how inputs are taken and output is displayed. 

The basic logic behind this is the implementation of queues and stacks. With these implementations, we traverse the maze until we find the exit or target value. As for the output, the image is generated after the solution is found and automatically saved on your device.

A demo input in the form of .txt file:
![Screenshot (3094)](https://github.com/user-attachments/assets/103c5289-fe9c-4826-90ce-68feed133fdf)

The solution in the form of form of .png file for the above demo maze:
![Screenshot (3095)](https://github.com/user-attachments/assets/37bb9359-b28c-4814-8fe7-6732e1153de9)
Green node: Starting point
Red node: Exit/Target point
White node: All possible traversal points
Light red node: Traversed by the program but was not the correct path

(Cannot share working demo due to size issues)

**Comment by Kushal997-das** [comment]
@Mahak-Agrawal-304 Is this simple python program ?

**Comment by Mahak-Agrawal-304** [comment]
Yes @Kushal997-das , it's a beginner project I made when I began learning Artificial Intelligence

**Comment by Kushal997-das** [comment]
Hi @Mahak-Agrawal-304,

Please ensure that this is developed as a desktop application rather than a standard program. It should have the appearance of a complete project. I’m assigning this to you for now and will check in when you open the PR.

Thank you!
