### ISSUE TITLE
Title: Music Popularity Prediction using Machine Learning

### ISSUE THREAD

**Issue by neyhere07** [Kushal997-das/Project-Guidance#1540]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your proposal related to a problem? Please describe.

Music Popularity Prediction involves building machine learning models to estimate the popularity of tracks based on their audio features. Accurately predicting music popularity can assist streaming platforms in better understanding user preferences, optimizing playlists, and enhancing recommendation systems, ultimately boosting user engagement and satisfaction.

### Add any other context or screenshots about the proposal request here.

>Dataset used : [Dataset.csv](https://statso.io/music-popularity-case-study/)
<br>
<em>I would like to work on this issue. Kindly assign me under GSSoC, GSSoC Ext 2024 and Hacktoberfest 2024. Thank you!</em>

**Comment by INGEMINI** [comment]
I would like to work on this issue. Kindly assign me this task under  GSSoC Ext 2024  Thank you!

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@neyhere07 Hello
I appreciate your pull issue, Can you give working video , screenshot after update the output!!!

**Comment by SakiraAli1115** [comment]
> I would like to work on this issue. Kindly assign me this task under GSSoC Ext 2024 Thank you!

I am the mentor of this project.
@INGEMINI Hello Kindly create your own issue , if any problem then tell me !!!

**Comment by neyhere07** [comment]
# Below are the images of prediction :

- ### Relationship between each music feature and popularity : 

![popularityVSenergy](https://github.com/user-attachments/assets/bb46f69e-ede5-448e-8061-92fc4b7cf416)

![popularityVSvalence](https://github.com/user-attachments/assets/bdf53a10-2f53-4508-84dc-769c63fb228d)

![popularityVSdanceabilty](https://github.com/user-attachments/assets/c3ce1542-03f3-4e8a-8eb7-186898a086d1)

![popularityVSloudness](https://github.com/user-attachments/assets/81d97e6f-4df7-4be2-bda4-4ecd198679cb)

![popularityVSacousticness](https://github.com/user-attachments/assets/1c06f99f-8c81-49d0-afe7-980ed2323c75)


- ### Correlation Matrix : 

![correlation matrix](https://github.com/user-attachments/assets/03469733-49ff-4d1a-9061-2e06957aedbb)


- ### Distribution of all the music features :

![Distribution of Energy](https://github.com/user-attachments/assets/6ca77985-1767-41c9-b6aa-05e03039537c)

![Distribution of Valenece](https://github.com/user-attachments/assets/9dfd8d27-62d7-4acf-9860-72af3cf93f61)

![Distribution of Danceability](https://github.com/user-attachments/assets/e7dd3682-a6a4-4964-a482-81160d52d734)

![Distribution of Loudness](https://github.com/user-attachments/assets/96dec5e7-7fd9-4f3d-ac4b-0fe067f7a739)

![Distribution of Acousticness](https://github.com/user-attachments/assets/78794d58-e996-4a97-adb1-bbebf7931446)
<hr>

- ### Actual vs Predicted results of the test data:

![ActualVSpredictedPopularity](https://github.com/user-attachments/assets/f18aba10-21b4-4a33-af6c-cc41eeab8137)

The red line represents perfect predictions, where the predicted popularity exactly matches the actual popularity. Most points are clustered near this line, indicating that the model is making fairly accurate predictions.

**Comment by neyhere07** [comment]
@Kushal997-das Hello! I have a question, in which folder (Basic/ Intermediate/ Advanced) should I add?

**Comment by SakiraAli1115** [comment]
> @Kushal997-das Hello! I have a question, in which folder (Basic/ Intermediate/ Advanced) should I add?

Intermediate..
