### ISSUE TITLE
Title: I Want to add My project Image_Compression using K means 

### ISSUE THREAD

**Issue by sohailshk** [Kushal997-das/Project-Guidance#1543]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

Yes my issue solves thee problem of image compression which is widely used today and it helps person to select their own compression rate and custom cluster or color to compress selection.

### Describe the solution you'd like.

My notebook implements image_compression using kmeans from scratch and finally implemented it for image compression with custom cluster selection(like which color u want it to compress more) and can work on any image.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/5fbaa3f6-f5b9-4a5f-8e61-3f5df558cb01)

Please assign me this under hacktoberfest2024 and GSSOC 2024 -EXT.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@sohailshk Hello
I appreciate your issue and thank you for your contribute!!!
@Kushal997-das kindly assign this issue!!
