### ISSUE TITLE
Title: Cybersecurity Project Guide

### ISSUE THREAD

**Issue by jayadarshinig0609** [Kushal997-das/Project-Guidance#1547]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

The project guide repository lacks cybersecurity domain

### Describe the solution you'd like.

I would like to add cybersecurity project guide encompassing basic, intermediate and advanced levels for the budding cybersecurity enthusiasts to explore

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@jayadarshinig0609 Hello
I appreciate your issue, can you give working video, screenshot after update the output!!
Thank you!!

**Comment by jayadarshinig0609** [comment]
> I am the mentor of this project. @jayadarshinig0609 Hello I appreciate your issue, can you give working video, screenshot after update the output!! Thank you!!
Hi mam,
I would like to respectfully mention that no such things were attached for other domains mam.
