### ISSUE TITLE
feat: Loading Skeletons 

### ISSUE THREAD

**Issue by shubhagarwal1** [Kushal997-das/Project-Guidance#1556]

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@shubhagarwal1 Hello
I appreciate your issue, can you describe little bit and give screenshot after update the output!!
Thank you!!

**Comment by shubhagarwal1** [comment]
Hey @SakiraAli1115 thank you for considering the issue, as per gssoc guidelines i can only workon the issue after assignment, for ref you can see this 
<img width="419" alt="Screenshot 2024-10-25 at 8 23 58 PM" src="https://github.com/user-attachments/assets/1bc5f381-a428-43b0-b65b-19c42cdbddea">

**Comment by Kushal997-das** [comment]
Hi @shubhagarwal1,

I see that you have already opened one PR. It would be better to complete that first before moving on to this task. However, I’m assigning this to you because it’s a good catch that needs to be addressed.

Thank you!

**Comment by Kushal997-das** [comment]
Hi @shubhagarwal1,

It seems that @SakiraAli1115 is not just inquiring about the work but is requesting more details, such as screenshots and specifics about the issue. You can’t simply create an issue without following a professional approach. Additionally, creating multiple issues at once is inappropriate.

Let me close this for now, and let’s focus on finishing the assigned issues first.

Thank you!

**Comment by shubhagarwal1** [comment]
> Hi @shubhagarwal1,
> 
> It seems that @SakiraAli1115 is not just inquiring about the work but is requesting more details, such as screenshots and specifics about the issue. You can’t simply create an issue without following a professional approach. Additionally, creating multiple issues at once is inappropriate.
> 
> Let me close this for now, and let’s focus on finishing the assigned issues first.
> 
> Thank you!

Thank you for your message. The reason I opened multiple issues is that some take time to get assigned, and I wanted to ensure that any potential blockers were visible early. I’m fully committed to maintaining a high standard of code quality, and I’m confident I can manage these issues effectively.

Please let me know if there’s anything specific you'd like me to adjust in my approach.

Thank you!

Best regards,
Shubh
