### ISSUE TITLE
Title: Customer Churn Prediction

### ISSUE THREAD

**Issue by Stuti333** [Kushal997-das/Project-Guidance#1561]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

A customer churn predictor is essential to proactively identify customers likely to leave, enabling businesses to take targeted retention actions before losing valuable revenue. It helps companies optimize their retention budget by focusing efforts on high-risk customers while providing insights into common churn patterns and triggers.

### Describe the solution you'd like.

I would implement a solution comparing three algorithms: Random Forest, XGBoost , and Logistic Regression. The models would be trained on historical customer data  evaluating them using metrics like AUC-ROC and precision-recall curves to optimize for early churn detection.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/e84fae5f-3e17-4c11-b220-9bd3058adf34)
![{F5CB48E8-0F2B-42A9-8AF5-C7191D730182}](https://github.com/user-attachments/assets/ff33a419-76f6-4376-ad83-c0280582632e)

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@Stuti333 Hello
I appreciate your issue and thank you for your contribute!!!
@Kushal997-das Kindly assign this issue!!!
