### ISSUE TITLE
Title: [ FEATURE REQUEST ]: Adding Nav Bar To The Website 

### ISSUE THREAD

**Issue by GyanaPrakashSahoo7853** [Kushal997-das/Project-Guidance#1564]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

Navigation bar is missing in the top of the website . 

Screenshots

![Screenshot 2024-10-27 114039](https://github.com/user-attachments/assets/beee3d67-d654-481c-aefe-64570e5d6f71)

### Describe the solution you'd like.

I will be adding navigation bar with animation effect to it when someone hover on it. 

The navigation bar will contain HOME ABOUT DOMAINS and CONTACT 

Solution 

I have already designed the code and it looks like this 

https://github.com/user-attachments/assets/fbad5d7c-5968-4b0b-9594-6ca6af12b95a

**Comment by GyanaPrakashSahoo7853** [comment]
I would like to work on it 

@Kushal997-das can you please assign me this task with label hacktoberfest and gssoc-ext.

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@GyanaPrakashSahoo7853 Hello
I appreciate your issue and thank you for your contribute!!
@Kushal997-das kindly assign this issue!!

**Comment by Kushal997-das** [comment]
@GyanaPrakashSahoo7853, the navigation menu is already included, but it's not fully expanded in desktop mode. You can check it by clicking the hamburger icon. A solution would be to hide the hamburger menu in desktop mode and display the content instead, while ensuring that the hamburger menu is visible on mobile screens. Do lemme know if you upto for this.

**Comment by GyanaPrakashSahoo7853** [comment]
> @GyanaPrakashSahoo7853, the navigation menu is already included, but it's not fully expanded in desktop mode. You can check it by clicking the hamburger icon. A solution would be to hide the hamburger menu in desktop mode and display the content instead, while ensuring that the hamburger menu is visible on mobile screens. Do lemme know if you upto for this.

Should I add the hamburger menu again  and what about the navbar, is it ok ?

**Comment by GyanaPrakashSahoo7853** [comment]
@Kushal997-das  Can we please discuss about this in discord

**Comment by Kushal997-das** [comment]
> > @GyanaPrakashSahoo7853, the navigation menu is already included, but it's not fully expanded in desktop mode. You can check it by clicking the hamburger icon. A solution would be to hide the hamburger menu in desktop mode and display the content instead, while ensuring that the hamburger menu is visible on mobile screens. Do lemme know if you upto for this.
> 
> Should I add the hamburger menu again to the website or not and what about the navbar I have contributed, is my contribution worth it or not ?

Please read it what i said .
