### ISSUE TITLE
Title: Add Text Summarization Using Transformers 

### ISSUE THREAD

**Issue by NimraAslamkhan** [Kushal997-das/Project-Guidance#1565]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

The challenge of extracting concise and informative summaries from lengthy text documents presents a significant barrier to information accessibility. Traditional summarization methods often fail to capture essential details and coherence, making it difficult for users to quickly understand large volumes of text. The goal of this project is to leverage state-of-the-art transformer models, like BART, to automatically generate high-quality summaries that maintain the original document's meaning, improving efficiency and comprehension.

### Describe the solution you'd like.

The use of the BART model and the workflow involved. It highlights essential steps like data preprocessing, model implementation, and summary generation, ensuring alignment with project goals. Additionally, it notes the use of ROUGE metrics for evaluating summary quality, enhancing the depth of the solution.

### Add any other context or screenshots about the feature request here.

![Artical summary](https://github.com/user-attachments/assets/1cfc8667-4a6f-4fe0-96d8-44a6ff584794)

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@NimraAslamkhan  Hello
I appreciate your issue and thank you for your contribute!!!
@Kushal997-das kindly assign this issue!!
