### ISSUE TITLE
Title: I want to add the Tech Stack of the project in the documentation

### ISSUE THREAD

**Issue by NumlStudentSE** [Kushal997-das/Project-Guidance#1566]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Explain what you want to add/change in the documentation.

I want to add the tech stack of the project on the documentation 

![image](https://github.com/user-attachments/assets/269a11a7-648d-4e3b-8604-f1c9d4fee4ae)

Plz assign this issue to me @Kushal997-das

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@NumlStudentSE Hello
I appreciate your issue, Can you describe me and give working video or screenshot after update the output!!

Thank you!!!

**Comment by NumlStudentSE** [comment]
The documentation must include the 'Technology used' section which is missing now. So, I want to add the technologies that has been used to develop the project in the documentation.

![image](https://github.com/user-attachments/assets/14f18460-edfb-4f06-984f-e08462458c9c)


Plz assign this issue to me @SakiraAli1115

**Comment by Kushal997-das** [comment]
@NumlStudentSE, hello! In our project, we’re not limited to just a few technologies; we have a wide range of features. While it may not be possible to include everything, I welcome any additional suggestions you have. Please feel free to share them here!

**Comment by NumlStudentSE** [comment]
I want to add the dark and light mode toggle for the webpage 
Please assign this issue to me @Kushal997-das @SakiraAli1115
