### ISSUE TITLE
Title: Adding cursor following animation

### ISSUE THREAD

**Issue by amanver45** [Kushal997-das/Project-Guidance#1578]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Is your feature request related to a problem? Please describe.

I would like to add a cursor following animation and make it align with the website styling
Kindly assign this to me

### Describe the solution you'd like.

cursor

**Comment by Gursaranjotsingh** [comment]
I want to work on this. Please assign me this issue
