### ISSUE TITLE
Title:  Adjust Social Media Icon Size and Position in footer

### ISSUE THREAD

**Issue by khushi1315** [Kushal997-das/Project-Guidance#1582]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

The social media icons in the footer are quite small, making them less visible and potentially harder for users to interact with. Increasing their size to a medium level would improve visibility and accessibility, encouraging users to engage with the social media links.
Social Media Icon Position: Currently, the social media icons are located in the bottom right corner next to the line at the end of the footer. I propose moving these icons above the line to create a clearer separation and improve visibility.

### Describe the solution you'd like.

I would like to increase size of social media icons to a medium level and also, I would like to put those icons above line at the end of page.
Kindly assign me this work under gssoc and hacktoberfest with level of your choice.

### Add any other context or screenshots about the feature request here.

These icons are very small.
<img width="960" alt="Projecg Guidance footer" src="https://github.com/user-attachments/assets/dfee63fe-4537-46e4-af76-48ce084fc4e5">

**Comment by Kushal997-das** [comment]
@khushi1315 It's there already.
