### ISSUE TITLE
Title: Add Lung Cancer Risk Assesment

### ISSUE THREAD

**Issue by ananyag309** [Kushal997-das/Project-Guidance#1585]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Adding this project under Machine Learning.

### Describe the solution you'd like.

Able to predict the chances of lung cancer

**Comment by Kushal997-das** [comment]
@ananyag309 Multile issues nor allowed under same program.
