### ISSUE TITLE
Title: AI based Study assistant

### ISSUE THREAD

**Issue by ananyag309** [Kushal997-das/Project-Guidance#1588]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

This is an AI based study assistant.

### Describe the solution you'd like.

**Content Summarization**: Condenses study materials into key points for easier understanding.

**Quizzes and Flashcards**: Generates practice quizzes and flashcards for effective review.

**Comment by Kushal997-das** [comment]
@ananyag309 Kindly stop spamming .

**Comment by ananyag309** [comment]
@Kushal997-das i am extremely sorry, i thought they are automatically getting closed. can you please tell why they are being closed

**Comment by Kushal997-das** [comment]
Hi, you can’t send multiple issues under one program, as per my project
guidelines you can only add one project but in your case i gave second
chance. And yes now again you create another issue, if you keep spamming
like that I’ll close all ofcourse and make sure to remove all levels in
your merged PR.

**Comment by ananyag309** [comment]
@Kushal997-das okay, i didn't knew that i thought its 150 points for all repos
