### ISSUE TITLE
Title: Spelling issue in desktop applications(c++) file 

### ISSUE THREAD

**Issue by Pawnios** [Kushal997-das/Project-Guidance#1590]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Explain what you want to add/change in the documentation.

<img width="1371" alt="Screenshot 2024-10-30 at 7 42 09 PM" src="https://github.com/user-attachments/assets/7ddd76e6-e804-4f60-8988-075571642fa8">
 "Calendar" should be the correct spelling. 
Wrong spelling is written which may cause confusion in the future.
Can you assign me this issue?

**Comment by Scholarscribe** [comment]
@Pawnios Please add hactoberfest label to this issue.
