### ISSUE TITLE
Title: add chatbot integration to website

### ISSUE THREAD

**Issue by amanver45** [Kushal997-das/Project-Guidance#1593]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Add Chatbot Feature to Enhance User Experience

### Describe the solution you'd like.

Add Chatbot Feature to Enhance User Experience

**Comment by Kushal997-das** [comment]
@amanver45 Give more deatils with Screenshot

**Comment by amanver45** [comment]
@Kushal997-das  i use chatbase as  chatbot provider  which enchance user experience by helping to solve troubleshhot and give info about websoite i recently added a chaatbot to this gssoc projec you an check here https://agentgenesis.dev/

**Comment by Tanisha0708** [comment]
@amanver45  i would like to work on this plerase assign me this issue

**Comment by amanver45** [comment]
@Kushal997-das  can i work on this

**Comment by Kushal997-das** [comment]
@Tanisha0708 Since he created this issue, I have assigned it to him. If he doesn’t respond within 2 days with a PR or if his work doesn’t meet our expectations, I will likely reassign it to you. Thank you, @amanver45. Please handle this as soon as possible.
