### ISSUE TITLE
Title: Adding a Grammar AutoCorrector Model

### ISSUE THREAD

**Issue by Peart-Guy** [Kushal997-das/Project-Guidance#1613]
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

People often make grammatical mistakes while writing English texts. This Tool helps users to recheck if there is any grammatical error.

### Describe the solution you'd like.

I would like to add a NLP model of Grammar AutoCorrector

A grammar autocorrector model helps users write clearly and professionally by correcting errors instantly. It saves time, boosts confidence, and aids learning by showing suggested improvements.

**Comment by ipisitasahoo** [comment]
@ipisitasahoo assign me this issue
