### ISSUE TITLE
Contribute django todo list

### ISSUE THREAD

**Issue by Jordistyd** [Kushal997-das/Project-Guidance#162]
## 🚀 Feature

A to do list Webb app using tha django web frame.

I have read the contributing guidelines 

## Motivation

A chance to show my programming skills to others and add another functioning feature to the repo

## Pitch

This app is used in order to create a check list of assignments you have to do during your day,
All you need is to run the files and the webpage will open and guide you to your tasks

**Comment by Kushal997-das** [comment]
@Jordistyd I'll assign you for this 👍

**Comment by Jordistyd** [comment]
Awesome, I'll get to work and should have it for you in a couple of days :)

**Comment by asuzukosi** [comment]
@Jordistyd I also want to be part of this project

**Comment by Jordistyd** [comment]
@asuzukosi of course! I"ll upload the main code by tomorrow and tag you, feel free to contribute in any way
