### ISSUE TITLE
Add back-to-top scroll up button in readme

### ISSUE THREAD

**Issue by T-Fathima** [Kushal997-das/Project-Guidance#1629]
### Initiative (Required)

GSSoC (Girl Script Summer of Code) 🌸

### Explain what you want to add/change in the documentation.

This feature involves adding a Back-to-Top button to the README page which allows users to quickly scroll back to the top of the page with a single click.
It would look something like this:
![image](https://github.com/user-attachments/assets/6b07ba49-61da-44f6-8785-887ffeb1cc93)

@Kushal997-das I would like to work on it.
Please assign it to me.

**Comment by Kushal997-das** [comment]
@T-Fathima Tell me under which program are you contributing ?
