### ISSUE TITLE
Add Django music player

### ISSUE THREAD

**Issue by Jordistyd** [Kushal997-das/Project-Guidance#170]
## 🚀 Feature

I have built an intermediate django music app using Django, Boostrap, JS, css and html

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

I have read the contribution guidelines 

## Motivation

I wrote the app in order to get more practice using backend development in django

## Pitch

This feature would be great for any music lover to enjoy, and a great exercise for anyone who wants to add to it

**Comment by Kushal997-das** [comment]
@Jordistyd You can proceed.
