### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by UG-SEP** [Kushal997-das/Project-Guidance#178]
## 🚀 Feature

Form Validation is a project which helps you to check whether your form is correct according to some criteria

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?

Yes
## Motivation

To explore the difficulties and enjoyments of creating projects using JavaScript

## Pitch

It can be used to check whether your email id, password, name, age etc are correct or not to get used of it in future work

> Please assign me and add it under Hacktoberfeast don't forget to add the label

Related PR: #182

**Comment by SamarpanCoder2002** [comment]
> ## 🚀 Feature
> Form Validation is a project which helps you to check whether your form is correct according to some criteria
> 
> ### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?
> Yes
> 
> ## Motivation
> To explore the difficulties and enjoyments of creating projects using JavaScript
> 
> ## Pitch
> It can be used to check whether your email id, password, name, age etc are correct or not to get used of it in future work
> 
> > Please assign me and add it under Hacktoberfeast don't forget to add the label

Please make a pull request with replying in that issue @UG-SEP

**Comment by SamarpanCoder2002** [comment]
You are 7 commits behind the main. Please fetch it to make it even. @UG-SEP
