### ISSUE TITLE
Adding Three.js to get 3D effect in the JTM- project 

### ISSUE THREAD

**Issue by Jaideepgarlyal15** [Kushal997-das/Project-Guidance#183]
Hi, Jaideep Singh Garlyal I'm a contributor. My plan is to enhance the website by using Three.js to use 3D background. Which will look amazing and would be really interesting for the user and keep them **engaging with the 3D effect.**It will give the form a new 3D look. I would like to contribute to this issue. Please assign me this issue.

**Comment by Jaideepgarlyal15** [comment]
Sure sir will do accordingly, but the guidelines are not working it's showing an error. Thanks for assigning me the project.

**Comment by Kushal997-das** [comment]
[check now](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)

**Comment by Jaideepgarlyal15** [comment]
sure now it's working, so I'll read it and will start with the project accordingly.

**Comment by Kushal997-das** [comment]
It's been so long you are not responding to this issue so we are going to close the issue . Thank you :)
