### ISSUE TITLE
Add custom Spotify Landing Page Clone

### ISSUE THREAD

**Issue by abhilipsasahoo03** [Kushal997-das/Project-Guidance#184]
## 🚀 Feature

I'm Abhilipsa Sahoo and I'm a GSSOC'22 Contributor. I'd like to add a Spotify landing page clone under the Basic Web Development Category. 

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I have read the contribution guidelines. 

## Motivation

I built this project as a hands-on practice on HTML and CSS

## Pitch

Landing pages lead customers to a specific product, service or offer and encourage them to take action. This minimalistic landing page can encourage beginners to get a hands-on experience of HTML and CSS which they can later modify and use it for Spotify Clone App.

**Comment by Kushal997-das** [comment]
@abhilipsasahoo03 👍

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 👍 

Thank you so much. As per the rules, I'd be able to make a pull request only after 1st March, I guess?

**Comment by Kushal997-das** [comment]
Yeah @abhilipsasahoo03
