### ISSUE TITLE
 I'd like to add a snake-food game  under the Basic Flutter Developer Category.

### ISSUE THREAD

**Issue by Utk98** [Kushal997-das/Project-Guidance#185]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

## Motivation

To contribute ,and to learn something new that will help me in future

## Pitch

From childhood many of us played snake game in key-pad phones,and had a sweet memory.This will definitely motivate beginners to get a hands on experience in Dart and Flutter ,and gain experience to make more beneficial apps.

**Comment by Utk98** [comment]
Thankyou

**Comment by photon149** [comment]
@Utk98 Status of your Issue ?
I dont see any PR linked to same.

**Comment by Utk98** [comment]
I met with accident,parallel my exams are going onn..App was half made,after 2april I will resume rest of the work.

**Comment by Kushal997-das** [comment]
It's been so long you are not responding to this issue so we are going to close the issue . Thank you :)
