### ISSUE TITLE
Google keep Clone(GSSOC'22)

### ISSUE THREAD

**Issue by AsmitaPatil06** [Kushal997-das/Project-Guidance#186]
Hey, @Kushal997-das, I want to add Google keep Clone or WhatsApp using Angular(GSSOC'22). It is possible or I have to contribute only to the existing one?

**Comment by Kushal997-das** [comment]
@AsmitaPatil06 Yes you can!!

**Comment by Kushal997-das** [comment]
It's been so long you are not responding to this issue so we are going to close the issue . Thank you :)
