### ISSUE TITLE
I am Utkarsh Singh and participant of Gssoc2022.I would like to add Expense-Manager App. 

### ISSUE THREAD

**Issue by Utk98** [Kushal997-das/Project-Guidance#187]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

## Motivation

To contribute ,and to learn something new that will help me in future.

## Pitch

Many of us spend money but did not able to manage the expenses ,as a result we forget where we spend it.Hence I came with a solution to make app that save all your expenses,and it will add all expenses  and show as a graph .

**Comment by Kushal997-das** [comment]
@Utk98 :+1:

**Comment by Utk98** [comment]
Thank you so much. As per the rules, I would be able to make a pull request only after 1st March ?

**Comment by Kushal997-das** [comment]
yes @Utk98

**Comment by Kushal997-das** [comment]
It's been so long you are not responding to this issue so we are going to close the issue . Thank you :)
