### ISSUE TITLE
Calculator using GUI (PYTHON)

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Kushal997-das/Project-Guidance#188]
Hey, Greeting's of the day !!
(A clear and concise description of what the feature is.)
**I want to add Calculator to your repository made using GUI (Python)** i.e ..     Project-Guidance/Web Development/Basic/Calulator 
It can do basic arithmetic operation .     

Yeas i read all the contributing Guidelines ..
I would like to work on this under **GSSOC'22**
Please assign this to me .
Thank's regard .. :crossed_fingers: 
(Write your answer here.)

**Comment by Kushal997-das** [comment]
@Vikash-8090-Yadav Proceed 👍

**Comment by PeritusDeveloper** [comment]
I am GGSoc Contributor
I would also like to contribute on this.
