### ISSUE TITLE
Add Pocket Dictionary app using Flutter. [GSSOC'22]

### ISSUE THREAD

**Issue by vspr14** [Kushal997-das/Project-Guidance#189]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

To create an application to help readers follow their reading lists and learn how to make valuable contributions to the open source community 

## Pitch
People who are new to reading often let go of their desire to read quality works due to the difficult vocabulary. An application such as this allows the end user to keep track of the new words found in a book along with its meaning, either by entering the word or by scanning the book.

**Comment by Kushal997-das** [comment]
@vspr14 Proceed !
