### ISSUE TITLE
Generating Password and OTP in Java

### ISSUE THREAD

**Issue by abhi1e9-1e10** [Kushal997-das/Project-Guidance#190]
## 🚀 Feature

The feature explains how to generate such Passwords and OTP within no time and what code we can use if in case we need to do so.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

Many a time we forget our passwords and we opt for Forget password option and within no time we get a new password at our registered email-ID or phone no. to login our account. And every time we get a different password.
Sometimes we access our bank accounts while shopping from an online store or many more ways, in order to verify our transition from the bank account, they send us OTP(One Time Password) on our registered phone no. or our email-ID, within no time.

## Pitch

Below are the steps to generate a secure password:

Defined all the supported characters.
Get random two characters from a list of lowercase characters [a-z].
Get random two characters from a list of uppercase characters [A-Z].
Get random two characters from a list of digits [0-9].
Get random two characters from a list of special characters [!@#&...].
Get another random 12 characters from a list of supported characters (lowercase, uppercase, digit, and special characters).
Combine all the above 20 random characters.
Shuffle the result in step 7 to produce a random order.
This is the final secure password.

**Comment by biswajit150803** [comment]
I want to work on this issue

**Comment by Kushal997-das** [comment]
@abhi1e9-1e10 👍

**Comment by abhi1e9-1e10** [comment]
Hello Sir where can I place my project in your github...
means in which section

**Comment by photon149** [comment]
@abhi1e9-1e10 Place it under the Desktop Application Section.

**Comment by Kushal997-das** [comment]
It's been so long you are not responding to this issue so we are going to close the issue . Thank you :)
