### ISSUE TITLE
web dev

### ISSUE THREAD

**Issue by amir-ammar** [Kushal997-das/Project-Guidance#191]
## 🚀 Feature

adding full descriptive shopping website and all its details and the source code also
 

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ? 

yes

## Motivation

i want to add project for the seek of helping people to find more resources to practice on

**Comment by codervivek5** [comment]
I want to work on this issue under the Gssoc'22. plz assign me for the contribution.

**Comment by amir-ammar** [comment]
i will be using express in the backend and for the frontend simple background.
The aim of the project to develop the server side of it not the front end
@Kushal997-das

**Comment by Kushal997-das** [comment]
It's been so long you are not responding to this issue so we are going to close the issue . Thank you :)
