### ISSUE TITLE
Add DSA file in main code

### ISSUE THREAD

**Issue by varsha080** [Kushal997-das/Project-Guidance#198]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)
I have seen web development, app development files but I think we can add an DSA file which will contain basic data structures and algorithms associated to make this repository more informative. Kindly assign the task to me. I'm a 5 star code on hackerrank and 2 star on codechef. I have my skills in competitive programming.

**Comment by Kushal997-das** [comment]
@varsha080 Could you please be more specific ?

**Comment by Kushal997-das** [comment]
> ## 💥 Proposal
> (A clear and concise description of what the proposal is.)
> 
> ### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
> (Write your answer here.) I have seen web development, app development files but I think we can add an DSA file which will contain basic data structures and algorithms associated to make this repository more informative. Kindly assign the task to me. I'm a 5 star code on hackerrank and 2 star on codechef. I have my skills in competitive programming.

This repo. only contain projects 👍
