### ISSUE TITLE
CASESENSETIVE result in Guess The Word

### ISSUE THREAD

**Issue by Satyam26-09** [Kushal997-das/Project-Guidance#207]
## 🐛 Bug Report

In **GUESS THE WORD** project(Project-Guidance\Desktop Application\Basic\Python\Guess The Word) the output is showing "You are wrong" everytime (except when answer is given all in lowercase). I would love to fix this bug as my first open-source contribution.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Yes)

**Comment by LiQuiD-404** [comment]
I was already working on this issue @Kushal997-das

**Comment by LiQuiD-404** [comment]
I am sorry I know you are a beginner as well but I too am a beginner and I hardly can find issues in any projects. People have all taken up easy issues. I am sorry for doing this but maybe you can work on this? 
https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/Python/Story-Generator

**Comment by Satyam26-09** [comment]
no bro...no need to be sorry i should have seen first and thnx for the suggestion
