### ISSUE TITLE
Loan Approval Prediction 

### ISSUE THREAD

**Issue by shivam-s16** [Kushal997-das/Project-Guidance#227]
## 🚀 Feature

This feature will help people to have an idea about whether bank should approve loan or not. 

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

Help the bank to take decision.

**Comment by photon149** [comment]
@shivam-s16 status of your Issue ?
I dont see any PR linked to same.
