### ISSUE TITLE
Add Form Validation to Web Development section #GSSoC22

### ISSUE THREAD

**Issue by kriti242** [Kushal997-das/Project-Guidance#241]
## 🚀 Feature

To add a new project called "Form Validation" in [Basic_Web_Development](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development/Basic). It will use basic HTML, CSS, Bootstrap and JavaScript. Through this we will learn javascript basics to validate form fields.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes

## Motivation
HTML is the first step towards learning Web Development and HTML forms is one of the important topic. Forms are used every where and this makes Form Validation as one of the important topic a web developer should know. I wish to help people learn and understand how to validate their forms and where to show error messages and use them in their websites.

## Pitch
- Forms are used in almost every websites either as login form, registration forms, feedback forms or any other forms. 
- This form validation program performs form fields validation in real time i.e., when the user is entering the details. Most forms validate after clicking submit button, but validating while user is typing input saves users time and is efficient.
- In this, HTML, CSS, Bootstrap and JavaScript is used. Through this others can learn basics of JavaScript for validating.
- DEMO :
  
https://user-images.githubusercontent.com/61977671/156383652-666e599b-8078-4fb2-9abc-78746a0bb119.mp4

**Comment by 22chiragmodh** [comment]
I am GSSOC'22 open source contributor.
Please assign me for this issue.

**Comment by kriti242** [comment]
Please assign me this, I wish to add my form validation project to Project-Guidance for GSSoC'22

**Comment by kriti242** [comment]
I actually opened this issue so I can contribute to it

> I am GSSOC'22 open source contributor. Please assign me for this issue.

**Comment by 22chiragmodh** [comment]
I am not mentor @kriti242 so how i assign you

**Comment by kriti242** [comment]
> I am GSSOC'22 open source contributor. Please assign me for this issue.

I actually created this issue so I can do that to contribute for GSSoC

**Comment by kriti242** [comment]
> I am not mentor @kriti242 so how i assign you

Yeah I know I was not asking you, it was a general request

**Comment by kriti242** [comment]
> can i create new issue?

Have you read the Contributing Guidelines? In that its given how to create an issue and contribute to project. You can create an issue under Issues section by clicking on 'New Issue'.

**Comment by kriti242** [comment]
> can i create new issue?


Have you read the Contributing Guidelines? In that its given how to create an issue and contribute to project. You can create an issue under Issues section by clicking on 'New Issue'.
![image](https://user-images.githubusercontent.com/61977671/156409083-e8875821-de5c-4442-b2b5-7f80a0d3d9c7.png)

**Comment by Kushal997-das** [comment]
> can i create new issue?

Yes you can

**Comment by kriti242** [comment]
I will be adding the program files by tomorrow as few changes still need to be done. So please don't close this issue.
