### ISSUE TITLE
PAYMENT GATEWAY INTEGRATION

### ISSUE THREAD

**Issue by dexterousb** [Kushal997-das/Project-Guidance#242]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

## Motivation

Donation Money for rigour students, to help them achieve more success and education.

## Pitch

A simple elegant donation website where one can donate money , integration done using razor pay , with that the person donating the money will get a official email with receipt.

**Comment by Kushal997-das** [comment]
@photon149 Please check this ask the contributor to give more details because we already have same project .

**Comment by dexterousb** [comment]
My Project is a donation fundraising website to get money for NGO's using Razor pay integration , if this isnt yet added then please assign me to this request !

**Comment by photon149** [comment]
@dexterousb Mention the following details as well :
Tech Stack :
Level of Project : (basic /intermediate/advanced)
Features : 
Also , is the main highlight of the project is just the payment integration system ? If not , then I would also suggest to rename the Issue and give a more apt name for better understanding purposes.

**Comment by photon149** [comment]
@Kushal997-das please assign the issue to @dexterousb .

**Comment by Kushal997-das** [comment]
@dexterousb Proceed !

**Comment by dexterousb** [comment]
I have made the changes , kindly pull my request for the same!
