### ISSUE TITLE
New Project: Rock Paper Scissors Game 

### ISSUE THREAD

**Issue by LiQuiD-404** [Kushal997-das/Project-Guidance#257]
## 🚀 Feature

A Rock Paper Scissors Game built using Python.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I have read the complete contributing guidelines.

I will be working on this project under **GSSoC'22**
*Shubham Singh*

**Comment by Kushal997-das** [comment]
@LiQuiD-404 This project is already exits.

**Comment by LiQuiD-404** [comment]
Oh. I am sorry, I did not know about it. I will work on something else then.  👍
