### ISSUE TITLE
Online code Editor [Intermediate level] [ Web Development project] 

### ISSUE THREAD

**Issue by shivangi-pandey** [Kushal997-das/Project-Guidance#259]
## 🚀 Feature

Building an online code editor in React and start using it to edit your source code. All you enthusiastic frontend developers reading this, make sure to tick this off from your bucket list of react projects for beginners.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Pitch

There is no intermediate project in web development folder. Its an intermediate level project which will help many students in learning web dev and also in resume. 

Tech Stack= HTML, CSS, React

**Comment by prakhar3062** [comment]
@shivangi-pandey Nice idea. Go ahead make readme for your and make use of comments
