### ISSUE TITLE
Food recipe website

### ISSUE THREAD

**Issue by Adbnemesis** [Kushal997-das/Project-Guidance#265]
Adding a project called foodRecs which lets a user to post his/her food recipes and also review them

**Comment by Kushal997-das** [comment]
@Adbnemesis Add more details about your project .

**Comment by Adbnemesis** [comment]
It is a web based application for posting food recipes online, getting reviews and viewing other user's recipes. It doesnt have the authentication yet . It includes implementation of node.js and mongoDB along with elementary frontend.

**Comment by Kushal997-das** [comment]
@Adbnemesis Okey cool Go ahead !!
