### ISSUE TITLE
Adding issue forms for the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [Kushal997-das/Project-Guidance#276]
## 🚀 Feature

I want to add a few issue forms so that it will be convenient for new contributors to open issues.
There are already issue templates for this project but they are deprecated now, issue forms instead work way better. I plan to create  **Bug Report**, **Feature Request**, **Documentation** and **Proposal** forms.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes.

## Motivation

Issue forms enable contributors to describe the issue more conveniently than issue templates. They enhance the **user experience** and enable contributors to create an issue hassle-free.

## Pitch

This feature can save people's time and make it easier for them to create issues. That's why I think it will be a good enhancement to the repo.  You can read more about issue forms [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**Comment by Kushal997-das** [comment]
@MonarchGitHub These features are already exits , could you please be more specific what you exactly trying to do ?

**Comment by MonarchGitHub** [comment]
Hello, Actually there are no issue forms in the repo right now, there are only issue templates. These templates are deprecated whereas issue forms add functionality to the project.

**Comment by Kushal997-das** [comment]
@MonarchGitHub Okey go ahead and make a PR after that i'll see .

**Comment by MonarchGitHub** [comment]
Thanks, I'm on it.
