### ISSUE TITLE
Website for games - Minesweeper and Sudoku

### ISSUE THREAD

**Issue by batulr** [Kushal997-das/Project-Guidance#277]
## 🚀 Feature

I would like to create a responsive website for playing games like Minesweeper and Sudoku online.

I have clearly read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)

Tech Stack: HTML, CSS, Bootstrap, Javascript
Level: Basic - minesweeper, Intermediate - Sudoku
Main Highlight is the impressive UI and the features added to the games.

## Motivation

Playing games online is better such that no memory is used to store them on our device, which is one of the main reason that encourages me to work on this.
I would be obliged if this is assigned to me.

**Comment by batulr** [comment]
Thank you so much @Kushal997-das

**Comment by harsh-na** [comment]
I also want to work in this Minesweeper and Sudoku website with @batulr as i want to gain expeience in open source.
so can you assign me also this task @Kushal997-das

**Comment by Kushal997-das** [comment]
@harsh-na Ask her if she allows you then i can assign you as well . 

@batulr Are you gonna allow him to work with you ,if yes then lemme know by tagging me . Thank you :)

**Comment by batulr** [comment]
Sure, it would be great to have someone to work with @Kushal997-das . I would be glad if @harsh-na joins too.

**Comment by harsh-na** [comment]
@Kushal997-das  please assign me also.....as assignees are not yet updated

**Comment by harsh-na** [comment]
Thanks a lot @Kushal997-das

**Comment by batulr** [comment]
@harsh-na I have sent a request on discord, we can start discussing as soon as you accept the request.

**Comment by batulr** [comment]
@Kushal997-das I am ready with both the games, can you please guide me for adding a PR or the other steps?
