### ISSUE TITLE
Project Counting !!

### ISSUE THREAD

**Issue by Kushal997-das** [Kushal997-das/Project-Guidance#278]
**Update the project counting !!**

![InkedBug1_LI](https://user-images.githubusercontent.com/61356005/156700095-f4074d5d-cd56-400c-bdec-2ab7e56434c1.jpg)

**Comment by itsAftabAlam** [comment]
i want to work on this issue. can u assign it to me?

**Comment by itsAftabAlam** [comment]
@Kushal997-das  can you explain exactly what i have to do? i need to automate project counting? can u provide some resources also?

**Comment by Kushal997-das** [comment]
> @Kushal997-das can you explain exactly what i have to do? i need to automate project counting? can u provide some resources also?

I already described what to do , what you need to do just count the project and update the project number .

**Comment by itsAftabAlam** [comment]
> > @Kushal997-das can you explain exactly what i have to do? i need to automate project counting? can u provide some resources also?
> 
> I already described what to do , what you need to do just count the project and update the project number .

ok sure

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Kushal997-das** [comment]
> I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

You can make your own issue this issue is not belong to GSSoC22 .
