### ISSUE TITLE
income tax calculator

### ISSUE THREAD

**Issue by gaurijoshi22** [Kushal997-das/Project-Guidance#291]
This is a simple C program which is relatively efficient and can be used by any person who wants to calculate his income tax. 
This is really helpful for people who want to do multiple calculations.
I am gssoc'22 contributor.

Please assign me this task.

**Comment by gaurijoshi22** [comment]
Yes. It is beginner level project

**Comment by Kushal997-das** [comment]
> Yes. It is beginner level project

Proceed and make sure your give star to this repo. before fork ! Thank you :)
