### ISSUE TITLE
Color Code Converter

### ISSUE THREAD

**Issue by XZANATOL** [Kushal997-das/Project-Guidance#302]
## 🚀 Feature

Color Code Converter is a web page that converts from and to different color codes such as RGB, CMYK, Hsl, & Hex.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

## Motivation

A nice project to get one's hands dirty with solid JS principles such as functions and variables scope. It's also a good tool to convert between different color codes on haste.

## Pitch

It's an on-the-go project that converts between color code formats on haste with accurate values.

Issue created under GSSoC'22 contributions

**Comment by Kushal997-das** [comment]
@XZANATOL please Mention your issue belongs to GSSoC22.
