### ISSUE TITLE
ADD DONATION WEBSITE MODEL

### ISSUE THREAD

**Issue by Daksh-jha** [Kushal997-das/Project-Guidance#303]
## 💥 Proposal

A desktop website for donation, designed in html Css with little JS. It is just a design so that anyone can use the code if required anyway.
I am a GSSOC participant and wish to work under your project thus bringing this proposal.

**Comment by Kushal997-das** [comment]
@Daksh-jha proceed !

**Comment by Daksh-jha** [comment]
Thanks for assigning the issue ! I hope, I may meet your expectations.
