### ISSUE TITLE
To do list using Python

### ISSUE THREAD

**Issue by Khushi260** [Kushal997-das/Project-Guidance#306]
this is a simple to do list using python.

I'm GSSOC'22 participant.

**Comment by Kushal997-das** [comment]
@Khushi260 Can you please explain what tech. you are being used ?

**Comment by Kushal997-das** [comment]
@Khushi260

**Comment by Kushal997-das** [comment]
@Khushi260 It's been 15+  days you are not replying so i think you are not going to work on this project , so i assigned @mohanm18 for this .
