### ISSUE TITLE
Bug when the user enters a leap year in Desktop Application/Basic/C++/Calender

### ISSUE THREAD

**Issue by salahashraf253** [Kushal997-das/Project-Guidance#314]
## 🐛 Bug Report

When the user enters a leap year as 2020 , month 2 
this appears : 
![image](https://user-images.githubusercontent.com/73083810/156897560-b86bab1e-414b-4d40-863f-9e1a274dfa7f.png)

instead of this : 
![image](https://user-images.githubusercontent.com/73083810/156897538-c03d324b-c370-41ac-afb3-42cdcfdf1ad2.png)

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes , of course 
Give me a chance to contribute under GSSOC'22

**Comment by Kushal997-das** [comment]
@salahashraf253 Proceed !

**Comment by Kushal997-das** [comment]
@salahashraf253 Proceed and make sure your give star to this repo. before fork ! Thank you :)
