### ISSUE TITLE
Tic-tac toe online multiplayer

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Kushal997-das/Project-Guidance#315]
## 🚀 Feature

Intermediate web app that uses sockets to make connections between clients and plays the game.
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

GirlScript summer of code 2022

## Pitch

You can play tic tac toe with your friend

![image](https://user-images.githubusercontent.com/74463091/156898712-3750f5d6-bf0b-4fbe-9c72-7be672c4d4eb.png)

**Comment by Kushal997-das** [comment]
@sudip-mondal-2002 Proceed and make sure your give star to this repo. before fork ! Thank you :)

**Comment by sudip-mondal-2002** [comment]
@Kushal997-das https://github.com/Kushal997-das/Project-Guidance/pull/316
here is the pull request
