### ISSUE TITLE
Enhance navigation-bar and changes in feedback form

### ISSUE THREAD

**Issue by nandinijha2114001** [Kushal997-das/Project-Guidance#317]
Hi, I am a GSSOC 2022 contributor.
In the feedback form of Tourist Places project under web development section both the buttons are indicating "submit".
Also I would like to enhance the navigation bar for all pages like the logo is touching the bottom, it would look better in the middle and there should be space between ABOUTUS and CONTACTUS etc.

I am interested in contributing to your project, Kindly assign this issue to me.
![feedbackForm](https://user-images.githubusercontent.com/96972934/156912498-001fe8b6-4ed3-451a-bddb-ea9b7bc9fcfc.png)
.

**Comment by Kushal997-das** [comment]
@nandinijha2114001 Proceed and make sure your give star to this repo. before fork ! Thank you :)
