### ISSUE TITLE
Fix README.md files

### ISSUE THREAD

**Issue by rajdip-b** [Kushal997-das/Project-Guidance#321]
## 🐛 Bug Report

Many readme files contain the following issues.
- Broken or missing links
- Grammatical errors
- Incorrect ordering of tags

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

**Comment by rajdip-b** [comment]
Assign me this issue under GSSOC'22

**Comment by Kushal997-das** [comment]
@rajdip-b Proceed and make sure your give star to this repo. before fork ! Thank you :)
