### ISSUE TITLE
Landing Page of an ecommerce website

### ISSUE THREAD

**Issue by zehra47** [Kushal997-das/Project-Guidance#326]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Using basic html and css creating a landing page

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)
yes

**Comment by Kushal997-das** [comment]
@zehra47 Mention all technology!!

**Comment by zehra47** [comment]
I edited it . Should I create a new issue or is this ok ?

**Comment by Kushal997-das** [comment]
> @zehra47 Mention all technology!!

Reply on this !!
