### ISSUE TITLE
A pong game using python

### ISSUE THREAD

**Issue by zehra47** [Kushal997-das/Project-Guidance#328]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)
Yes

**Comment by Kushal997-das** [comment]
Proceed and make sure your give star to this repo. before fork ! Thank you :)
