### ISSUE TITLE
Ping pong game using python

### ISSUE THREAD

**Issue by mayank-del** [Kushal997-das/Project-Guidance#329]
## 🚀 Feature

It is ping pong game using python turtle graphics

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

Previous projects which were already added in this repo motivated me to request  this,

## Pitch

Since previous issues contain different games as well by different  languages , I thought  my ping-pong python game should  also present in this repo

**Comment by zehra47** [comment]
Can you please assign this to me
My project is ready, just have to add some documentation to it

**Comment by Kushal997-das** [comment]
Proceed and make sure your give star to this repo. before fork ! Thank you :)

@mayank-del Since someone else already raise an issue regarding this , so i gonna assign you as well, and when it comes to merge the PR we will see different factor and add only one project?.

**Comment by Kushal997-das** [comment]
> Can you please assign this to me My project is ready, just have to add some documentation to it

I already assigned you
