### ISSUE TITLE
NodeMailer

### ISSUE THREAD

**Issue by mayank-del** [Kushal997-das/Project-Guidance#330]
## 🚀 Feature

By this you can use node.js to mail from one person to another person

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

## Motivation

previous project motivated me to do this

## Pitch

Since it is a node project ,it  should be added in website Repo , It is almost important in each and every website

**Comment by Kushal997-das** [comment]
Proceed and make sure your give star to this repo. before fork ! Thank you :)
