### ISSUE TITLE
Motivator using python

### ISSUE THREAD

**Issue by lovishprabhakar** [Kushal997-das/Project-Guidance#340]
## 🚀 Feature

A python project that fetches motivational quotes from the internet and plays them.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

This was the project for my first hackathon in university.

## Pitch

Just a beginner level project that motivates you.

**Comment by FatimahAdwan** [comment]
Hi, pls I would like to work on this

**Comment by FatimahAdwan** [comment]
Hi, i would like to work on this

**Comment by FatimahAdwan** [comment]
could you assign this to me and also help with some useful materials *smiles*. thanks

**Comment by lovishprabhakar** [comment]
@Kushal997-das sir why did you remove the GSSoC22 label?

**Comment by lovishprabhakar** [comment]
@Kushal997-das sir I have solved the issue and created a PR #375. Kindly review.
