### ISSUE TITLE
BMI Calculator App

### ISSUE THREAD

**Issue by SomyaRanjanSahu** [Kushal997-das/Project-Guidance#341]
## 🚀 Feature

BMI Calculator is a basic level app development project that helps an individual to calculate his/her body mass index with just a few taps.

First of all the person has to select his/her gender and then set the height, weight, and age. Then after tapping on calculate button the result(BMI) is shown. It also gives feedback based on the result obtained.

Tools used: Flutter(2.8.1), Dart
![1](https://user-images.githubusercontent.com/63153316/157068059-f041e063-b59c-417d-b063-0f35c3bb4aa7.png)

Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?
Yes

**Comment by SomyaRanjanSahu** [comment]
@Kushal997-das please assign this issue to me under GSSoC'22

**Comment by Kushal997-das** [comment]
@SomyaRanjanSahu 👍
