### ISSUE TITLE
Snake game using HTML, CSS and JS

### ISSUE THREAD

**Issue by Rashmisingh-18** [Kushal997-das/Project-Guidance#342]
You can check by going through the website: https://snake-game-five-cyan.vercel.app/

**Comment by Rashmisingh-18** [comment]
Please assign this issue to me @Kushal997-das

**Comment by Kushal997-das** [comment]
@Rashmisingh-18 Done !

**Comment by Rashmisingh-18** [comment]
Added Snake Game #367.
