### ISSUE TITLE
New Simple Project - STICKY NOTES 

### ISSUE THREAD

**Issue by isha614** [Kushal997-das/Project-Guidance#343]
## 🚀 Feature
A simple project using HTML, CSS, JavaScript which allows users to add their to-dos , and  they can delete one when done with their task.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes
## Pitch
Useful for people, they can add the task and delete it on completion.

**Comment by Pranjali-49** [comment]
Hello, I want to work on this issue under GSSOC'22. Please assign me this issue.

**Comment by Kushal997-das** [comment]
> Hello, I want to work on this issue under GSSOC'22. Please assign me this issue.

If @isha614 allows you to do so you can work with her .

@isha614 ?

**Comment by isha614** [comment]
> > Hello, I want to work on this issue under GSSOC'22. Please assign me this issue.
> 
> If @isha614 allows you to do so you can work with her .
> 
> @isha614 ?
I want to work on it
So, Please assign to me.

**Comment by Kushal997-das** [comment]
@isha614 👍
