### ISSUE TITLE
Improvement of the code in Credit Card Checker project 

### ISSUE THREAD

**Issue by salahashraf253** [Kushal997-das/Project-Guidance#345]
## 💥 Proposal
I will modify the code to be more clean and maintable
Project : https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/C%2B%2B/Credit%20Card%20Checker 

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(sure.)

Give me a chance to contribute under GSSOC'22

**Comment by Kushal997-das** [comment]
@salahashraf253 Proceed!
