### ISSUE TITLE
Customer review webapp

### ISSUE THREAD

**Issue by XZANATOL** [Kushal997-das/Project-Guidance#349]
## 🚀 Feature

A Flask based app that provides a form for the user to upload a feedback/review about a current product, it then saves the reviews in a CSV file with the help of pandas library.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

## Motivation

The project demonstrates the raw idea of how feedback forms work. in addition to explaining some concepts of different python libraries such as wtforms, Pandas, and Flask.

## Pitch

It's a good startup app for those who are new to Flask and want to get their hands wet with it.

Issue created under GSSoC'22 contributions.

**Comment by Kushal997-das** [comment]
@XZANATOL If you don't mentioned that you are a contributor of GSSoC22 then i gonna not add level of it .

**Comment by XZANATOL** [comment]
@Kushal997-das I've updated the issue body and mentioned I'm a GSSoC'22 contributor
