### ISSUE TITLE
Title: Enhancement in the project CALENDER.

### ISSUE THREAD

**Issue by Satyam26-09** [Kushal997-das/Project-Guidance#355]
### Is your proposal related to a problem? Please describe.

I would like to work in the quality of the code of project **CALENDER**. https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/C%2B%2B/Calender

**Comment by Kushal997-das** [comment]
@Satyam26-09 Please mention what exactly you want to change be specific .

**Comment by Satyam26-09** [comment]
@Kushal997-das I'll modify it as:
- program will end when user input is negative in year as the program not work for negative years.
- I can restrict the upper bound in years too...as you specify. 
- program will re-prompt for month again if user input is not between 1-12.

**Comment by Satyam26-09** [comment]
@Kushal997-das  can you assign me this??

**Comment by Satyam26-09** [comment]
@Kushal997-das need your comment on this...

**Comment by Kushal997-das** [comment]
@Satyam26-09
