### ISSUE TITLE
Add a set of glowing icons with hover effect

### ISSUE THREAD

**Issue by srinjoy-26** [Kushal997-das/Project-Guidance#356]
### Is your feature request related to a problem? Please describe.

I want to add a new project.

### Describe the solution you'd like.

The project is created purely using CSS. It consists of some icons with glowing + hover effect.

### Describe alternatives you've considered.

i haven't thought of alternatives yet.

### Add any other context or screenshots about the feature request here.

<img width="960" alt="icon" src="https://user-images.githubusercontent.com/91176055/157295196-c9114cb6-f53a-4afc-aafb-757ebafd2419.png">

**Comment by photon149** [comment]
@srinjoy-26 status of your Issue ?
