### ISSUE TITLE
Title: Desktop clock application added(python)

### ISSUE THREAD

**Issue by Ash-KODES** [Kushal997-das/Project-Guidance#360]
### Explain what you want to add/change in documentation.

Desktop clock application 
Techstack-Python
library used-Time module of python
program-GsSOC2022

**Comment by Kushal997-das** [comment]
@Ash-KODES Add more details about your project .

**Comment by Kushal997-das** [comment]
@Ash-KODES Add more details about your project like what technology you are being used in this project etc.

**Comment by Ash-KODES** [comment]
> ### Explain what you want to add/change in documentation.
> Desktop clock application Techstack-Python library used-Time module of python program-GsSOC2022

is it enough sir?

**Comment by Kushal997-das** [comment]
@Ash-KODES Okey ! But you have to create another PR .

**Comment by Ash-KODES** [comment]
> @Ash-KODES Okey ! But you have to create another PR .

Done :)
