### ISSUE TITLE
Title: Chat Application Using Django

### ISSUE THREAD

**Issue by Monalisa-2000** [Kushal997-das/Project-Guidance#361]
Web-based Chat application using Django framework and python backend.

Have you read the Contributing Guidelines?
Yes

Pitch
Just an advanced-level project that helps to build a social network.

**Comment by Monalisa-2000** [comment]
Sir, till this monday I'll be submitting it here... Just more 2days?

**Comment by Kushal997-das** [comment]
Please send the PR before EOD monday else we will close this up.

**Comment by Monalisa-2000** [comment]
Sure by the EOD of the Monday(today)before 12am I'll be sending it ....
Thank you for reopening it.

**Comment by Monalisa-2000** [comment]
Please sir just for today open it? Else the time I've given to complete the project that'll be gonna waste plz do understand as I mentioned yesterday itself I have finished with my exams... Plz

**Comment by Kushal997-das** [comment]
Send the PR by EOD , i already gave you enough time to complete the project .

**NOTE** : _Today is the last date_
