### ISSUE TITLE
Adding Parallex Web Design Using HTML,CSS

### ISSUE THREAD

**Issue by rajprem4214** [Kushal997-das/Project-Guidance#364]
### Is your feature request related to a problem? Please describe.

A website that showcases Parallex Web Design

### Describe the solution you'd like.

A website that works on parallex design effect on basis of css and scroll trigger

### Describe alternatives you've considered.

No alternatives

**Comment by Kushal997-das** [comment]
@rajprem4214 One issue at a time !
