### ISSUE TITLE
Contribute your code to Open source.

### ISSUE THREAD

**Issue by Kushal997-das** [Kushal997-das/Project-Guidance#37]
If you have any project **doesn't matter **small or big**** you can easily contribute your project in this repo.
Make sure you follow the all the required guidelines.
For more info contact me _@Kushal997-das_

**Comment by smv1999** [comment]
I would like to contribute a project to this repo. Please assign me @Kushal997-das .

**Comment by Kushal997-das** [comment]
> I would like to contribute a project to this repo. Please assign me @Kushal997-das .

Yeah sure you can contribute .
Make sure you follow all 5the guidelines :)

**Comment by TawfikYasser** [comment]
Hi, I have a good console applications using Java and C++
Can i add them as a beginner ?!
Thanks

**Comment by SamarpanCoder2002** [comment]
Yes..you can do it....Please follow our all 5 guidelines...

**Comment by TawfikYasser** [comment]
Okay, For console applications which folder is appropriate, Please?

**Comment by SamarpanCoder2002** [comment]
Is your project made with both Java and C++????

**Comment by TawfikYasser** [comment]
I have some projects with java, Other projects with C++

**Comment by SamarpanCoder2002** [comment]
oh, nice...First, ensure that...your project is which type? 
1. Beginner
2. Intermediate
3. Advanced
(I think your projects are desktop applications...So find the above three folders under desktop applications)
After predicting this, make a programming language-specific folder in the above-mentioned folder if that kind of programming language folder is not present, and then added your projects in that particular folder.

For more information, please read the Code of Conduct file of that repo...I think it will clear to you...
Thank you for your attention.....

**Comment by TawfikYasser** [comment]
Thanks for your time

It is clear for me now

I will open an issue now, Then open and PR.

**Comment by SamarpanCoder2002** [comment]
Waiting for your pull request

**Comment by 96RadhikaJadhav** [comment]
@Kushal997-das @SamarpanCoder2002  I also want to add beginner level javascript projects. Can I work on it?

**Comment by Kushal997-das** [comment]
> @Kushal997-das @SamarpanCoder2002 I also want to add beginner level javascript projects. Can I work on it?

@96RadhikaJadhav Yes ofcourse you can .Make sure you follow our guidelines.

**Comment by TawfikYasser** [comment]
Hi @96RadhikaJadhav  you can add your project by following the contributing rules -> [Here](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)
* Ask for anything
* Good luck

**Comment by TawfikYasser** [comment]
Hello @Kushal997-das  What is your opinion about creating an organization. To help the developers in a big scale.

**Comment by Kushal997-das** [comment]
> Hello @Kushal997-das What is your opinion about creating an organization. To help the developers in a big scale.

We already thought that @TawfikYasser Soon we will create an organization .  Just need more people to contribute to this project . Tell your friends to do contribute :)

**Comment by TawfikYasser** [comment]
> > Hello @Kushal997-das What is your opinion about creating an organization. To help the developers in a big scale.
> 
> We already thought that @TawfikYasser Soon we will create an organization . Just need more people to contribute to this project . Tell your friends to do contribute :)

Great, I will tell my friends and I have more projects I will add them consecutively,
I wish to be on of this great organization.

**Comment by Rutikab12** [comment]
Hey can i contribute beginner pycharm and web development projects to this repo?. And in which folder should i contribute pycharm projects.?

**Comment by TawfikYasser** [comment]
Hi @96RadhikaJadhav , Sure you can contribute which is a great thing to do

If you want to add a web project you can add to [this](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development) directory
and for desktop application [here](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application) you can add the tkinter project for example

Take care of the project programming language folder and follow the repo [contribution rules](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)

Have a nice time :)

**Comment by Sristi27** [comment]
Hello @Kushal997-das ,I want to add a Javascript project which is beginner friendly.Can I do so?

**Comment by Kushal997-das** [comment]
> Hello @Kushal997-das ,I want to add a Javascript project which is beginner friendly.Can I do so?

Yeah sure please create an issue and mention your project name and description . Happy contribution @Sristi27

**Comment by 96RadhikaJadhav** [comment]
> > @Kushal997-das @SamarpanCoder2002 I also want to add beginner level javascript projects. Can I work on it?
> 
> @96RadhikaJadhav Yes ofcourse you can .Make sure you follow our guidelines.

I tried opening an issue and then creating a PR but submit issue button was disabled so I couldn't do that. I created a PR #146 . Could you please review it.

**Comment by Kushal997-das** [comment]
> > > @Kushal997-das @SamarpanCoder2002 I also want to add beginner level javascript projects. Can I work on it?
> > 
> > 
> > @96RadhikaJadhav Yes ofcourse you can .Make sure you follow our guidelines.
> 
> I tried opening an issue and then creating a PR but submit issue button was disabled so I couldn't do that. I created a PR #146 . Could you please review it.

Hi @96RadhikaJadhav i check and found some bug over your PR please check [this](https://github.com/Kushal997-das/Project-Guidance/pull/146) out.

**Comment by Isha307** [comment]
@Kushal997-das @SamarpanCoder2002  Please check #150.

**Comment by Jordistyd** [comment]
Hi,
I wrote a Webb App to do list in python using django,
A beginner project that I would love to contribute to the repo, please let me know if I can upload it :)

**Comment by AyushJain001** [comment]
I have a project to add it in python .Please assign me.

**Comment by Ajoe12** [comment]
Please assign me, I had created google keep clone web application can I add it in the basic web development

**Comment by thisisharsh7** [comment]
Hello sir, @Kushal997-das 
I have a password storing project build by C++;
Will you please assign it to me?

**Comment by TadrupDas** [comment]
Hello @Kushal997-das , i would like to contribute a weather report website here using Html,css,javascript . Could you please assign it to me?
Tadrup Das
GSSOC'22 Contributor

**Comment by vickyrules** [comment]
I would like to contribute some python projects  (Basic to intermidiate levels).
Please allow me to add those nice projects..
