### ISSUE TITLE
Add a Quiz app

### ISSUE THREAD

**Issue by Anchita15** [Kushal997-das/Project-Guidance#372]
### Is your feature request related to a problem? Please describe.

I have made a very user friendly quiz app.

### Describe the solution you'd like.

Live: https://anchita15.github.io/QuizApp/

### Describe alternatives you've considered.

This is responsive.
This is made using JavaScript, HTML and CSS.

### Add any other context or screenshots about the feature request here.

<img width="959" alt="quiz app ss1" src="https://user-images.githubusercontent.com/83870242/157410445-7aed839f-1aed-4757-8ff4-87640551af05.png">
<img width="955" alt="quiz app ss2" src="https://user-images.githubusercontent.com/83870242/157410454-04cd1d23-31e7-4558-abdd-6b2da5937c69.png">

**Comment by Kushal997-das** [comment]
@Anchita15 Proceed !
