### ISSUE TITLE
Title: add a new feature in currency convertor project as part of GSSoC'22

### ISSUE THREAD

**Issue by salahashraf253** [Kushal997-das/Project-Guidance#379]
### Is your feature request related to a problem? Please describe.

no 

### Describe the solution you'd like.

I want to switch button to switch the currency instead of changing it manually.
project link : https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/Java/currency-converter

### Describe alternatives you've considered.

![image](https://user-images.githubusercontent.com/73083810/157517100-596ce72e-5471-4854-9bc0-fd86e43bceb8.png)

the switch button that I will develop it 

### Add any other context or screenshots about the feature request here.

I am participating in gssoc'22. please assign this to me.

**Comment by Kushal997-das** [comment]
@salahashraf253 👍
