### ISSUE TITLE
Add a java console application

### ISSUE THREAD

**Issue by TawfikYasser** [Kushal997-das/Project-Guidance#39]
Hi

I’m new to open source and I want to help the community,
So I have a good java console application to simulate the CPU Scheduler for the following alogrithms:
* Shortest Job First
* Priority Scheduling
* Round Robin
* Multi-Level Queue

I wish to make this repository more good.

**Comment by SamarpanCoder2002** [comment]
Please add your projects in Project-Guidance following the 5 rules in the 'Code of Conduct' File under project guidance....Make sure that you must follow that rules to add your projects to a particular folder in a specific location...Thank you for your interest..

**Comment by TawfikYasser** [comment]
I opened a pull request successfully.

**Comment by SamarpanCoder2002** [comment]
https://github.com/Kushal997-das/Project-Guidance/pull/40#issuecomment-765205891

**Comment by TawfikYasser** [comment]
The project added from PR #40 
Thanks
