### ISSUE TITLE
make some grammatical correction to the contributing.md

### ISSUE THREAD

**Issue by FatimahAdwan** [Kushal997-das/Project-Guidance#396]
### Is your proposal related to a problem? Please describe.

I noticed some grammatical errors while reading the contributing.md which got me a little bit confused at first, I feel I could correct them

from gssoc, you cold assign it to me as well

**Comment by mohanm18** [comment]
Hey 👋🏼@FatimahAdwan sorry for the interruption, but are you still working on this issue?
If you don't have any problem can I ask the project owner to assign the issue to me?
Btw I'm also a **GSSoC 2022** participant(contributor).

**Comment by FatimahAdwan** [comment]
> Hey 👋🏼@FatimahAdwan sorry for the interruption, but are you still working on this issue? If you don't have any problem can I ask the project owner to assign the issue to me? Btw I'm also a **GSSoC 2022** participant(contributor).

Hey, am done with it since, my system needs to be fixed that's why I haven't committed yet. It's done already, will push it soon.
