### ISSUE TITLE
Markov Chain Text Composer

### ISSUE THREAD

**Issue by FatimahAdwan** [Kushal997-das/Project-Guidance#409]
a simple markov chain text composer which is an  Implementation of a predictive text generator using Markov chains.

am from GSSOC, pls assign this to me

**Comment by photon149** [comment]
@FatimahAdwan status of your issue ?

**Comment by FatimahAdwan** [comment]
> @FatimahAdwan status of your issue ?

Hi Kushal, I encountered an issue while pushing to GitHub, dropped the problem I encountered in the discord group channel for help from the mentors , but no one answered me yet, am still trying my way around it to see if I can solve it. you can as well help me out, I dropped a screen shot in the group, pls do have a look so that I can quickly meet up too. thank you

**Comment by FatimahAdwan** [comment]
> @FatimahAdwan Don't worry we are here to help you . Please confirm did you fork this repo ?

yes i did

**Comment by Kushal997-das** [comment]
@FatimahAdwan Please fetch all the updates from the original repo .

**Comment by FatimahAdwan** [comment]
> @FatimahAdwan Please fetch all the updates from the original repo .

 i have done that. 
i also wanted to ask if i delete it from my local machine and clone it again, what will happen, cause i have a pending changes with another pull request and again, the initial push i made for the grammatical changes issues is already pushed to my remote git, so what do you think will happen to all this when i delete the whole project Guidance repo from my local machine and clone it again?

**Comment by Kushal997-das** [comment]
Yes you can delete the whole `project-guidance` folder from you local but make sure what you have made changes in local before delete the `Project-guidance` whole folder you can copy those changes in your other local folder and save there . Then delete the folder (Project-Guidance) from your local then again clone the repo from remote repo .
 Using  this `git clone https://github.com/Kushal997-das/Project-Guidance.git` , after cloning you can do your work and whatever you saved before deleting folder now you can add new clone repo .

I hope it helps try to resolve it ASAP .

**Comment by FatimahAdwan** [comment]
> Yes you can delete the whole `project-guidance` folder from you local but make sure what you have made changes in local before delete the `Project-guidance` whole folder you can copy those changes in your other local folder and save there . Then delete the folder (Project-Guidance) from your local then again clone the repo from remote repo . Using this `git clone https://github.com/Kushal997-das/Project-Guidance.git` , after cloning you can do your work and whatever you saved before deleting folder now you can add new clone repo .
> 
> I hope it helps try to resolve it ASAP .

okay i am going to do that. i hope it solves it too

**Comment by FatimahAdwan** [comment]
> > Yes you can delete the whole `project-guidance` folder from you local but make sure what you have made changes in local before delete the `Project-guidance` whole folder you can copy those changes in your other local folder and save there . Then delete the folder (Project-Guidance) from your local then again clone the repo from remote repo . Using this `git clone https://github.com/Kushal997-das/Project-Guidance.git` , after cloning you can do your work and whatever you saved before deleting folder now you can add new clone repo .
> > I hope it helps try to resolve it ASAP .
> 
> okay i am going to do that. i hope it solves it too

i have a question, do i need to fork it again before cloning, because i have cloned already? and is there a format for naming branches or i just name my branch as i want?

**Comment by Kushal997-das** [comment]
@FatimahAdwan Follow these [videos](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md#need-more-help) you will get to know .

**Comment by FatimahAdwan** [comment]
> @FatimahAdwan Follow these [videos](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md#need-more-help) you will get to know .

alright then, thank you

**Comment by FatimahAdwan** [comment]
> > @FatimahAdwan Follow these [videos](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md#need-more-help) you will get to know .
> 
> alright then, thank you

i will let you know the update, after watching them
