### ISSUE TITLE
Title : Medical Insurance Cost Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [Kushal997-das/Project-Guidance#419]
### Is your feature request related to a problem? Please describe.

The main goal of the project is to predict medical insurance cost prediction

I will be using this dataset : https://www.kaggle.com/subhakarks/medical-insurance-cost-analysis-and-prediction/data

### Describe the solution you'd like.

It helps in analyzing the cost and predicting the medical insurance using various ML algorithms based on various parameters from dataset taken into consideration.

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

I would like to take up this issue as GSSoC contributor. Kindly assign. @Kushal997-das

**Comment by Kushal997-das** [comment]
@prathimacode-hub We have this project already.
