### ISSUE TITLE
Pong game in python 

### ISSUE THREAD

**Issue by zehra47** [Kushal997-das/Project-Guidance#431]
### Pong game using python

![pong_game](https://user-images.githubusercontent.com/73516108/159172609-b3f13676-2a3c-4600-b604-54091d7c3f58.jpg)

**Comment by zehra47** [comment]
Can you please assign this to me

**Comment by mayank-del** [comment]
@zehra47  bro, i was already assigned in this, please try something else.

**Comment by Kushal997-das** [comment]
@zehra47 Wait for this as of now .
