### ISSUE TITLE
Title: Add a simple Matrix Calculator 

### ISSUE THREAD

**Issue by kaustav202** [Kushal997-das/Project-Guidance#439]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

Given a user entered matrix the calculator finds the adjoint and inverse of that matrix. Made using vanilla js , html and css.

### Describe alternatives you've considered.

NA

**Comment by kaustav202** [comment]
I would like to work on this issue.

**Comment by Kushal997-das** [comment]
@kaustav202 Please mentioned the tech that you are going to use .

**Comment by AnIkeT126** [comment]
is it up for grab @Kushal997-das ?
please assign it to me if it is
