### ISSUE TITLE
Title: Add a Currency Converter App

### ISSUE THREAD

**Issue by priyanshu688** [Kushal997-das/Project-Guidance#451]
### Is your feature request related to a problem? Please describe.

I have made a very user friendly Currency Converter App.

### Describe the solution you'd like.

Live - https://priyanshu688.github.io/Currency_Converter/

### Describe alternatives you've considered.

This is built using Java language.

**Comment by Kushal997-das** [comment]
@priyanshu688 URL is not working !

**Comment by priyanshu688** [comment]
@Kushal997-das Okh.. So Actually this is a mobile application. So I am unable to share the working app link.

**Comment by priyanshu688** [comment]
Can I still add the project? @Kushal997-das

**Comment by Kushal997-das** [comment]
@priyanshu688 Yes

**Comment by priyanshu688** [comment]
@Kushal997-das Kindly review and merge this PR - https://github.com/Kushal997-das/Project-Guidance/pull/458
