### ISSUE TITLE
python program to build a neural network model with different learning models: 

### ISSUE THREAD

**Issue by ABHIGPT401** [Kushal997-das/Project-Guidance#477]
### Is your feature request related to a problem? Please describe.

python program to build a neural network model with different learning models.

### Describe the solution you'd like.

python program to build a neural network model with different learning models.

### Describe alternatives you've considered.

python program to build a neural network model with different learning models.

**Comment by ABHIGPT401** [comment]
Please assign me this and place it under the advanced category and assign it the GSSOC'22 Badge

**Comment by Kushal997-das** [comment]
@ABHIGPT401 This project is already exits .
