### ISSUE TITLE
Add a web development project

### ISSUE THREAD

**Issue by TawfikYasser** [Kushal997-das/Project-Guidance#48]
Hi,

This issue to add a new web development project

The project developed with:
* JSP
* Servlets
* HTML5 & CSS3
* JavaScript & JQuery
* Ajax
* MySQL

I hope this project helps other developers.

**Comment by SamarpanCoder2002** [comment]
> Hi,
> 
> This issue to add a new web development project
> 
> The project developed with:
> 
> * JSP
> * Servlets
> * HTML5 & CSS3
> * JavaScript & JQuery
> * Ajax
> * MySQL
> 
> I hope this project helps other developers.

Successfully merged

**Comment by TawfikYasser** [comment]
> > Hi,
> > This issue to add a new web development project
> > The project developed with:
> > 
> > * JSP
> > * Servlets
> > * HTML5 & CSS3
> > * JavaScript & JQuery
> > * Ajax
> > * MySQL
> > 
> > I hope this project helps other developers.
> 
> Successfully merged

Thanks @SamarpanCoder2002
