### ISSUE TITLE
Python GUI Calendar App

### ISSUE THREAD

**Issue by abhilipsasahoo03** [Kushal997-das/Project-Guidance#550]
### Is your feature request related to a problem? Please describe.

A Calender feature to view day, date and month of any year. 

### Describe the solution you'd like.

A GUI Calendar built using Python Tkinter Module as a solution to the problem described above. I'd like to be assigned this issue under GSSOC'22.

### Describe alternatives you've considered.

None. 

### Add any other context or screenshots about the feature request here.

None.

**Comment by tasneemahmed123** [comment]
Can you assign me this issue @abhilipsasahoo03

**Comment by abhilipsasahoo03** [comment]
Hi @Kushal997-das sorry for the delay. The delay was caused by my end sem exams. However I'll be making the pull request by tomorrow.

**Comment by tasneemahmed123** [comment]
Can you assign me this issue ?

**Comment by Kushal997-das** [comment]
> Can you assign me this issue ?

Sorry it's already been assigned .

**Comment by Kushal997-das** [comment]
> Hi @Kushal997-das sorry for the delay. The delay was caused by my end sem exams. However I'll be making the pull request by tomorrow.

It's Okey @abhilipsasahoo03

**Comment by Kushal997-das** [comment]
@abhilipsasahoo03 Should we close the PR?

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 Should we close the PR?

Hi, sorry I've been facing some medical issues for the past weeks, but I'll try to make a PR by end of the day. If I'm unable to do so by EOD, you are free to close the PR or assign someone else.

**Comment by Kushal997-das** [comment]
@abhilipsasahoo03 So sorry to hear that take care of yourself .
