### ISSUE TITLE
Want to add cool readme under desktop application. 

### ISSUE THREAD

**Issue by Kushal997-das** [Kushal997-das/Project-Guidance#58]
**In this folder I want to add proper readme.**

[Desktop Application ](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application )

![IMG_20210126_231630](https://user-images.githubusercontent.com/61356005/105883678-2118cb80-602d-11eb-894c-c2c3d6953215.jpg)

**Comment by TawfikYasser** [comment]
Hi @Kushal997-das  Please clarify the pattern of the file content!
I can do that if you want

**Comment by Kushal997-das** [comment]
> Hi @Kushal997-das Please clarify the pattern of the file content!
> I can do that if you want

@TawfikYasser Do it by your own style and I think this gonna be cool then definitely you can send PR.

**Comment by TawfikYasser** [comment]
Ok, I’m going to work on it

**Comment by UG-SEP** [comment]
#58 this issue have been solved

**Comment by SamarpanCoder2002** [comment]
> #58 this issue have been solved

I am going to improve it

**Comment by SamarpanCoder2002** [comment]
> **In this folder I want to add proper readme.**
> 
> [Desktop Application ](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application)
> 
> ![IMG_20210126_231630](https://user-images.githubusercontent.com/61356005/105883678-2118cb80-602d-11eb-894c-c2c3d6953215.jpg)

I make something different..hope you like it...Rest work will cover soon...

**Comment by TawfikYasser** [comment]
> > **In this folder I want to add proper readme.**
> > [Desktop Application ](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application)
> > ![IMG_20210126_231630](https://user-images.githubusercontent.com/61356005/105883678-2118cb80-602d-11eb-894c-c2c3d6953215.jpg)
> 
> I make something different..hope you like it...Rest work will cover soon...

Greta worl

**Comment by SamarpanCoder2002** [comment]
> > > **In this folder I want to add proper readme.**
> > > [Desktop Application ](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application)
> > > ![IMG_20210126_231630](https://user-images.githubusercontent.com/61356005/105883678-2118cb80-602d-11eb-894c-c2c3d6953215.jpg)
> > 
> > 
> > I make something different..hope you like it...Rest work will cover soon...
> 
> Great work

Thanks, @TawfikYasser ... You also help me a lot to do that...Thanks for your contribution

**Comment by SamarpanCoder2002** [comment]
> **In this folder I want to add proper readme.**
> 
> [Desktop Application ](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application)
> 
> ![IMG_20210126_231630](https://user-images.githubusercontent.com/61356005/105883678-2118cb80-602d-11eb-894c-c2c3d6953215.jpg)

Complete to add Cool REAME.... But anybody can improve this....

**Comment by Kushal997-das** [comment]
@SamarpanCoder2002  Great job but one thing it's better to not add gif in desktop readme.md file because every contributor do not add gif . So it's better to add only name of the projects and link of those projects.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 Great job but one thing it's better to not add gif in desktop readme.md file because every contributor do not add gif . So it's better to add only name of the projects and link of those projects.

I think without gif or image in readme....it's not clear to the visitor about the project idea....GIF or image gives a partial thought about the project...Even everyone provided either image or gif in the readme...So, I think it's a good project name with GIF or image file...

**Comment by Kushal997-das** [comment]
> > @SamarpanCoder2002 Great job but one thing it's better to not add gif in desktop readme.md file because every contributor do not add gif . So it's better to add only name of the projects and link of those projects.
> 
> I think without gif or image in readme....it's not clear to the visitor about the project idea....GIF or image gives a partial thought about the project...Even everyone provided either image or gif in the readme...So, I think it's a good project name with GIF or image file...

Indeed @SamarpanCoder2002 but it's not possible to add gif in every project. There are few those are adding project without gif. So it's better to stay with ni gif only project name and link of the project .

**Comment by SamarpanCoder2002** [comment]
> > > @SamarpanCoder2002 Great job but one thing it's better to not add gif in desktop readme.md file because every contributor do not add gif . So it's better to add only name of the projects and link of those projects.
> > 
> > 
> > I think without gif or image in readme....it's not clear to the visitor about the project idea....GIF or image gives a partial thought about the project...Even everyone provided either image or gif in the readme...So, I think it's a good project name with GIF or image file...
> 
> Indeed @SamarpanCoder2002 but it's not possible to add gif in every project. There are few those are adding project without gif. So it's better to stay with ni gif only project name and link of the project .

Ok....from the later projects I will do that...
