### ISSUE TITLE
Hospital management system

### ISSUE THREAD

**Issue by jyothi-k-g** [Kushal997-das/Project-Guidance#586]
### Is your feature request related to a problem? Please describe.

It is difficult for people to book an appointment with the doctors and maintaining the health history of the patient.

### Describe the solution you'd like.

It's an online portal which helps the paitients to book appointment with the doctors and to maintain there healthb records

### Describe alternatives you've considered.

It's easy to maintain patient records which saves time for both doctor and patients

**Comment by jyothi-k-g** [comment]
@Kushal997-das  please assign this issue to me under gssoc 2022

**Comment by tasneemahmed123** [comment]
Can you assign me this issue I will work on developing a.web app for patients to know how to book an appointment with doctors in order to save time and avoid crowdedness

**Comment by tasneemahmed123** [comment]
@jyothi-k-g

**Comment by Kushal997-das** [comment]
> Can you assign me this issue I will work on developing a.web app for patients to know how to book an appointment with doctors in order to save time and avoid crowdedness

sorry Not possible since she raise the issue first .
