### ISSUE TITLE
Title: Page View Time Series Visualizer

### ISSUE THREAD

**Issue by Viraj-Sanap** [Kushal997-das/Project-Guidance#626]
### Is your feature request related to a problem? Please describe.

Machine Learning Basic Project to visualize time series data using a line chart, bar chart, and box plots. 

### Describe the solution you'd like.

You will use Pandas, Matplotlib, and Seaborn to visualize a dataset containing the number of page views each day on the given forum from 2016-05-09 to 2019-12-03. The data visualizations will help you understand the patterns in visits and identify yearly and monthly growth.

### Describe alternatives you've considered.

GGplot, Altair, Geoplotlib, etc can be used as libraries.

**Comment by Kushal997-das** [comment]
Will assign after you have successfully send PR .
