### ISSUE TITLE
My plan for the rest of the year

### ISSUE THREAD

**Issue by TawfikYasser** [Kushal997-das/Project-Guidance#65]
Hi

Thanks @Kushal997-das & @SamarpanCoder2002 for making me one of this great community.

I still have other projects to add and I will continue ASAP, After that I will work on my projects in the repository to update and enhance them day by day to be a good reference for other people.

I can see a great future for [Project Guidance](https://github.com/Kushal997-das/Project-Guidance)

Thanks again for all.

**Comment by SamarpanCoder2002** [comment]
Thanks for your nice comment.....We are lucky to have you as a contributor...
