### ISSUE TITLE
Coffee shop website

### ISSUE THREAD

**Issue by jyothi-k-g** [Kushal997-das/Project-Guidance#670]
### Is your proposal related to a problem? Please describe.

This is an website which provides all the details of coffee shop, services, dishes available,menu, reservation, testimonials and other features

**Comment by jyothi-k-g** [comment]
@Kushal997-das  please assign this issue to me under gssoc22

**Comment by Kushal997-das** [comment]
@jyothi-k-g Don't spam
https://github.com/khushi-purwar/WebDev-ProjectKart/issues/1639

**Comment by jyothi-k-g** [comment]
I haven't created the pull request for this @Kushal997-das  I had created new issue but before creating the pull request they had announced that no new pull request will be accepted in webdev project kart

**Comment by Kushal997-das** [comment]
@jyothi-k-g Then close it from there .

**Comment by jyothi-k-g** [comment]
Okk I'll do that

**Comment by jyothi-k-g** [comment]
Done @Kushal997-das
