### ISSUE TITLE
Update Readme.md files 

### ISSUE THREAD

**Issue by Kushal997-das** [Kushal997-das/Project-Guidance#765]
I want to update the `readme.md` file for : 

[Desktop Application](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application) <br>
[Machine Learning and Data Science](https://github.com/Kushal997-das/Project-Guidance/tree/main/Machine%20Learning%20and%20Data%20Science) <br>

[Mobile Applications](https://github.com/Kushal997-das/Project-Guidance/tree/main/Mobile%20Applications) <br>

[Web Development](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development) <br>

Anyone can contribute to this issue . 

For this please follow [`contributing.md` file](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)

**Comment by shyamtawli** [comment]
i am asking what content you want to add?

**Comment by Kushal997-das** [comment]
@shyamtawli
Check this `readme.md` file in order to understand .
 [FYI](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application)

**Comment by muskan467** [comment]
I wanted to update Web development readme as some projects are not mentioned in bullet points. Can u assign me this. @Kushal997-das

**Comment by Prekshathakkar51** [comment]
Kindly assign me this issue
