### ISSUE TITLE
Title: Blockchain Development 

### ISSUE THREAD

**Issue by Sanitya7** [Kushal997-das/Project-Guidance#767]
### Is your feature request related to a problem? Please describe.

People are now also exploring blockchain domain for its unmatachable features but are unable to find projects build in the blockchain domain at a basic, intermediate level.

### Describe the solution you'd like.

I am proposing to add a new folder named Blockchain, where in I will be adding basic solidity based projects for the beginners of blockchain domain

### Describe alternatives you've considered.

We may also add a simple blog section for the new learners of blockchain describing the consensus mechanisms, the operations and applications of blockchain.

### Add any other context or screenshots about the feature request here.

```
// SPDX-License-Identifier: MIT

pragma solidity 0.8.0;

contract ETH_to_SC {
    address payable public receiver = payable(0x4B20993Bc481177ec7E8f571ceCaE8A9e22C02db);
    //Understand the receive inbuilt function 
    receive() external payable{} 

    function getBalance() public view returns( uint ) {
        return address( this ).balance ; 
    }
}

//this is a code for transacting ETH from an account to Smart Contract 
```

This is the code snippet for the basic project of ether transaction on the smart contract.

**Comment by Sanitya7** [comment]
Thanks @Kushal997-das for assigning the task, I would love to contribute for the same.

**Comment by Sanitya7** [comment]
Hi @Kushal997-das , you may create a folder for blockchain dev. I shall then raise the PR in it.

**Comment by Kushal997-das** [comment]
@Sanitya7 Yes i'm going to add a folder .

**Comment by Kushal997-das** [comment]
@Sanitya7 I have crated a folder `Blockchain Development` please add your PR over their in the folder `Blockchain Development`.
