### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by Kushal997-das** [Kushal997-das/Project-Guidance#78]
**Update readme and make it more fun In this folder** 

[Web Development ](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development)

Reference: https://kushal997-das.github.io/Project-Guidance/

**Comment by SamarpanCoder2002** [comment]
> **Update readme and make it more fun In this folder**
> 
> [Web Development ](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development)
> 
> Reference: https://kushal997-das.github.io/Project-Guidance/

Any body please contribute here....to help us...

**Comment by JohnWesleyK** [comment]
Hey I'd like to work on this can you provide me with notes for the README

**Comment by Kushal997-das** [comment]
> Hey I'd like to work on this can you provide me with notes for the README

There is no such notes see the desktop application folder for reference and do the same job in web development folder. I hope it make sense @JohnWesleyK

**Comment by JohnWesleyK** [comment]
@Kushal997-das I've updated the web development README and here is the [link](https://github.com/Kushal997-das/Project-Guidance/pull/83) to the PR related to that

**Comment by Kushal997-das** [comment]
Done!
