### ISSUE TITLE
Title: Titanic Survival Prediction

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Kushal997-das/Project-Guidance#800]
### Is your proposal related to a problem? Please describe.

Titanic Survival Prediction Project from Kaggle

**Comment by Kushal997-das** [comment]
@Soumya-Kushwaha #796 Kindly finish this .

**Comment by Soumya-Kushwaha** [comment]
@Kushal997-das Please assign now

**Comment by Soumya-Kushwaha** [comment]
@Kushal997-das hello?

**Comment by Kushal997-das** [comment]
@Soumya-Kushwaha Please add more description about this project .
