### ISSUE TITLE
Title:  A backend Dance Website

### ISSUE THREAD

**Issue by Laraibnehal** [Kushal997-das/Project-Guidance#809]
### Is your proposal related to a problem? Please describe.

Made this website using only backend language. Simple and understandable code

**Comment by Kushal997-das** [comment]
@Laraibnehal Describe more about this .

**Comment by Laraibnehal** [comment]
I made a website using only backend languages where I also created a form page where it gets submitted to database directly.And code is easy to understand and simple.

**Comment by Laraibnehal** [comment]
@Kushal997-das

**Comment by Kushal997-das** [comment]
@Laraibnehal Add some images at least name of your project

**Comment by Laraibnehal** [comment]
![lda website ](https://user-images.githubusercontent.com/95610027/214619354-7f922794-1c56-4e86-8efd-1766f88ad7d7.png)
Laraib's dance academy is the project's name
