### ISSUE TITLE
Please add Credit Card Fraud Detection Project

### ISSUE THREAD

**Issue by Avisikta-Majumdar** [Kushal997-das/Project-Guidance#81]
[ML Project (Supervised Learning)Credit_Card_Fraud_Detection](https://github.com/Avisikta-Majumdar/Credit_Card_Fraud_Detection)

**Comment by TawfikYasser** [comment]
Hi
@Avisikta-Majumdar 
You can follow this [CONTRIBUTING RULES](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) to add your project.

Welcome to **Project Guidance**

**Comment by Avisikta-Majumdar** [comment]
I hv read but can't add my project please help @TawfikYasser

**Comment by TawfikYasser** [comment]
Welcome @Avisikta-Majumdar 

Please follow these steps:
* Fork the repository
* Clone the repository using `git clone <repo-link>`
* Add your project to the appropriate directory
* Commit your changes and push them
* Make a Pull Request

I hope this help you.

**Comment by SamarpanCoder2002** [comment]
> Welcome @Avisikta-Majumdar
> 
> Please follow these steps:
> 
> * Fork the repository
> * Clone the repository using `git clone <repo-link>`
> * Add your project to the appropriate directory
> * Commit your changes and push them
> * Make a Pull Request
> 
> I hope this help you.

Good

**Comment by UG-SEP** [comment]
hey @Kushal997-das,
I think you should close this issue because the author @Avisikta-Majumdar  hasn't respond till now near about 2 month gone so please close this issue so it look that the Project Guidance member are active
