### ISSUE TITLE
Title: Landing page 

### ISSUE THREAD

**Issue by Laraibnehal** [Kushal997-das/Project-Guidance#810]
### Is your proposal related to a problem? Please describe.

Dynamic landing page using HTML,CSS,JS

**Comment by Kushal997-das** [comment]
@Laraibnehal Describe more about this .

**Comment by Laraibnehal** [comment]
Created a landing page for travel enthusiasts  people .It is simple yet very beginner's friendly project.

**Comment by Laraibnehal** [comment]
![travel](https://user-images.githubusercontent.com/95610027/214041367-9429d935-3f4e-4615-85ad-3b4579bdb6d8.png)
