### ISSUE TITLE
Title: Update all readme files 

### ISSUE THREAD

**Issue by Prekshathakkar51** [Kushal997-das/Project-Guidance#818]
### Explain what you want to add/change in documentation.

Most of the project readme files seems not updated. I wish to update them

**Comment by Prekshathakkar51** [comment]
Kindly assign me this issue

**Comment by Kushal997-das** [comment]
@Prekshathakkar51 What exactly you want update in `readme.md` file .

**Comment by Kushal997-das** [comment]
@Prekshathakkar51 Someone else already make PR about this .

#821
