### ISSUE TITLE
Title: Car Price Prediction Model

### ISSUE THREAD

**Issue by aryaman1202** [Kushal997-das/Project-Guidance#824]
### Is your proposal related to a problem? Please describe.

My proposal is based on predicting prices of cars based on some of it's important features used to distinguish cars. Analyzing a given dataset and calculating results. Please assign me this issue for SWOC 23 @Kushal997-das

**Comment by Kushal997-das** [comment]
@aryaman1202 Create one issue at a time let complete the first one then i'll assign.

**Comment by aryaman1202** [comment]
Please assign me this issue now, my previous issue is closed now. @Kushal997-das
