### ISSUE TITLE
Title: Laptop Price Prediction

### ISSUE THREAD

**Issue by aryaman1202** [Kushal997-das/Project-Guidance#825]
### Is your proposal related to a problem? Please describe.

The problem of my proposal is to design a laptop price prediction model based on important features of a laptop. We will be analyzing a given dataset and will get useful insights as well as design a prediction model for the same. @Kushal997-das Please assign me this issue for SWOC 23.

**Comment by Kushal997-das** [comment]
@aryaman1202 Create one issue at a time let complete the first one then i'll assign.

**Comment by aryaman1202** [comment]
@Kushal997-das please assign this issue to me. Would like to contribute in this repository for SWOC' 23

**Comment by aryaman1202** [comment]
@Kushal997-das Please assign the issue to me
