### ISSUE TITLE
Title: Add a weight converter project in web development

### ISSUE THREAD

**Issue by palaksinghania05** [Kushal997-das/Project-Guidance#826]
### Is your proposal related to a problem? Please describe.

It will just convert weight from kgs to gms and other units.

**Comment by Kushal997-das** [comment]
@palaksinghania05 Add more description about this project .

**Comment by palaksinghania05** [comment]
It is a single-page website built using HTML, CSS, and javascript in which the user will give input in kgs. Pressing the convert button will show the output in grams, pounds, and ounces. A reset functionality will also clear all the fields for new input.
@Kushal997-das
