### ISSUE TITLE
Blog website using html , css , js

### ISSUE THREAD

**Issue by charu1603** [Kushal997-das/Project-Guidance#837]
This is a static blog website made using html , css and js . 
[link](https://charu1603.github.io/blog-website/)

**Comment by charu1603** [comment]
I want to contribute on this issue under swoc Kindly assign this to me

**Comment by Kushal997-das** [comment]
@charu1603 Do finish the first one then create next issue , one issue at a time .

**Comment by charu1603** [comment]
@Kushal997-das I have created the pr for the previous issue kindly review it .

**Comment by charu1603** [comment]
@Kushal997-das  can you assign me this issue . My previous pr got merged☺

**Comment by Prs0307** [comment]
@Kushal997-das Can you please assign me good first issues...
