### ISSUE TITLE
Update CONTRIBUTING RULES

### ISSUE THREAD

**Issue by TawfikYasser** [Kushal997-das/Project-Guidance#84]
Hi

I would like to add images to the text to make to more understandable for new contributors.

Thanks

**Comment by Kushal997-das** [comment]
> Hi
> 
> I would like to add images to the text to make to more understandable for new contributors.
> 
> Thanks

@TawfikYasser Explain please

**Comment by SamarpanCoder2002** [comment]
> Hi
> 
> I would like to add images to the text to make to more understandable for new contributors.
> 
> Thanks

Yah...You have done a great job....thanks @TawfikYasser

**Comment by TawfikYasser** [comment]
> > Hi
> > I would like to add images to the text to make to more understandable for new contributors.
> > Thanks
> 
> @TawfikYasser Explain please

I have added some images in the `contribution rules` file to make it easier for new contributors

**Comment by TawfikYasser** [comment]
> > Hi
> > I would like to add images to the text to make to more understandable for new contributors.
> > Thanks
> 
> Yah...You have done a great job....thanks @TawfikYasser

Thanks @SamarpanCoder2002

**Comment by Kushal997-das** [comment]
@TawfikYasser Please add your changes before step 2 . This makes sense. 
In step -2 I already mentioned how to clone so you have to add image before step and after sept one. 
@SamarpanCoder2002 please check carefully before you merge.

**Comment by TawfikYasser** [comment]
> @TawfikYasser Please add your changes before step 2 . This makes sense.
> In step -2 I already mentioned how to clone so you have to add image before step and after sept one.
> @SamarpanCoder2002 please check carefully before you merge.

Changes done.
Sorry for the error

**Comment by SamarpanCoder2002** [comment]
> @TawfikYasser Please add your changes before step 2 . This makes sense.
> In step -2 I already mentioned how to clone so you have to add image before step and after sept one.
> @SamarpanCoder2002 please check carefully before you merge.

Sorry for that casualty...
