### ISSUE TITLE
Title: JS Shopping Cart

### ISSUE THREAD

**Issue by manisha-nair28** [Kushal997-das/Project-Guidance#842]
## Adding a new basic web development project: JS Shopping Cart

A simple one-page shopping cart website built using HTML, CSS, JavaScript, and jQuery. The website features a user-friendly interface for adding items to the cart. The total cost is automatically calculated and displayed on the page as items are added. The website uses JavaScript and jQuery to update the cart and calculate the total cost dynamically.

### Add any other context or screenshots about the proposal request here.

![sc1](https://user-images.githubusercontent.com/109059571/216513323-9f9fb4ea-d99d-4d9e-81f1-6dce86fde691.png)

![sc2](https://user-images.githubusercontent.com/109059571/216513375-c170c78d-6322-4266-bf6c-485393143f88.png)

**Comment by Kushal997-das** [comment]
@manisha-nair28 Let's done with your PR first .

**Comment by manisha-nair28** [comment]
@Kushal997-das  pls assign this issue to me
