### ISSUE TITLE
Make a Live Character Counter WebApp

### ISSUE THREAD

**Issue by Srishtihere** [Kushal997-das/Project-Guidance#843]
The website will consist of a space where any text will be entered the characters entered will be counted live. Kindly assign me this issue under the beginner's folder.

**Comment by Kushal997-das** [comment]
@Srishtihere Any images would help us to understand please attach .

**Comment by Srishtihere** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/74984515/216682217-4421226d-0121-4835-bf26-91a3adfa8796.png)


My prescribed website will not be fully the same as I will be using the same idea but with different UI and different approach of Javascript.
