### ISSUE TITLE
Title: I wish to add Blockchain README file 

### ISSUE THREAD

**Issue by muskan467** [Kushal997-das/Project-Guidance#846]
### Explain what you want to add/change in documentation.

As of now readme file is empty and I want to add content according to the format needed.

**Comment by Kushal997-das** [comment]
@muskan467 Add more description about it

**Comment by muskan467** [comment]
I will add image describing the repo and its three level by adding links of the projects of respective folders. And in last message to the contributors for contributing guidelines. I'll try to make it more informative and creative.

**Comment by Kushal997-das** [comment]
@muskan467 Sounds good.
