### ISSUE TITLE
Food Ordering Website using HTML | CSS | JS

### ISSUE THREAD

**Issue by samvid2020** [Kushal997-das/Project-Guidance#870]
### Is your proposal related to a problem? Please describe.

No, this is a Project Proposal 

### Add any other context or screenshots about the proposal request here.

Nah!

**Comment by samvid2020** [comment]
can you assign this issue to me @Kushal997-das

**Comment by Kushal997-das** [comment]
@samvid2020 We have already this kinda project in our repo .
