### ISSUE TITLE
Web development - Food blog website

### ISSUE THREAD

**Issue by jain-anshika** [Kushal997-das/Project-Guidance#917]
Foodverse is a food blog website with many features

**Comment by Kushal997-das** [comment]
@jain-anshika Do mention your project, Not create a single-line issue.

**Comment by jain-anshika** [comment]
I m currently working this project

**Comment by jain-anshika** [comment]
# Foodverse - Discover endless possibilities in the kitchen, your ultimate recipe destination!

## Video Demo:  <https://youtu.be/JGxegepEcjY>

## Discription
- Search for different kinds of recipes
- Find necessary ingredients for each recipe item
- Save favorite recipe items to local storage
- Recipes for vegetarians, meat eaters, and people who want to lose weight
- Built with React, Tailwind, and React Router

## Introduction of website
Foodverse is a recipe website where users can search for different kinds of recipes and find the necessary ingredients for each recipe item. The website also allows users to save their favorite recipe items to the local storage of their browser.

Foodverse makes it easy to find recipes for both vegetarians and meat eaters, as well as for people who want to lose weight. The website is made with React, Tailwind, and React Router.


## Getting Started

To get started with Foodverse, follow these steps:

1. Install the necessary dependencies with `npm instal`
2. Run the app with `npm start`

## Technologies Used

- React
- Tailwind
- React Router

**Comment by Kushal997-das** [comment]
@jain-anshika Hello Though your video link is not working, but it's fine let's work on this project and do send the PR.

**Comment by jain-anshika** [comment]
https://youtu.be/A1ZWMTJAIVc?si=bbSGXUJDVP6_cNC_

This is the link

**Comment by Kushal997-das** [comment]
@jain-anshika The Issue Going to close soon if you do not send PR within 31ST OCT 12 PM IST.

**Comment by jain-anshika** [comment]
sorry the project is facing some issues right now and i m working on it!!
