### ISSUE TITLE
Title: Adding google translator feature to 'Google clone' project

### ISSUE THREAD

**Issue by payallenka** [Kushal997-das/Project-Guidance#918]
### Is your feature request related to a problem? Please describe.

Google provides it's search engine in almost every language. Your program only gives in a limited set of language.

### Describe the solution you'd like.

I would like to add the google translator to this project of yours making it more realistic. 

### Describe alternatives you've considered.

No alternatives I am sure this feature will be added in the most efficient way.

**Comment by payallenka** [comment]
I have forked and made the changes in it. Kindly add the hacktoberfest/hacktoberfest-accecpted label to this issue. Then I'll commit the changes in the main branch and close the issue.

**Comment by payallenka** [comment]
@Kushal997-das  kindly do the needed I am eager to do make the pull request.

**Comment by payallenka** [comment]
I have made the pull request, but an error has occurred, kindly guide me through or do the needed. 
![image](https://github.com/Kushal997-das/Project-Guidance/assets/83643171/1c74afba-35b1-4052-b7ff-a0e13b7dfa43)

**Comment by Kushal997-das** [comment]
The Issue Going to close soon if you do not send PR within 31ST OCT 12 PM IST.
