### ISSUE TITLE
Add Desktop Application

### ISSUE THREAD

**Issue by TawfikYasser** [Kushal997-das/Project-Guidance#92]
Hello,

This issue to add a new desktop application for `Java` -> Advanced Level

The project description in the README file 

The project is about `REST API` using `Spring Boot` using `Java`

Thanks

**Comment by TawfikYasser** [comment]
PR #93 Merged successfully, Please close the issue.
Thanks

**Comment by Kushal997-das** [comment]
Thanks @TawfikYasser
