### ISSUE TITLE
Title: Improvising overall aesthetics of the budgeting app

### ISSUE THREAD

**Issue by Pavana-karanth** [Kushal997-das/Project-Guidance#922]
### Is your feature request related to a problem? Please describe.

The overall design doesn't look like it's inviting users. A container taking the inputs and giving the percentage is placed randomly with no center positions. The tag line seems like it's a mere project display and not an application meant for use. It's not eye catchy and visually pleasing. 

### Describe the solution you'd like.

Using my knowledge in CSS and Html, I intend to give a suitable vibe to the page. Retaining the dark green color scheme of the input and calculate options, I'll work on making everything look fit and placed in an appealing manner with a bit of change in the tagline or heading.

### Describe alternatives you've considered.

I just have a couple of designs in mind and I'm looking forward to implementing them in the project!

**Comment by Pavana-karanth** [comment]
please assign the issue to me whenever possible!

**Comment by Kushal997-das** [comment]
The Issue Going to close soon if you do not send PR within 31ST OCT 12 PM IST.
