### ISSUE TITLE
Unnecessary iterations of the items added.

### ISSUE THREAD

**Issue by Pavana-karanth** [Kushal997-das/Project-Guidance#923]
### What happened?

When items and expenditure percentage is entered and calculated, for item 1 it gives item 1's calculation and for irem 2 it gives item 1 and item 2's calculations again, the iterations are unnecessary. They only confuse the consumers more.

### How can we reproduce this bug?

adding an item one after another is giving wrong format of output.

input- food, 10 
output seen: "you have 90% right now"
calculation: Food     1000

input- travel, 20
output seen: "you have 70% right now"
calculation: Food     1000
                  Travel      2000

Expected output calculation:
Food     1000
Travel      2000

overall output calculation:
Food     1000
Food     1000
Travel      2000

### Urgency (Optional)

None

**Comment by Pavana-karanth** [comment]
for the budgeting app in basic category of web development!

**Comment by Kushal997-das** [comment]
The Issue Going to close soon if you do not send PR within 31ST OCT 12 PM IST.
