### ISSUE TITLE
Navbar for the budgetting app

### ISSUE THREAD

**Issue by Pavana-karanth** [Kushal997-das/Project-Guidance#934]
### Is your feature request related to a problem? Please describe.

The website layout looks bland with no navbar or logo and just "Budgetting app" all in bold font. A navbar consisting of common options like home page por profile and about us, contact us - cam be developed in order to make the website look more appealing!

### Describe the solution you'd like.

With my skills in html and Css I would be able to effectively add the navbar as per the necessity. 

### Describe alternatives you've considered.

No alternatives as of now. I just have a few designs in mind, I can work on them!

**Comment by Pavana-karanth** [comment]
Please make sure to assign the issue to me!

**Comment by Kushal997-das** [comment]
The Issue Going to close soon if you do not send PR within 31ST OCT 12 PM IST.
