### ISSUE TITLE
Title: Raspberry Pi projects under IoT along with Arduino

### ISSUE THREAD

**Issue by Royal-Emine** [Kushal997-das/Project-Guidance#960]
### Is your feature request related to a problem? Please describe.

It's not a problem but a suggestion that IoT consists of widely used components which includes higher end major components like Arduino, Raspberry Pi, Dexter etc. So , keeping the folder restricted to only Arduino doesn't seems unfair. Therefore, I would like to add IoT projects done based on Raspberry Pi too which will not only serve the vision of projects available in variety but also available options can be availed for a project which is available in both Arduino and Raspberry Pi.

### Describe the solution you'd like.

Adding Raspberry Pi based projects in " IOT(Internet of Things)/Basic "

### Describe alternatives you've considered.

Projects based on Arduino to be also made available along with similar projects made on Raspberry Pi.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/112507451/260483a2-cb5a-496a-b4bc-1ef0d3496eef)

The folder consists of projects based on Arduino only which is quite specific and requires diversification with the inclusion of other IoT projects also along with separate boards.

**Comment by Kushal997-das** [comment]
@Royal-Emine Is it under GSSoC'24 ?

**Comment by Royal-Emine** [comment]
How to find out that? I'm not really acquainted with that.

**Comment by Kushal997-das** [comment]
Are you a GSSoC'24  contributor?

**Comment by Royal-Emine** [comment]
Yes
