### ISSUE TITLE
Sentimental Analysis on Social Media Data

### ISSUE THREAD

**Issue by Royal-Emine** [Kushal997-das/Project-Guidance#961]
### Is your feature request related to a problem? Please describe.

A request to encourage the inclusion of Sentimental Analysis from Social Media Data in the folder - Machine Learning and Data Science/Advanced 

### Describe the solution you'd like.

A clarified Python code performing sentimental analysis on Facebook , Twitter and Instagram and analyze its overall performance

### Describe alternatives you've considered.

Sentimental Analysis on some other social media platforms.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/112507451/83938577-069d-4d14-8359-772f634a21a1)

A new project request on Sentimental Analysis from Social Media Data

**Comment by dpkkmr20** [comment]
Can you plz assign this issue.

**Comment by OmChillure** [comment]
@Kushal997-das Can you please assign this issue to me !!!

**Comment by ShreyaAwasekar** [comment]
Can you assign this issue to me?

**Comment by SayantikaLaskar** [comment]
I want to contribute on this issue please assign it to me under gssoc24

**Comment by Royal-Emine** [comment]
@Kushal997-das I request you to assign me this issues to resolve for I am the one to open the issue and wish to contribute in it.

**Comment by Kushal997-das** [comment]
> @Kushal997-das I request you to assign me this issues to resolve for I am the one to open the issue and wish to contribute in it.

Done
