### ISSUE TITLE
Input format specification

### ISSUE THREAD

**Issue by joongdok1864** [Kushal997-das/Project-Guidance#964]
### Is your feature request related to a problem? Please describe.

I think it would be a good idea to mention the format of the input when asking the user. Please give me this issue

### Describe the solution you'd like.

A small mention that the format for birthday can be helpful.

### Describe alternatives you've considered.

If not, then it should be mentioned that reading the README file is necessary and to be not skipped.

**Comment by aryadavare19** [comment]
I know java Language , Can you please assign me any Suitable work ? I am eager to contribute.

**Comment by Kushal997-das** [comment]
> I know java Language , Can you please assign me any Suitable work ? I am eager to contribute.

Look around the repo try to find the suitable work

**Comment by Kushal997-das** [comment]
@joongdok1864 Your issue is not clear to me . Please explain in detail what exactly you want to do .

**Comment by joongdok1864** [comment]
i forgot to delete this, was about to send this to my friend, sorry for the inconvenience.
