### ISSUE TITLE
Duplicate Code and Error Handling Issues

### ISSUE THREAD

**Issue by jahnaviviyyapu** [Kushal997-das/Project-Guidance#970]
### What happened?

There is a code duplication issue in the EDA on Netflix data in Machine Learning and Data Science - Basic. Also, there are some missing values in the data which must be handled.

### How can we reproduce this bug?

I have run this code and found that the code for analyzing directors and cast is duplicated. I have also noticed that there are some missing values in the data to be handled.

### Urgency (Optional)

High priority

**Comment by Kushal997-das** [comment]
@jahnaviviyyapu Go ahed !

**Comment by Avishek8136** [comment]
I can work with this bug. I have done this before too. Please assign me

**Comment by Kushal997-das** [comment]
> I can work with this bug. I have done this before too. Please assign me

It's already assign to someone else. If the person not able to solve will assign you.

**Comment by Avishek8136** [comment]
ok thank you.
