### ISSUE TITLE
GSSOC'24 wanna add my project virtual classes attendance extractor

### ISSUE THREAD

**Issue by ramsatyasai** [Kushal997-das/Project-Guidance#971]
## ❓ Questions and Help
the project description is that if we upload the attendance sheet which include the time duration in the virtual class , students list with rolls, and the minimum threshold percentage of class duration attended. the sorted list of students  will be displays. technologies used python libs like flask for backend, pandas for data analysis, etc

can i add this to your repo . i think it can be a intermediate one

**Comment by Kushal997-das** [comment]
@ramsatyasai Explain in details about your project .

**Comment by ramsatyasai** [comment]
> @ramsatyasai Explain in details about your project .
its a basic web application which helps the educators for shortlisting the attendance of the students based on the threshold percentage of time they present in the meeting.
user inputs: 
1. csv file with their total students, roll numbers 
2. attendance csv file which contains (student name, first appeared, total time in call
3. threshold percentage of time
after providing the above inputs the results will be shown in the table format
