### ISSUE TITLE
GSSOC'24 Want to add a Dice roller application in the mobile applications domain

### ISSUE THREAD

**Issue by X-Cypher** [Kushal997-das/Project-Guidance#974]
### Is your proposal related to a problem? Please describe.

Dice Roller | Mobile App:
The Dice Roller app lets users tap a button to roll a dice. The outcome is
randomized and is displayed with the image of the particular number on the dice on the user screen.

### Add any other context or screenshots about the proposal request here.

Tech Stack: Jetpack Compose for UI and Kotlin for App logic

**Comment by Kushal997-das** [comment]
@X-Cypher Kinldy share the screenshot to me ,for better understanding

**Comment by Kushal997-das** [comment]
@X-Cypher As no update so going to close the issue. Feel free to open a new one.
