### ISSUE TITLE
Add an android application

### ISSUE THREAD

**Issue by TawfikYasser** [Kushal997-das/Project-Guidance#98]
Hi

This issue to add an android application using `Java` called `Cowost`

Thanks

**Comment by SamarpanCoder2002** [comment]
> Hi
> 
> This issue to add an android application using `Java` called `Cowost`
> 
> Thanks

Please add it by following the guidelines of Contributing.md

**Comment by TawfikYasser** [comment]
Added Successfully with last PR #97 
Please close this issue
Thanks

**Comment by SamarpanCoder2002** [comment]
Ok...Thanks for your contribution
