### ISSUE TITLE
GSSOC 24  Want to add Snake Game under Desktop Application

### ISSUE THREAD

**Issue by Ayushi22-coder** [Kushal997-das/Project-Guidance#980]
### Is your proposal related to a problem? Please describe.

Snake game:
In this game, we'll delve into the world of game development as we build a classic Snake game using Java (Swing, and AWT). We will build this game step-by-step from scratch. Discover how to design the game board, handle user input, implement snake movement, and incorporate collision detection.

### Add any other context or screenshots about the proposal request here.

Tech Stack:Core Java ,Swing, AWT, Graphics, Exceptional Handling, OOPS, Abstract classes, Interfaces
IDE used: Netbeans

**Comment by Kushal997-das** [comment]
@Ayushi22-coder Share screenshots for better understanding.

**Comment by merciajeno** [comment]
Hey, we can create a snake game using turtle. I have done it and can use tkinter to create a desktop application?

**Comment by Kushal997-das** [comment]
@merciajeno Hello, we have the same project already in our repo (:
