### ISSUE TITLE
GSSOC'24 Want to add Water Quality Data EDA

### ISSUE THREAD

**Issue by Arghya-Banerjee** [Kushal997-das/Project-Guidance#982]
### Is your feature request related to a problem? Please describe.

It a water impurities dataset that can provide insights on how pollution or water quality has changed through the passage of time.

### Describe the solution you'd like.

I would like to first make a Jupyter Notebook file that will make the initial EDA of the dataset and then try to add a prediction model to it.

### Describe alternatives you've considered.

An alternate approach that I am thinking of is making a Power Bi dashboard out of the dataset.

**Comment by deepti-50** [comment]
I would like to work on this issue please assign me this @Kushal997-das

**Comment by shikham12** [comment]
please assign this issue

**Comment by Kushal997-das** [comment]
> I would like to work on this issue please assign me this under GSSOC'24 @Kushal997-das

Hello, he already opened the issue first , make sure to create your own issue.

**Comment by Arghya-Banerjee** [comment]
@Kushal997-das Thank you for assigning me this issue, I am already working on this. Just a small request, can you please add the level label for the issue as required by GSSoC'24? Thank you again !
