### ISSUE TITLE
GSSOC'24 Want to LLM Related projects 

### ISSUE THREAD

**Issue by YugantGotmare** [Kushal997-das/Project-Guidance#985]
### Is your feature request related to a problem? Please describe.

Yes, with the rapid advancement of language models (LLMs), there's a growing demand for opportunities to explore, contribute to, and learn from projects related to this field.
What if we make new folder for only project realted to generative AI or LLM based project

### Describe the solution you'd like.

By using API like Gemini and chatgpt we can make many generative AI and LLM realted project and also using framework like langchain 

### Describe alternatives you've considered.

we can also make project on RAG based techniques

@Kushal997-das

**Comment by YugantGotmare** [comment]
Hey @Kushal997-das can you add label gssoc and level1, level2, or level3 
and also I am gonna add GenAI related projects and I will do it from strach so make it level 3.

**Comment by Kushal997-das** [comment]
> Hey @Kushal997-das can you add label gssoc and level1, level2, or level3 and also I am gonna add GenAI related projects and I will do it from strach so make it level 3.

Sure , but level I'm suppose to add .

**Comment by YugantGotmare** [comment]
@Kushal997-das can you change level 1 to level 2 or 3 ? Because I am gonna add GenAI project from scratch
