### ISSUE TITLE
GSSOC'24 Addition of 2048 game under Web-Development/Basic

### ISSUE THREAD

**Issue by AtharvKasar04** [Kushal997-das/Project-Guidance#986]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like.

A game called 2048 where user slides numbered tiles which combine and to reach 2048 number.

### Describe alternatives you've considered.

features may include:

- number of moves
- different grid sizes
- etc

### Add any other context or screenshots about the feature request here.

@Kushal997-das Can you please assign this issue to me under GSSoC'24. I would love to work on this addition.

Thank You!

**Comment by Kushal997-das** [comment]
@AtharvKasar04 Kindly share the Screenshot of it for better undersatding.

**Comment by Kushal997-das** [comment]
@AtharvKasar04 As no update so going to close the issue. Feel free to open a new one.
