### ISSUE TITLE
Gssoc 24' Calorie burnt prediction

### ISSUE THREAD

**Issue by Seersha9802** [Kushal997-das/Project-Guidance#989]
### Is your feature request related to a problem? Please describe.

The feature request I provided isn't directly related to a specific problem. Instead, it's a set of guidelines for predicting calories burnt outcomes within a project context. If there's a specific problem you're facing related to calorie tracking in a project, feel free to share, and I can tailor my response to address that particular issue.

### Describe the solution you'd like.

I might implement ml strategies and algorithms to predict calories burnt in strenuous activities within the project.

### Describe alternatives you've considered.

Another alternative machine learning (ML) model that could be considered is a deep learning model specifically trained on data of various people.

**Comment by Seersha9802** [comment]
I want to work on it please assign it to me

**Comment by MJakash** [comment]
Hey ! I have good experience on predictive modelling as well as machine learning. I will be pleased to work on this issue. Kindly assign me this issue

**Comment by Kushal997-das** [comment]
@Seersha9802 Your problem Statement is not clear to me, kindly explain bit details exactly what you want?

**Comment by Seersha9802** [comment]
I want to add this project proposal to machine learning beginner level project which enables them to have hands on experience. This model will consist of ML algos and XGBoost to predict calories burnt in any activity performed. I request you to assign me under gssoc'24 @Kushal997-das
