### ISSUE TITLE
Title: GSSoC'24 - Desktop Application - Python CLI Based - Screen Recorder

### ISSUE THREAD

**Issue by jindalpriyanshu101** [Kushal997-das/Project-Guidance#991]
### Is your proposal related to a problem? Please describe.

This project will allow users to record videos in HD quality, while they can name it to anything and any extension they would like to use. Eliminates the problem of low end pc where users couldn't use softwares like OBS Studio, or fed up by watermark of bandicam.

### Add any other context or screenshots about the proposal request here.

Yeah, here's few things one should know:

- Currently its CLI Based, doesn't record audio!
- video resolution: can modify resolution pixels according to their system
- Video FPS can be modified
- Additional error handling for filenames
- Custom key to stop recording (defaulted to 'q' incase of errors)

### Screenshot for better understanding:
![image](https://github.com/Kushal997-das/Project-Guidance/assets/52918255/d86370a4-4f0f-46e6-af9f-48554cb4d134)

**Comment by Kushal997-das** [comment]
@jindalpriyanshu101 Is this desktop application ?

**Comment by jindalpriyanshu101** [comment]
it is CLI based Desktop Application (.exe file) however a GUI can be introduced as well into it if required.

**Comment by Kushal997-das** [comment]
@Adhetya Yeah add GUI as well.
