### ISSUE TITLE
Title: Proper CSS for the entire page 

### ISSUE THREAD

**Issue by r7projects-shayan** [Kushal997-das/Project-Guidance#992]
### Is your feature request related to a problem? Please describe.

There is currently no proper css for the entire page and it doesn't look good. The UI is not so appealing.
![Screenshot 2024-05-12 124544](https://github.com/Kushal997-das/Project-Guidance/assets/167475552/84d74a63-62dc-49b0-8a86-bd17110ec845)

### Describe the solution you'd like.

Proper CSS following the industry principles to make the website more visually attractive so that users stay on it for long. 
This will make it easy to access the links and resources. 

### Describe alternatives you've considered.

Hover effect and smooth scroll

**Comment by r7projects-shayan** [comment]
@Kushal997-das Kindly assign me this issue. I will make the entire page look clean and magical for the users with my Frontend skills

**Comment by Kushal997-das** [comment]
@r7projects-shayan Will see your work if possible for us to add we will , go Ahed .

**Comment by Akshatakapare** [comment]
I would like to contribute to this issue. Could you please assign me this issue?

**Comment by r7projects-shayan** [comment]
Thanks @Kushal997-das I will start working on it

**Comment by JuhiVathsalya** [comment]
I would like to work on this issue . Could you please assign me to this

**Comment by r7projects-shayan** [comment]
@Kushal997-das Don't close this issue, the work is almost complete. I will raise the PR soon

**Comment by r7projects-shayan** [comment]
@Kushal997-das I have raised a new pull request by fixing the watchers section. Its fully responsive now #1103

**Comment by r7projects-shayan** [comment]
@Kushal997-das I have created the landing page, added interactive particle effects, made it responsive for all devices and dimensions in this PR, just as you asked me to do. 

Kindly assign the labels as you said in the last PR. #1165
