### ISSUE TITLE
Title: GSSOC'24 EDA on Zomato Dataset

### ISSUE THREAD

**Issue by AnushkaJMokashi** [Kushal997-das/Project-Guidance#993]
### Is your feature request related to a problem? Please describe.

I would like to add EDA (Exploratory Data Analysis) on Zomato dataset.

### Describe the solution you'd like.

In this, I would add all the steps for EDA which includes Data preprocessing, Visualization of data, Correlation, Handling Outliers, etc.

### Describe alternatives you've considered.

We can gain meaningful insights from the data. Step by step data preprocessing and Visualization. 

### Add any other context or screenshots about the feature request here.

![image](https://github.com/Kushal997-das/Project-Guidance/assets/100767949/4f751015-b4f9-4653-b065-e0ad914f3aa7)

**Comment by AnushkaJMokashi** [comment]
Requesting you to assign me this issue under GSSOC'24.

**Comment by palayushi293** [comment]
pls assign this to me  under GGSOC'24
Waiting for your response

**Comment by AnushkaJMokashi** [comment]
@Kushal997-das Since I opened this issue, kindly assign it to me under GSSOC'24. I would love to contribute.

**Comment by MJakash** [comment]
hey! i have experience on machine learning and exploratory data analysis.its pleasure to contribute to this issue if assigned.

**Comment by Kushal997-das** [comment]
> hey! i have experience on machine learning and exploratory data analysis.its pleasure to contribute to this issue if assigned.

Please don't spam in other Issue .

**Comment by Kushal997-das** [comment]
> pls assign this to me under GGSOC'24 Waiting for your response

Please don't spam in other issue .

**Comment by Kushal997-das** [comment]
@AnushkaJMokashi Will assign you but this goes under basic level , will check your project then will add if possible  for now go ahead and send PR.
