### ISSUE TITLE
[ Missing Error 404 page]

### ISSUE THREAD

**Issue by r7projects-shayan** [Kushal997-das/Project-Guidance#994]
### What happened?

There is currently no Error 404 Page to alert the users when they click on any wrong link or visit any wrong url. 

### How can we reproduce this bug?

A dedicated Error 404 page for the users to land on as and when they visit any wrong url or click on any wrong link 

The users will be redirected back to the homepage

![Screenshot 2024-05-12 125533](https://github.com/Kushal997-das/Project-Guidance/assets/167475552/60248558-7c6f-45b1-8373-d78711cd3212)
![Screenshot 2024-05-12 130156](https://github.com/Kushal997-das/Project-Guidance/assets/167475552/173886e9-1968-41ad-ba8d-6d403b62e18e)
![Screenshot 2024-05-12 130218](https://github.com/Kushal997-das/Project-Guidance/assets/167475552/4b4cddbd-b14f-4eba-8603-83cb0ccdf4f2)

### Urgency (Optional)

High priority

**Comment by r7projects-shayan** [comment]
@Kushal997-das Kindly assign me this issue so that I can start working on it

**Comment by Kushal997-das** [comment]
@r7projects-shayan Explain in details not clear

**Comment by Kushal997-das** [comment]
@r7projects-shayan As no update closing this Issue.
