### ISSUE TITLE
Title: using GANS to classify MNSIT digits 

### ISSUE THREAD

**Issue by Nicole09999** [Kushal997-das/Project-Guidance#995]
### Is your feature request related to a problem? Please describe.

there is a similar project of classification of digits using ANN but i want to try a different ML technique that is GANS with your permission .

### Describe the solution you'd like.

to generate the digits by building the generator and discriminator from scratch to form a DC GAN

### Describe alternatives you've considered.

GANS is a part of unsupervised learning ..there are various supervised learning techniques available 

### Add any other context or screenshots about the feature request here.

something like this 
![image](https://github.com/Kushal997-das/Project-Guidance/assets/106644205/f97b7feb-76bf-4ae3-b24e-42966e1709f6)

**Comment by Nicole09999** [comment]
if approved ,please assign this to me under GSSOC24

**Comment by Kushal997-das** [comment]
@Nicole09999 We have this already. thanks
