### ISSUE TITLE
Title: Screen time analysis using Python 

### ISSUE THREAD

**Issue by poojaharihar03** [Kushal997-das/Project-Guidance#997]
Using python data visalization we can analyze the relation between time screen and notifcayions
I have personally worked on this and is good for beginner to start with Data analysis. Looking to add this in the repo. .kindly assign me this issue

**Comment by sush123-mita** [comment]
hey @Kushal997-das i have learnt python . i m a beginner and is looking forward for a opportunity to work upon this issue.kindly assign me this issue

**Comment by Kushal997-das** [comment]
> hey @Kushal997-das i have learnt python . i m a beginner and is looking forward for a opportunity to work upon this issue.kindly assign me this issue

This issue you haven't open so it's not possible to assign you , but you can contact me . I'll help

**Comment by Kushal997-das** [comment]
@poojaharihar03 Explain your issue in more details.

**Comment by poojaharihar03** [comment]
@Kushal997-das 
so the idea is for a given dataset, need to see the relation between the usage of devices to the number of notifications apps, etc.
It is a beginner level for data analysis in python and a useful way to dive in to the data analysis

**Comment by Kushal997-das** [comment]
@poojaharihar03 What category the project is? Under which folder are you going to add ?

**Comment by poojaharihar03** [comment]
@Kushal997-das 
since it is data analysis i guess I can add it in machine learning basics right?

**Comment by sush123-mita** [comment]
> > hey @Kushal997-das i have learnt python . i m a beginner and is looking forward for a opportunity to work upon this issue.kindly assign me this issue
> 
> This issue you haven't open so it's not possible to assign you , but you can contact me . I'll help

How can i open it ..  i dodnt get it. Can you please help

**Comment by shikham12** [comment]
please assign me this issue

**Comment by Kushal997-das** [comment]
> > > hey @Kushal997-das i have learnt python . i m a beginner and is looking forward for a opportunity to work upon this issue.kindly assign me this issue
> > 
> > 
> > This issue you haven't open so it's not possible to assign you , but you can contact me . I'll help
> 
> How can i open it .. i didnt get it. Can you please help

[Contact me ](https://www.linkedin.com/in/kushal-das-7337421a9/)

**Comment by Kushal997-das** [comment]
> @Kushal997-das since it is data analysis i guess I can add it in machine learning basics right?

Yes
